{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLSecurityCodeFormatter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlsecuritycodeformatter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlsecuritycodeformatter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Used to format the security code."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:formatter:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLSecurityCodeFormatter"}],"title":"DLSecurityCodeFormatter","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeFormatter","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DLSecurityCodeFormatter"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter\/init(brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter\/init(maxLength:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter\/maxLength"]}],"references":{"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeFormatter/init(maxLength:)":{"role":"symbol","title":"init(maxLength:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a formatter instance."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter\/init(maxLength:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMaxLength:"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodeformatter\/init(maxlength:)"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(securityCode:formatter:)":{"role":"symbol","title":"format(securityCode:formatter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"formatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLSecurityCodeFormatter","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeFormatter"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Format the security code using your own rules."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:formatter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formatWithSecurityCode:formatter:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(securitycode:formatter:)"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeFormatter/init(brand:)":{"role":"symbol","title":"init(brand:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter\/init(brand:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBrand:"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodeformatter\/init(brand:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeFormatter":{"role":"symbol","title":"DLSecurityCodeFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLSecurityCodeFormatter"}],"abstract":[{"type":"text","text":"Used to format the security code."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:formatter:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLSecurityCodeFormatter"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodeformatter"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeFormatter/maxLength":{"role":"symbol","title":"maxLength","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter\/maxLength","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxLength"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodeformatter\/maxlength"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"},"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DLSecurityCodeFormatter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLSecurityCodeFormatter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DLSecurityCodeFormatter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter\/maxLength"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter\/init(brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter\/init(maxLength:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLSecurityCodeFormatter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter~1init(maxLength:)\/title","value":"initWithMaxLength:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter~1init(maxLength:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMaxLength:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:formatter:)\/title","value":"formatWithSecurityCode:formatter:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:formatter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithSecurityCode:formatter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter~1init(brand:)\/title","value":"initWithBrand:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter~1init(brand:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBrand:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter\/title","value":"DLSecurityCodeFormatter"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter\/fragments","value":[{"kind":"identifier","text":"DLSecurityCodeFormatter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter~1maxLength\/title","value":"maxLength"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter~1maxLength\/fragments","value":[{"kind":"identifier","text":"maxLength"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}