{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"density"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity","text":"DLImageDensity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize","text":"DLImageSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"density","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The resolution of the image"}]}]},{"name":"size","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The size of the image"}]}]},{"name":"background","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the image should have an opaque background (true) or it should be transparent (false)"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The remote URL for the image or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the image is not available"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/cardimage(density:size:background:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/cardimage(density:size:background:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/cardImage(density:size:background:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Generates the image URL for this brand with the given configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"density"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLImageDensity","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLImageSize","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"title":"cardImage(density:size:background:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrand(im)cardImageWithDensity:size:background:","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"cardImageWithDensity:size:background:"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"role":"symbol","title":"DLCardBrand","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrand"}],"abstract":[{"type":"text","text":"The brand identifing the issuer of a card."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrand"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/cardImage(density:size:background:)":{"role":"symbol","title":"cardImage(density:size:background:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"density"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLImageDensity","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLImageSize","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Generates the image URL for this brand with the given configuration."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/cardImage(density:size:background:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cardImageWithDensity:size:background:"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand\/cardimage(density:size:background:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize":{"role":"symbol","title":"DLImageSize","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLImageSize"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLImageSize"}],"url":"\/documentation\/dldirectsdk\/dlimagesize"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity":{"role":"symbol","title":"DLImageDensity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLImageDensity"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLImageDensity"}],"url":"\/documentation\/dldirectsdk\/dlimagedensity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cardImageWithDensity:size:background:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cardImageWithDensity:size:background:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"cardImageWithDensity:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity","text":"DLImageDensity"},{"kind":"text","text":") "},{"kind":"internalParam","text":"density"},{"kind":"text","text":" "},{"kind":"identifier","text":"size:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize","text":"DLImageSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":" "},{"kind":"identifier","text":"background:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"background"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","value":"DLCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","value":[{"kind":"identifier","text":"DLCardBrand"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1cardImage(density:size:background:)\/title","value":"cardImageWithDensity:size:background:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1cardImage(density:size:background:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cardImageWithDensity:size:background:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/title","value":"DLImageSize"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/fragments","value":[{"kind":"identifier","text":"DLImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/title","value":"DLImageDensity"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/fragments","value":[{"kind":"identifier","text":"DLImageDensity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}