{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SE","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"metadata":{"symbolKind":"class","roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLInstallmentsPlan","kind":"identifier"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLInstallmentsPlan","navigatorTitle":[{"kind":"identifier","text":"DLInstallmentsPlan"}],"modules":[{"name":"DLDirectSDK"}],"title":"DLInstallmentsPlan"},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/init(from:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/id","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installmentAmount","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installments","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/totalAmount"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/CodingKeys"],"title":"Enumerations"}],"abstract":[{"text":"One of the available installments options.","type":"text"},{"text":" ","type":"text"},{"text":"This is used as output parameter in the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","isActive":true,"type":"reference"},{"type":"text","text":" method."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLInstallmentsPlan"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlinstallmentsplan"]},{"paths":["\/documentation\/dldirectsdk\/dlinstallmentsplan"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dlocal.DLDirectSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getBinInformation"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"currencyCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"amount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"DLBinInfo","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"DLError","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Get bin information and installments.","type":"text"}],"navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan/init(from:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/init(from:)","abstract":[],"kind":"symbol","title":"init(from:)","url":"\/documentation\/dldirectsdk\/dlinstallmentsplan\/init(from:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan/totalAmount":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"totalAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"totalAmount"}],"abstract":[{"type":"text","text":"The total amount that would be paid, e.g. 1200."}],"role":"symbol","title":"totalAmount","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/totalAmount","type":"topic","url":"\/documentation\/dldirectsdk\/dlinstallmentsplan\/totalamount"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLInstallmentsPlan","kind":"identifier"}],"abstract":[{"type":"text","text":"One of the available installments options."},{"text":" ","type":"text"},{"type":"text","text":"This is used as output parameter in the "},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","isActive":true},{"type":"text","text":" method."}],"navigatorTitle":[{"text":"DLInstallmentsPlan","kind":"identifier"}],"title":"DLInstallmentsPlan","url":"\/documentation\/dldirectsdk\/dlinstallmentsplan","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan/installments":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installments","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"installments","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","type":"topic","abstract":[{"text":"The number of installments, e.g. 6.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlinstallmentsplan\/installments","navigatorTitle":[{"text":"installments","kind":"identifier"}],"title":"installments","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan/id":{"abstract":[{"type":"text","text":"The identifier of the installment option."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"id"}],"role":"symbol","url":"\/documentation\/dldirectsdk\/dlinstallmentsplan\/id","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/id","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"id"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","url":"\/documentation\/dldirectsdk","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/SQ":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan/CodingKeys":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CodingKeys","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlinstallmentsplan\/codingkeys","title":"DLInstallmentsPlan.CodingKeys","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CodingKeys"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/CodingKeys","abstract":[],"type":"topic","role":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan/installmentAmount":{"title":"installmentAmount","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"installmentAmount"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","role":"symbol","abstract":[{"text":"The amount paid on each installment, e.g. 200.","type":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installmentAmount","navigatorTitle":[{"kind":"identifier","text":"installmentAmount"}],"url":"\/documentation\/dldirectsdk\/dlinstallmentsplan\/installmentamount"},"doc://com.dlocal.DLDirectSDK/Se":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/SE":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DLInstallmentsPlan","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"DLInstallmentsPlan"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DLInstallmentsPlan","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/id","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installmentAmount","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installments","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/totalAmount"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLInstallmentsPlan","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"},{"value":[{"text":"- ","kind":"text"},{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1totalAmount\/title","value":"totalAmount","op":"replace"},{"op":"replace","value":[{"text":"totalAmount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1totalAmount\/fragments"},{"value":"DLInstallmentsPlan","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan\/fragments","op":"replace","value":[{"text":"DLInstallmentsPlan","kind":"identifier"}]},{"value":"installments","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1installments\/title"},{"value":[{"text":"installments","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1installments\/fragments"},{"value":"id","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1id\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1id\/fragments","value":[{"kind":"identifier","text":"id"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1installmentAmount\/title","value":"installmentAmount"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1installmentAmount\/fragments","value":[{"text":"installmentAmount","kind":"identifier"}],"op":"replace"}]}]}