{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardToken"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken"},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardtoken"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardtoken"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SE","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLCardToken","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardToken","navigatorTitle":[{"text":"DLCardToken","kind":"identifier"}],"title":"DLCardToken","symbolKind":"class","modules":[{"name":"DLDirectSDK"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken\/token"]}],"kind":"symbol","abstract":[{"text":"The card number tokenized.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This is the output of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)"},{"text":" method.","type":"text"}],"sections":[],"references":{"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardToken/init(from:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtoken\/init(from:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken\/init(from:)","abstract":[],"title":"init(from:)"},"doc://com.dlocal.DLDirectSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SE"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[],"url":"\/documentation\/dldirectsdk","role":"collection"},"doc://com.dlocal.DLDirectSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardToken":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardToken","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtoken","navigatorTitle":[{"kind":"identifier","text":"DLCardToken"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken","abstract":[{"type":"text","text":"The card number tokenized."},{"type":"text","text":" "},{"text":"This is the output of the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","isActive":true,"type":"reference"},{"text":" method.","type":"text"}],"title":"DLCardToken"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardToken/token":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"text":"The token representing this card securely tokenized.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"token","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken\/token","title":"token","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtoken\/token"},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","title":"Swift.Equatable"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/tokenizeCard(cardData:onSuccess:onError:)":{"navigatorTitle":[{"text":"tokenizeCardWithCardData:onSuccess:onError:","kind":"identifier"}],"title":"tokenizeCard(cardData:onSuccess:onError:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","abstract":[{"type":"text","text":"Tokenizes a card."}],"kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/tokenizecard(carddata:onsuccess:onerror:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tokenizeCard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardData"},{"text":": ","kind":"text"},{"text":"DLCardData","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardToken","text":"DLCardToken"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"DLError","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.dlocal.DLDirectSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","title":"Swift.Decodable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"DLCardToken","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardToken"}]},{"op":"replace","value":[{"text":"DLCardToken","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken\/token"],"title":"Instance Properties"}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardToken"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DLCardToken","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken\/fragments","value":[{"text":"DLCardToken","kind":"identifier"}],"op":"replace"},{"value":"token","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken~1token\/title"},{"op":"replace","value":[{"text":"token","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken~1token\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/title","value":"tokenizeCardWithCardData:onSuccess:onError:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenizeCardWithCardData:onSuccess:onError:"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}