{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/luhn","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/naranja","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/other"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/Equatable-Implementations","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/RawRepresentable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"title":"DLCardBrandValidationAlgorithm","symbolKind":"enum","modules":[{"name":"DLDirectSDK"}]},"abstract":[{"type":"text","text":"The algorithm used for validating the brand’s card numbers."}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH","doc:\/\/com.dlocal.DLDirectSDK\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/init(rawvalue:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/rawrepresentable-implementations"},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","title":"Swift.Equatable"},"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","title":"Swift.Hashable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/equatable-implementations"},"doc://com.dlocal.DLDirectSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm/luhn":{"abstract":[],"title":"DLCardBrandValidationAlgorithm.luhn","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/luhn","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithmLuhn"}],"role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/luhn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"luhn","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm/other":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithmOther"}],"abstract":[],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/other","title":"DLCardBrandValidationAlgorithm.other","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"other"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/other"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[],"url":"\/documentation\/dldirectsdk","role":"collection"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"role":"symbol","abstract":[{"type":"text","text":"The algorithm used for validating the brand’s card numbers."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm","title":"DLCardBrandValidationAlgorithm"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm/naranja":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/naranja","url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/naranja","abstract":[],"type":"topic","title":"DLCardBrandValidationAlgorithm.naranja","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"naranja","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandValidationAlgorithmNaranja","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DLCardBrandValidationAlgorithm"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/luhn","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/naranja","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/other"],"title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DLCardBrandValidationAlgorithmLuhn","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1luhn\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1luhn\/fragments","value":[{"text":"DLCardBrandValidationAlgorithmLuhn","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1other\/title","value":"DLCardBrandValidationAlgorithmOther","op":"replace"},{"value":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithmOther"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1other\/fragments"},{"value":"DLCardBrandValidationAlgorithm","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/title"},{"op":"replace","value":[{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/fragments"},{"value":"DLCardBrandValidationAlgorithmNaranja","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1naranja\/title","op":"replace"},{"op":"replace","value":[{"text":"DLCardBrandValidationAlgorithmNaranja","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1naranja\/fragments"}]}]}