{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"metadata":{"role":"symbol","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardExpert","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardExpert"}],"title":"DLCardExpert","symbolKind":"class"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/init(countryCode:testMode:options:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/allBrands","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/countryCode","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/resolvedCountryCode"]},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/brand(withIdentifier:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(binNumber:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(cardNumber:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(date:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(expirationMonth:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(expirationYear:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(holderName:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(expirationDate:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(holderName:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:brands:)"],"title":"Instance Methods"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Used  to perform various operations around cards, like format a card number or validate an expiration date.","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardExpert","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumber:brand:)":{"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumber:brand:)","abstract":[{"text":"Fromat a card number to match what’s shown on the card.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The difference between this and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)"},{"text":" is that we will not attempt to detect the brand from the number, instead we will use what you pass as parameter.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"text":"cardNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"brand","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DLCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"formatWithCardNumber:brand:"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","type":"topic","title":"format(cardNumber:brand:)","role":"symbol","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/init(countryCode:testMode:options:)":{"kind":"symbol","title":"init(countryCode:testMode:options:)","navigatorTitle":[{"text":"initWithCountryCode:testMode:options:","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/init(countryCode:testMode:options:)","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardexpert\/init(countrycode:testmode:options:)","abstract":[{"type":"text","text":"Initializes the card expert."}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"testMode"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(cardNumber:)":{"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate a card number."}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(cardnumber:)","title":"validate(cardNumber:)","kind":"symbol","navigatorTitle":[{"text":"validateWithCardNumber:","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/resolvedCountryCode":{"abstract":[{"text":"Country code resolved at runtime. When you pass an unsupported or unrecognized country code, we will default you to the list of “GLOBAL” cards which are globally accepted cards.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/resolvedCountryCode","title":"resolvedCountryCode","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"resolvedCountryCode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/resolvedcountrycode","navigatorTitle":[{"text":"resolvedCountryCode","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"url":"\/documentation\/dldirectsdk\/dlcardexpert","abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLCardExpert","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardExpert","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","type":"topic","title":"DLCardExpert","role":"symbol","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(expirationYear:)":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(expirationYear:)","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(expirationyear:)","abstract":[{"type":"text","text":"Format the expiration year."},{"text":" ","type":"text"},{"type":"text","text":"This will disallow entering invalid characters."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"text":"(","kind":"text"},{"text":"expirationYear","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"formatWithExpirationYear:"}],"title":"format(expirationYear:)","role":"symbol"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumberEndingWith:)":{"kind":"symbol","navigatorTitle":[{"text":"formatWithCardNumberEndingWith:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cardNumberEndingWith"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Format the card number using the last digits."},{"type":"text","text":" "},{"text":"If you know the brand of the card then you can use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)"},{"type":"text","text":" which will provide a formatted version that matches what’s on the card."}],"title":"format(cardNumberEndingWith:)","url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumberendingwith:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(expirationMonth:)":{"role":"symbol","abstract":[{"text":"Format the expiration month.","type":"text"},{"text":" ","type":"text"},{"text":"This will for instance turn “3” into “03” and disallow entering invalid characters.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(expirationMonth:)","title":"format(expirationMonth:)","url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(expirationmonth:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"expirationMonth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"formatWithExpirationMonth:"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(holderName:)":{"role":"symbol","abstract":[{"type":"text","text":"Validate the holder name."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(holderName:)","title":"validate(holderName:)","url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(holdername:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"text":"holderName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithHolderName:"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/detectBrand(cardNumber:)":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(cardNumber:)","type":"topic","abstract":[{"type":"text","text":"Detect the brand from the given card number."}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/detectbrand(cardnumber:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectBrand"},{"kind":"text","text":"("},{"text":"cardNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"detectBrandWithCardNumber:"}],"title":"detectBrand(cardNumber:)","role":"symbol"},"doc://com.dlocal.DLDirectSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/brand(withIdentifier:)":{"abstract":[{"text":"Get the brand from a given identifier.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/brand(withidentifier:)","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/brand(withIdentifier:)","title":"brand(withIdentifier:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifier"},{"text":": ","kind":"text"},{"text":"DLCardBrandIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"brandWithIdentifier:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumberEndingWith:brand:)":{"navigatorTitle":[{"kind":"identifier","text":"formatWithCardNumberEndingWith:brand:"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:brand:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"kind":"text","text":"("},{"text":"cardNumberEndingWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","title":"format(cardNumberEndingWith:brand:)","abstract":[{"text":"Format the card number using the last digits.","type":"text"},{"type":"text","text":" "},{"text":"The difference between this and ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:)"},{"text":" is that you specify what brand to use.","type":"text"},{"type":"text","text":" "},{"text":"This is preferred as it will make the formatted string match what’s displayed on the brand.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumberendingwith:brand:)","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/countryCode":{"kind":"symbol","title":"countryCode","navigatorTitle":[{"text":"countryCode","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/countryCode","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardexpert\/countrycode","abstract":[{"text":"Country code passed at initialization.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/allBrands":{"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardexpert\/allbrands","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/allBrands","title":"allBrands","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allBrands"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"text":"]","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allBrands"}],"abstract":[{"text":"The brands available in expert instance.","type":"text"},{"type":"text","text":" "},{"text":"For example, if you passed “US” as country code at initialization, these would be the card brands available in “United States”.","type":"text"}]},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(securityCode:brands:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"securityCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"brands","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier","text":"DLCardBrand"},{"text":"]) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Validate the security code for a list of specific brands.","type":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:brands:)","navigatorTitle":[{"kind":"identifier","text":"validateWithSecurityCode:brands:"}],"role":"symbol","kind":"symbol","title":"validate(securityCode:brands:)","url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(securitycode:brands:)","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(securityCode:)":{"abstract":[{"type":"text","text":"Format the security code."},{"text":" ","type":"text"},{"type":"text","text":"Thsi will disallow entering invalid characters and will limit the input to a valid length."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:)","title":"format(securityCode:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"format","kind":"identifier"},{"kind":"text","text":"("},{"text":"securityCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(securitycode:)","navigatorTitle":[{"text":"formatWithSecurityCode:","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumber:)":{"kind":"symbol","title":"format(cardNumber:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumber:)","navigatorTitle":[{"kind":"identifier","text":"formatWithCardNumber:"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:)","abstract":[{"text":"Formats the card number to match what’s shown on the card.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example if input is “424242424”, we will detect this is an incomplete VISA card and will return “4242 4242 4”."},{"text":" ","type":"text"},{"text":"If you already know the brand of the card you can use ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","isActive":true},{"type":"text","text":" instead."}],"type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","url":"\/documentation\/dldirectsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","role":"collection"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(securityCode:)":{"abstract":[{"text":"Validate the security code.","type":"text"}],"title":"validate(securityCode:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(securitycode:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithSecurityCode:"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/detectBrand(binNumber:)":{"role":"symbol","abstract":[{"text":"Detect the brand from the given bin number.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(binNumber:)","type":"topic","title":"detectBrand(binNumber:)","url":"\/documentation\/dldirectsdk\/dlcardexpert\/detectbrand(binnumber:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"detectBrand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"text":"DLCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"detectBrandWithBinNumber:"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(expirationDate:)":{"navigatorTitle":[{"text":"validateWithExpirationDate:","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(expirationdate:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(expirationDate:)","abstract":[{"text":"Validate the expiration date.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Validation includes proper formatting of the expiration date and also that card is not expired."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"text":"expirationDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"validate(expirationDate:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(holderName:)":{"abstract":[{"type":"text","text":"Formats the holder name to match the formatting shown in the card."}],"kind":"symbol","title":"format(holderName:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(holderName:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formatWithHolderName:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"holderName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(holdername:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(securityCode:brand:)":{"abstract":[{"text":"Format the security code using a specific brand.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Use this if you know the brand of the card for which the security code belongs. This will improve the validation rules."}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(securitycode:brand:)","title":"format(securityCode:brand:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:brand:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":"(","kind":"text"},{"text":"securityCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"brand","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"text":"formatWithSecurityCode:brand:","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(securityCode:brand:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"securityCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"brand","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier","text":"DLCardBrand"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate the security code for a specific brand."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:brand:)","navigatorTitle":[{"text":"validateWithSecurityCode:brand:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"validate(securityCode:brand:)","url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(securitycode:brand:)","type":"topic"},"doc://com.dlocal.DLDirectSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(date:)":{"title":"format(date:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"formatWithDate:"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(date:)","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(date:)","abstract":[{"type":"text","text":"Format the expiration month and year."},{"type":"text","text":" "},{"text":"This will disallow entering invalid characters while also provide a guide while entering this value when both month and year are in the same field.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"kind":"text","text":"("},{"text":"date","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DLCardExpert"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"DLCardExpert"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DLCardExpert","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/allBrands","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/countryCode","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/resolvedCountryCode"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/brand(withIdentifier:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(binNumber:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(cardNumber:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(date:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(expirationMonth:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(expirationYear:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(holderName:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/init(countryCode:testMode:options:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(expirationDate:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(holderName:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:brands:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DLCardExpert","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"formatWithCardNumber:brand:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:brand:)\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:brand:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"formatWithCardNumber:brand:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1init(countryCode:testMode:options:)\/title","value":"initWithCountryCode:testMode:options:","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1init(countryCode:testMode:options:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCountryCode:testMode:options:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(cardNumber:)\/title","value":"validateWithCardNumber:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(cardNumber:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithCardNumber:","kind":"identifier"}]},{"op":"replace","value":"resolvedCountryCode","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1resolvedCountryCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1resolvedCountryCode\/fragments","value":[{"kind":"identifier","text":"resolvedCountryCode"}]},{"value":"DLCardExpert","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","op":"replace"},{"value":[{"text":"DLCardExpert","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(expirationYear:)\/title","op":"replace","value":"formatWithExpirationYear:"},{"value":[{"text":"- ","kind":"text"},{"text":"formatWithExpirationYear:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(expirationYear:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumberEndingWith:)\/title","value":"formatWithCardNumberEndingWith:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumberEndingWith:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"formatWithCardNumberEndingWith:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(expirationMonth:)\/title","value":"formatWithExpirationMonth:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"formatWithExpirationMonth:"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(expirationMonth:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(holderName:)\/title","value":"validateWithHolderName:"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(holderName:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithHolderName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1detectBrand(cardNumber:)\/title","value":"detectBrandWithCardNumber:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1detectBrand(cardNumber:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"detectBrandWithCardNumber:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1brand(withIdentifier:)\/title","value":"brandWithIdentifier:"},{"value":[{"text":"- ","kind":"text"},{"text":"brandWithIdentifier:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1brand(withIdentifier:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumberEndingWith:brand:)\/title","value":"formatWithCardNumberEndingWith:brand:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"formatWithCardNumberEndingWith:brand:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumberEndingWith:brand:)\/fragments","op":"replace"},{"value":"countryCode","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1countryCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"countryCode"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1countryCode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1allBrands\/title","value":"allBrands","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1allBrands\/fragments","op":"replace","value":[{"kind":"identifier","text":"allBrands"}]},{"value":"validateWithSecurityCode:brands:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:brands:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithSecurityCode:brands:"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:brands:)\/fragments","op":"replace"},{"value":"formatWithSecurityCode:","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithSecurityCode:"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:)\/fragments"},{"value":"formatWithCardNumber:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"formatWithCardNumber:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:)\/fragments"},{"value":"validateWithSecurityCode:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:)\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"validateWithSecurityCode:"}],"op":"replace"},{"value":"detectBrandWithBinNumber:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1detectBrand(binNumber:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectBrandWithBinNumber:"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1detectBrand(binNumber:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(expirationDate:)\/title","value":"validateWithExpirationDate:"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(expirationDate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"validateWithExpirationDate:"}]},{"value":"formatWithHolderName:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(holderName:)\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(holderName:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"formatWithHolderName:","kind":"identifier"}],"op":"replace"},{"value":"formatWithSecurityCode:brand:","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:brand:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"formatWithSecurityCode:brand:"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:brand:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:brand:)\/title","value":"validateWithSecurityCode:brand:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"validateWithSecurityCode:brand:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:brand:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(date:)\/title","value":"formatWithDate:"},{"value":[{"kind":"text","text":"- "},{"text":"formatWithDate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(date:)\/fragments"}]}]}