{"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/init(from:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/excludePattern","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/gaps","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/identifier","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/images","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/lengths","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/niceName","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/patterns","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/patternsObjc","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/rawIdentifier","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/securityCode","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/validation"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/cardImage(density:size:background:)"]}],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrand"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrand"]}],"sections":[],"kind":"symbol","abstract":[{"text":"The brand identifing the issuer of a card.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrand"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","title":"DLCardBrand","navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}],"modules":[{"name":"DLDirectSDK"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrand","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","interfaceLanguage":"swift"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/cardImage(density:size:background:)":{"url":"\/documentation\/dldirectsdk\/dlcardbrand\/cardimage(density:size:background:)","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/cardImage(density:size:background:)","title":"cardImage(density:size:background:)","role":"symbol","abstract":[{"type":"text","text":"Generates the image URL for this brand with the given configuration."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"density"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity","text":"DLImageDensity"},{"kind":"text","text":", "},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize","text":"DLImageSize"},{"kind":"text","text":", "},{"text":"background","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cardImageWithDensity:size:background:"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"title":"DLCardBrand","navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrand","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand","type":"topic","abstract":[{"text":"The brand identifing the issuer of a card.","type":"text"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/identifier":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DLCardBrandIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","title":"identifier","url":"\/documentation\/dldirectsdk\/dlcardbrand\/identifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/identifier","role":"symbol","abstract":[{"type":"text","text":"Identifier of the brand, like .visa or .mastercard"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/patternsObjc":{"url":"\/documentation\/dldirectsdk\/dlcardbrand\/patternsobjc","navigatorTitle":[{"kind":"identifier","text":"patternsObjc"}],"kind":"symbol","abstract":[{"type":"text","text":"Same as "},{"code":"patterns","type":"codeVoice"},{"type":"text","text":" but exposed specifically to Objective-C (as enums with associated values cannot be exposed)."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"patternsObjc"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrandPatternObjc","text":"DLCardBrandPatternObjc"},{"text":"]","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/patternsObjc","type":"topic","title":"patternsObjc"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/securityCode":{"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrand\/securitycode","type":"topic","abstract":[{"text":"Security code information.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"securityCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrandSecurityCode","kind":"typeIdentifier","text":"DLCardBrandSecurityCode"}],"navigatorTitle":[{"kind":"identifier","text":"securityCode"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/securityCode","title":"securityCode"},"doc://com.dlocal.DLDirectSDK/SH":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/init(from:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrand\/init(from:)","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/init(from:)","type":"topic","title":"init(from:)","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/gaps":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gaps","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]"}],"type":"topic","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrand\/gaps","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/gaps","title":"gaps","role":"symbol","abstract":[{"text":"Position of the blank spaces in the card number, used for formatting a card number to match what’s seen in the physical card.","type":"text"}],"navigatorTitle":[{"text":"gaps","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/niceName":{"url":"\/documentation\/dldirectsdk\/dlcardbrand\/nicename","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/niceName","title":"niceName","abstract":[{"type":"text","text":"Nice name of the brand to be shown to users, like “Visa” or “Mastercard”."}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"niceName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"niceName"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/excludePattern":{"url":"\/documentation\/dldirectsdk\/dlcardbrand\/excludepattern","navigatorTitle":[{"text":"excludePattern","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Regular expresion indicating the card patterns that do not match this brand.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"excludePattern"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/excludePattern","type":"topic","title":"excludePattern"},"doc://com.dlocal.DLDirectSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/lengths":{"type":"topic","kind":"symbol","abstract":[{"text":"Length of the card number.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand\/lengths","title":"lengths","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/lengths","navigatorTitle":[{"text":"lengths","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lengths"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":"]?"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/patterns":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/patterns","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"patterns"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DLDirectSDK18DLCardBrandPatternO","text":"DLCardBrandPattern"},{"text":"]","kind":"text"}],"type":"topic","title":"patterns","abstract":[{"type":"text","text":"Patterns used to know whether a card number belongs to this brand or not."}],"url":"\/documentation\/dldirectsdk\/dlcardbrand\/patterns","role":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/images":{"url":"\/documentation\/dldirectsdk\/dlcardbrand\/images","navigatorTitle":[{"text":"images","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"URL of the brand card with logo."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"images"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBrandImage","text":"DLBrandImage"},{"text":"]?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/images","type":"topic","title":"images"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/rawIdentifier":{"type":"topic","abstract":[{"text":"Raw identifier of the brand, like “visa” or “mastercard”","type":"text"}],"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrand\/rawidentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/rawIdentifier","title":"rawIdentifier","navigatorTitle":[{"text":"rawIdentifier","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"rawIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/validation":{"abstract":[{"text":"Validation algorithm used to ensure the card number is valid.","type":"text"}],"title":"validation","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/validation","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrand\/validation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"validation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DLCardBrandValidationAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm"}],"navigatorTitle":[{"kind":"identifier","text":"validation"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DLCardBrand","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DLCardBrand","kind":"identifier"}]},{"op":"replace","value":[{"text":"DLCardBrand","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/excludePattern","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/gaps","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/images","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/lengths","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/niceName","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/patternsObjc","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/rawIdentifier","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/securityCode","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/validation"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/cardImage(density:size:background:)"]}]},{"value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrand"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"cardImageWithDensity:size:background:","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1cardImage(density:size:background:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cardImageWithDensity:size:background:"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1cardImage(density:size:background:)\/fragments","op":"replace"},{"value":"DLCardBrand","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","value":[{"kind":"identifier","text":"DLCardBrand"}]},{"op":"replace","value":"patternsObjc","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1patternsObjc\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1patternsObjc\/fragments","value":[{"text":"patternsObjc","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1securityCode\/title","value":"securityCode","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"securityCode"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1securityCode\/fragments"},{"value":"gaps","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1gaps\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1gaps\/fragments","value":[{"text":"gaps","kind":"identifier"}]},{"value":"niceName","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1niceName\/title"},{"value":[{"text":"niceName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1niceName\/fragments","op":"replace"},{"value":"excludePattern","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1excludePattern\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1excludePattern\/fragments","value":[{"kind":"identifier","text":"excludePattern"}]},{"op":"replace","value":"lengths","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1lengths\/title"},{"op":"replace","value":[{"kind":"identifier","text":"lengths"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1lengths\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1images\/title","value":"images"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1images\/fragments","op":"replace","value":[{"kind":"identifier","text":"images"}]},{"value":"rawIdentifier","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1rawIdentifier\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1rawIdentifier\/fragments","value":[{"text":"rawIdentifier","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1validation\/title","value":"validation"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1validation\/fragments","value":[{"kind":"identifier","text":"validation"}]}]}]}