{"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/apiKeyInvalid","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/clientNetworkingError","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/internalClientError","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/serverError"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/Equatable-Implementations","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH","doc:\/\/com.dlocal.DLDirectSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLErrorType"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlerrortype"]},{"paths":["\/documentation\/dldirectsdk\/dlerrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"DLErrorType","symbolKind":"enum","externalID":"c:@M@DLDirectSDK@E@DLErrorType","roleHeading":"Enumeration","modules":[{"name":"DLDirectSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLErrorType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLErrorType"}]},"sections":[],"abstract":[{"text":"Categorizes the possible errors that can be returned by our APIs.","type":"text"}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/internalClientError":{"url":"\/documentation\/dldirectsdk\/dlerrortype\/internalclienterror","title":"DLErrorType.internalClientError","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/internalClientError","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalClientError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeInternalClientError"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This usually indicates an error in the library code and there isn’t anything you could do about it. Please contact dlocal if this happens."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/init(rawValue:)","url":"\/documentation\/dldirectsdk\/dlerrortype\/init(rawvalue:)","role":"symbol","abstract":[]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/serverError":{"url":"\/documentation\/dldirectsdk\/dlerrortype\/servererror","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/serverError","title":"DLErrorType.serverError","role":"symbol","abstract":[{"text":"Our server returned an unsuccessful response. This could be an issue with your input or our API is unavailable. Please contact dlocal if this happens continously.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"serverError"}],"navigatorTitle":[{"text":"DLErrorTypeServerError","kind":"identifier"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/apiKeyInvalid":{"type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"API-KEY"},{"type":"text","text":" provided is invalid. Please check that you are not using the production key for testing or vice versa. Please contact dlocal if you are unable to get this fixed."}],"title":"DLErrorType.apiKeyInvalid","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/apiKeyInvalid","role":"symbol","url":"\/documentation\/dldirectsdk\/dlerrortype\/apikeyinvalid","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiKeyInvalid"}],"navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeApiKeyInvalid"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/SH":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/SY":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/Equatable-Implementations":{"url":"\/documentation\/dldirectsdk\/dlerrortype\/equatable-implementations","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/Equatable-Implementations","type":"topic","title":"Equatable Implementations"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/RawRepresentable-Implementations":{"type":"topic","abstract":[],"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/dldirectsdk\/dlerrortype\/rawrepresentable-implementations","kind":"article"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/clientNetworkingError":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientNetworkingError"}],"type":"topic","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlerrortype\/clientnetworkingerror","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/clientNetworkingError","title":"DLErrorType.clientNetworkingError","role":"symbol","abstract":[{"text":"Client networking error indicate that the device’s internet connection is poor or device is offline. Please ask user to check their connection.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeClientNetworkingError"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType":{"title":"DLErrorType","navigatorTitle":[{"kind":"identifier","text":"DLErrorType"}],"role":"symbol","abstract":[{"text":"Categorizes the possible errors that can be returned by our APIs.","type":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlerrortype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLErrorType"}]},"doc://com.dlocal.DLDirectSDK/SQ":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DLErrorType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"DLErrorType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DLErrorType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/apiKeyInvalid","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/clientNetworkingError","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/internalClientError","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/serverError"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLErrorType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1internalClientError\/title","op":"replace","value":"DLErrorTypeInternalClientError"},{"op":"replace","value":[{"text":"DLErrorTypeInternalClientError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1internalClientError\/fragments"},{"value":"DLErrorTypeServerError","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1serverError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1serverError\/fragments","value":[{"text":"DLErrorTypeServerError","kind":"identifier"}]},{"value":"DLErrorTypeApiKeyInvalid","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1apiKeyInvalid\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1apiKeyInvalid\/fragments","op":"replace","value":[{"text":"DLErrorTypeApiKeyInvalid","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1clientNetworkingError\/title","op":"replace","value":"DLErrorTypeClientNetworkingError"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1clientNetworkingError\/fragments","value":[{"text":"DLErrorTypeClientNetworkingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/title","value":"DLErrorType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/fragments","value":[{"text":"DLErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}