{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/id","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"DLDirectSDK"}],"title":"id","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLInstallments(py)id","navigatorTitle":[{"text":"id","kind":"identifier"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlinstallments\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlinstallments\/id"]}],"kind":"symbol","abstract":[{"type":"text","text":"The identifier of the installments plan."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments/id":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/id","kind":"symbol","abstract":[{"type":"text","text":"The identifier of the installments plan."}],"title":"id","url":"\/documentation\/dldirectsdk\/dlinstallments\/id","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"id"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","kind":"symbol","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments":{"navigatorTitle":[{"kind":"identifier","text":"DLInstallments"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlinstallments","abstract":[{"text":"The available installment options.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is used as output parameter in the "},{"isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","type":"reference"},{"type":"text","text":" method."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLInstallments","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments","type":"topic","title":"DLInstallments"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Get bin information and installments."}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getBinInformation"},{"kind":"text","text":"("},{"text":"binNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"currencyCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"amount"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","text":"DLBinInfo"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","kind":"typeIdentifier","text":"DLError"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","type":"topic","title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"id"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"id"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1id\/title","value":"id"},{"value":[{"text":"id","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1id\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/title","op":"replace","value":"DLInstallments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/fragments","value":[{"text":"DLInstallments","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}