{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeValidator","text":"DLSecurityCodeValidator"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"True if the security code is valid, false otherwise."}]}]},{"kind":"parameters","parameters":[{"name":"securityCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The security code to validate."}]}]},{"name":"validator","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The validator with the rules to use to validate."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/validate(securitycode:validator:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/validate(securitycode:validator:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:validator:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Validate the security code using the given validator."},{"type":"text","text":" "},{"type":"text","text":"Use this when you want to validate the security code using your own predefined rules."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLSecurityCodeValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeValidator"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"validate(securityCode:validator:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)validateWithSecurityCode:validator:","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithSecurityCode:validator:"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"role":"symbol","title":"DLCardExpert","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardExpert"}],"abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(securityCode:)":{"role":"symbol","title":"validate(securityCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate the security code."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithSecurityCode:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(securitycode:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(securityCode:validator:)":{"role":"symbol","title":"validate(securityCode:validator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLSecurityCodeValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeValidator"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate the security code using the given validator."},{"type":"text","text":" "},{"type":"text","text":"Use this when you want to validate the security code using your own predefined rules."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:validator:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithSecurityCode:validator:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(securitycode:validator:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeValidator":{"role":"symbol","title":"DLSecurityCodeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLSecurityCodeValidator"}],"abstract":[{"type":"text","text":"Defines the security code validation rules."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLSecurityCodeValidator"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodevalidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"validateWithSecurityCode:validator:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithSecurityCode:validator:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithSecurityCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"securityCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"validator:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeValidator","text":"DLSecurityCodeValidator"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"validator"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","value":"DLCardExpert"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"kind":"identifier","text":"DLCardExpert"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:)\/title","value":"validateWithSecurityCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithSecurityCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:validator:)\/title","value":"validateWithSecurityCode:validator:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:validator:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithSecurityCode:validator:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator\/title","value":"DLSecurityCodeValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator\/fragments","value":[{"kind":"identifier","text":"DLSecurityCodeValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}