{"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"gaps","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gaps"},{"kind":"text","text":": ["},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"]"}],"modules":[{"name":"DLDirectSDK"}],"title":"gaps","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrand(py)gaps","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/gaps"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"gaps","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"]","kind":"text"}]}]}],"abstract":[{"text":"Position of the blank spaces in the card number, used for formatting a card number to match what’s seen in the physical card.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/gaps"]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/gaps"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"navigatorTitle":[{"kind":"identifier","text":"DLCardBrand"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","abstract":[{"text":"The brand identifing the issuer of a card.","type":"text"}],"type":"topic","title":"DLCardBrand","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrand","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/gaps":{"type":"topic","kind":"symbol","abstract":[{"text":"Position of the blank spaces in the card number, used for formatting a card number to match what’s seen in the physical card.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gaps"},{"text":": [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"]"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand\/gaps","navigatorTitle":[{"text":"gaps","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/gaps","title":"gaps"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"gaps","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"gaps"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"gaps","kind":"identifier"}]}]}},{"value":"DLCardBrand","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DLCardBrand"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1gaps\/title","value":"gaps","op":"replace"},{"value":[{"kind":"identifier","text":"gaps"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1gaps\/fragments","op":"replace"}]}]}