{"metadata":{"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"validation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm","text":"DLCardBrandValidationAlgorithm"}],"navigatorTitle":[{"kind":"identifier","text":"validation"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrand(py)validation","modules":[{"name":"DLDirectSDK"}],"title":"validation"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm","text":"DLCardBrandValidationAlgorithm"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/validation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/validation"]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/validation","interfaceLanguage":"swift"},"abstract":[{"text":"Validation algorithm used to ensure the card number is valid.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/validation":{"navigatorTitle":[{"text":"validation","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand\/validation","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/validation","abstract":[{"text":"Validation algorithm used to ensure the card number is valid.","type":"text"}],"type":"topic","title":"validation","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"validation","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm","text":"DLCardBrandValidationAlgorithm","kind":"typeIdentifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm":{"navigatorTitle":[{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","type":"topic","abstract":[{"type":"text","text":"The algorithm used for validating the brand’s card numbers."}],"role":"symbol","title":"DLCardBrandValidationAlgorithm"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"navigatorTitle":[{"kind":"identifier","text":"DLCardBrand"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","abstract":[{"text":"The brand identifing the issuer of a card.","type":"text"}],"type":"topic","title":"DLCardBrand","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrand","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"validation","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"validation"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm","text":"DLCardBrandValidationAlgorithm"},{"kind":"text","text":" "},{"text":"validation","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1validation\/title","op":"replace","value":"validation"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1validation\/fragments","op":"replace","value":[{"text":"validation","kind":"identifier"}]},{"op":"replace","value":"DLCardBrandValidationAlgorithm","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/title"},{"value":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","value":"DLCardBrand","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLCardBrand"}]}]}]}