{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"DLImageSize","kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize"}]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"size","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"text":"DLImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize"}],"title":"size","externalID":"c:@M@DLDirectSDK@objc(cs)DLBrandImage(py)size","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DLDirectSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage"]]},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/size","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlbrandimage\/size"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlbrandimage\/size"]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize":{"url":"\/documentation\/dldirectsdk\/dlimagesize","title":"DLImageSize","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLImageSize"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLImageSize","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage":{"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","role":"symbol","title":"DLBrandImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLBrandImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLBrandImage"}],"abstract":[],"url":"\/documentation\/dldirectsdk\/dlbrandimage","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage/size":{"url":"\/documentation\/dldirectsdk\/dlbrandimage\/size","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"text":"DLImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/size","title":"size","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"size"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"size"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"size","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize","text":"DLImageSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/title","value":"DLImageSize","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DLImageSize"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/fragments"},{"value":"DLBrandImage","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/fragments","value":[{"text":"DLBrandImage","kind":"identifier"}]},{"value":"size","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1size\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1size\/fragments","op":"replace","value":[{"text":"size","kind":"identifier"}]}]}]}