{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"clientNetworkingError","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dldirectsdk\/dlerrortype\/clientnetworkingerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlerrortype\/clientnetworkingerror"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Client networking error indicate that the device’s internet connection is poor or device is offline. Please ask user to check their connection."}],"metadata":{"role":"symbol","externalID":"c:@M@DLDirectSDK@E@DLErrorType@DLErrorTypeClientNetworkingError","roleHeading":"Case","modules":[{"name":"DLDirectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientNetworkingError","kind":"identifier"}],"title":"DLErrorType.clientNetworkingError","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeClientNetworkingError"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/clientNetworkingError"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType"]]},"sections":[],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk","title":"DLDirectSDK","abstract":[],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType":{"abstract":[{"text":"Categorizes the possible errors that can be returned by our APIs.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk\/dlerrortype","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","title":"DLErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLErrorType"}],"role":"symbol","navigatorTitle":[{"text":"DLErrorType","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/clientNetworkingError":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientNetworkingError","kind":"identifier"}],"navigatorTitle":[{"text":"DLErrorTypeClientNetworkingError","kind":"identifier"}],"title":"DLErrorType.clientNetworkingError","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/clientNetworkingError","type":"topic","url":"\/documentation\/dldirectsdk\/dlerrortype\/clientnetworkingerror","abstract":[{"type":"text","text":"Client networking error indicate that the device’s internet connection is poor or device is offline. Please ask user to check their connection."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"DLErrorTypeClientNetworkingError","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLErrorTypeClientNetworkingError"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DLErrorTypeClientNetworkingError","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/title","value":"DLErrorType"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/fragments","op":"replace","value":[{"text":"DLErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1clientNetworkingError\/title","value":"DLErrorTypeClientNetworkingError"},{"op":"replace","value":[{"kind":"identifier","text":"DLErrorTypeClientNetworkingError"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1clientNetworkingError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}