{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"DLCardBrandIdentifierDinersClub","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"dinersClub","kind":"identifier"}],"role":"symbol","modules":[{"name":"DLDirectSDK"}],"title":"DLCardBrandIdentifier.dinersClub","externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierDinersClub"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dinersClub","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/dinersclub"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/dinersclub"]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/dinersClub","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/dinersClub":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dinersClub","kind":"identifier"}],"title":"DLCardBrandIdentifier.dinersClub","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierDinersClub"}],"abstract":[],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/dinersclub","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/dinersClub"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","title":"DLCardBrandIdentifier","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifier"}],"abstract":[{"text":"The available card brand identifiers.","type":"text"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrandIdentifier"}],"role":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","title":"DLDirectSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DLCardBrandIdentifierDinersClub"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DLCardBrandIdentifierDinersClub","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DLCardBrandIdentifierDinersClub","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1dinersClub\/title","value":"DLCardBrandIdentifierDinersClub","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1dinersClub\/fragments","op":"replace","value":[{"text":"DLCardBrandIdentifierDinersClub","kind":"identifier"}]},{"op":"replace","value":"DLCardBrandIdentifier","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments","value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}