{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"lengths","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The supported lengths to consider a security code valid."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlsecuritycodevalidator\/init(lengths:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlsecuritycodevalidator\/init(lengths:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator\/init(lengths:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a validator instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"title":"init(lengths:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeValidator(im)initWithLengths:","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLengths:"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(securityCode:)":{"role":"symbol","title":"validate(securityCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate the security code."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithSecurityCode:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(securitycode:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeValidator/init(lengths:)":{"role":"symbol","title":"init(lengths:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Creates a validator instance."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator\/init(lengths:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLengths:"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodevalidator\/init(lengths:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeValidator":{"role":"symbol","title":"DLSecurityCodeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLSecurityCodeValidator"}],"abstract":[{"type":"text","text":"Defines the security code validation rules."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLSecurityCodeValidator"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodevalidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLengths:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLengths:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLengths:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lengths"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:)\/title","value":"validateWithSecurityCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithSecurityCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator~1init(lengths:)\/title","value":"initWithLengths:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator~1init(lengths:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLengths:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator\/title","value":"DLSecurityCodeValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator\/fragments","value":[{"kind":"identifier","text":"DLSecurityCodeValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}