{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalAmount"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlinstallment\/codingkeys\/totalamount"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallment\/CodingKeys\/totalAmount","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalAmount"}],"title":"DLInstallment.CodingKeys.totalAmount","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:11DLDirectSDK13DLInstallmentC10CodingKeysO11totalAmountyA2EmF","modules":[{"name":"DLDirectSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallment","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallment\/CodingKeys"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallment/CodingKeys":{"role":"symbol","title":"DLInstallment.CodingKeys","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CodingKeys"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallment\/CodingKeys","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CodingKeys"}],"url":"\/documentation\/dldirectsdk\/dlinstallment\/codingkeys"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallment":{"role":"symbol","title":"DLInstallment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLInstallment"}],"abstract":[{"type":"text","text":"One of the available installments options."},{"type":"text","text":" "},{"type":"text","text":"This is used as output parameter in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLInstallment"}],"url":"\/documentation\/dldirectsdk\/dlinstallment"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallment/CodingKeys/totalAmount":{"role":"symbol","title":"DLInstallment.CodingKeys.totalAmount","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalAmount"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallment\/CodingKeys\/totalAmount","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk\/dlinstallment\/codingkeys\/totalamount"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"role":"symbol","title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBinInformation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"binNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currencyCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"amount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"DLBinInfo","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"DLError","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get bin information and installments."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallment\/title","value":"DLInstallment"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallment\/fragments","value":[{"kind":"identifier","text":"DLInstallment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}