{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:brand:)"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"text":"(","kind":"text"},{"text":"securityCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brand"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DLCardBrand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The security code to format.","type":"text"}],"type":"paragraph"}],"name":"securityCode"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand."}]}],"name":"brand"}]},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The formatted security code.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Format the security code using a specific brand."},{"text":" ","type":"text"},{"text":"Use this if you know the brand of the card for which the security code belongs. This will improve the validation rules.","type":"text"}],"metadata":{"roleHeading":"Instance Method","extendedModule":"DLDirectSDK","title":"format(securityCode:brand:)","symbolKind":"method","role":"symbol","modules":[{"name":"DLDirectSDK"}],"externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)formatWithSecurityCode:brand:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"text":"securityCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"brand","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"formatWithSecurityCode:brand:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(securitycode:brand:)"]},{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(securitycode:brand:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"abstract":[{"text":"Used  to perform various operations around cards, like format a card number or validate an expiration date.","type":"text"}],"title":"DLCardExpert","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","url":"\/documentation\/dldirectsdk\/dlcardexpert","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardExpert","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DLCardExpert","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"abstract":[{"text":"The brand identifing the issuer of a card.","type":"text"}],"title":"DLCardBrand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","url":"\/documentation\/dldirectsdk\/dlcardbrand","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrand"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(securityCode:brand:)":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:brand:)","navigatorTitle":[{"text":"formatWithSecurityCode:brand:","kind":"identifier"}],"abstract":[{"text":"Format the security code using a specific brand.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use this if you know the brand of the card for which the security code belongs. This will improve the validation rules."}],"kind":"symbol","title":"format(securityCode:brand:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"securityCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"brand","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(securitycode:brand:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"formatWithSecurityCode:brand:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"formatWithSecurityCode:brand:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"formatWithSecurityCode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"securityCode"},{"kind":"text","text":" "},{"text":"brand:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DLCardBrand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"brand"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DLCardExpert","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title"},{"value":[{"text":"DLCardExpert","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","op":"replace","value":"DLCardBrand"},{"op":"replace","value":[{"text":"DLCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:brand:)\/title","value":"formatWithSecurityCode:brand:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithSecurityCode:brand:"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:brand:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}