{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/resolvedcountrycode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/resolvedcountrycode"]}],"abstract":[{"text":"Country code resolved at runtime. When you pass an unsupported or unrecognized country code, we will default you to the list of “GLOBAL” cards which are globally accepted cards.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/resolvedCountryCode"},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DLDirectSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolvedCountryCode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"resolvedCountryCode"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardExpert(py)resolvedCountryCode","title":"resolvedCountryCode","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"resolvedCountryCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert","type":"topic","abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardExpert","kind":"identifier"}],"title":"DLCardExpert","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/resolvedCountryCode":{"title":"resolvedCountryCode","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolvedCountryCode"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"resolvedCountryCode"}],"abstract":[{"type":"text","text":"Country code resolved at runtime. When you pass an unsupported or unrecognized country code, we will default you to the list of “GLOBAL” cards which are globally accepted cards."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/resolvedCountryCode","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert\/resolvedcountrycode","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"resolvedCountryCode","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"resolvedCountryCode"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"resolvedCountryCode"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"DLCardExpert","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"kind":"identifier","text":"DLCardExpert"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1resolvedCountryCode\/title","value":"resolvedCountryCode"},{"value":[{"kind":"identifier","text":"resolvedCountryCode"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1resolvedCountryCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}