{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getBinInformation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currencyCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"amount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"DLBinInfo","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"symbolKind":"method","title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","modules":[{"name":"DLDirectSDK"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardTokenizer(im)getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"]]},"abstract":[{"text":"Get bin information and installments.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)"]},{"paths":["\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getBinInformation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"binNumber"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"currencyCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"amount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","text":"DLBinInfo","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onError"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"binNumber","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The first six digits of the card."}]}]},{"name":"currencyCode","content":[{"inlineContent":[{"type":"text","text":"The currency of the amount paramater."}],"type":"paragraph"}]},{"name":"amount","content":[{"inlineContent":[{"text":"The total amount to be charged (in order to provide installments options).","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLBinInfo"}],"abstract":[{"text":"The information obtained from the bin number of the card.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is used as output parameter in the "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","type":"reference","isActive":true},{"type":"text","text":" method."}],"title":"DLBinInfo","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","navigatorTitle":[{"kind":"identifier","text":"DLBinInfo"}],"url":"\/documentation\/dldirectsdk\/dlbininfo"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","url":"\/documentation\/dldirectsdk\/dlerror","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLError"}],"title":"DLError","kind":"symbol","role":"symbol","abstract":[{"text":"Encapsulates error that can happen when using the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","type":"reference","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DLError"}],"type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","abstract":[],"url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"url":"\/documentation\/dldirectsdk\/dlcardtokenizer","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardTokenizer","kind":"identifier"}],"title":"DLCardTokenizer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}],"navigatorTitle":[{"kind":"identifier","text":"DLCardTokenizer"}],"type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBinInformation"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currencyCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"amount"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"DLBinInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"DLError","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get bin information and installments."}],"title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:onSuccess:onError:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getBinInformation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"text":": (","kind":"text"},{"text":"DLBinInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": ("},{"text":"DLError","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Get bin information"}],"title":"getBinInformation(binNumber:onSuccess:onError:)","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","navigatorTitle":[{"text":"getBinInformationWithBinNumber:onSuccess:onError:","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:onsuccess:onerror:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"getBinInformationWithBinNumber:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"binNumber","kind":"internalParam"},{"kind":"text","text":" "},{"text":"currencyCode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"currencyCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"amount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"amount"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSuccess:"},{"kind":"text","text":"("},{"text":"void (^)(DLBinInfo *)","preciseIdentifier":"c:BFv(#*$@M@DLDirectSDK@objc(cs)DLBinInfo)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onSuccess","kind":"internalParam"},{"kind":"text","text":" "},{"text":"onError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(DLError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@DLDirectSDK@objc(cs)DLError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"onError"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/title","value":"DLBinInfo"},{"op":"replace","value":[{"kind":"identifier","text":"DLBinInfo"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/fragments"},{"op":"replace","value":"DLError","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title"},{"value":[{"text":"DLError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments","op":"replace"},{"value":"DLCardTokenizer","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DLCardTokenizer"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments"},{"value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:onSuccess:onError:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getBinInformationWithBinNumber:onSuccess:onError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}