{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlsecuritycodevalidator\/init(brand:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlsecuritycodevalidator\/init(brand:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator\/init(brand:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":")"}],"title":"init(brand:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeValidator(im)initWithBrand:","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBrand:"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeValidator":{"role":"symbol","title":"DLSecurityCodeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLSecurityCodeValidator"}],"abstract":[{"type":"text","text":"Defines the security code validation rules."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLSecurityCodeValidator"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodevalidator"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeValidator/init(brand:)":{"role":"symbol","title":"init(brand:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeValidator\/init(brand:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBrand:"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodevalidator\/init(brand:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(securityCode:)":{"role":"symbol","title":"validate(securityCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate the security code."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(securityCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithSecurityCode:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(securitycode:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"role":"symbol","title":"DLCardBrand","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrand"}],"abstract":[{"type":"text","text":"The brand identifing the issuer of a card."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrand"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBrand:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBrand:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBrand:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"brand"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator\/title","value":"DLSecurityCodeValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator\/fragments","value":[{"kind":"identifier","text":"DLSecurityCodeValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator~1init(brand:)\/title","value":"initWithBrand:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeValidator~1init(brand:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBrand:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:)\/title","value":"validateWithSecurityCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(securityCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithSecurityCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","value":"DLCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","value":[{"kind":"identifier","text":"DLCardBrand"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}