{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier","kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","text":"DLCardBrandIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Identifier of the brand, like .visa or .mastercard","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/identifier"]}],"sections":[],"metadata":{"title":"identifier","modules":[{"name":"DLDirectSDK"}],"role":"symbol","externalID":"s:11DLDirectSDK11DLCardBrandC10identifierAA0cD10IdentifierOSgvp","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"DLCardBrandIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"]]},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/identifier","interfaceLanguage":"swift"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","kind":"symbol","abstract":[{"type":"text","text":"The brand identifing the issuer of a card."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrand","kind":"identifier"}],"role":"symbol","title":"DLCardBrand","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrand","navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","url":"\/documentation\/dldirectsdk","role":"collection","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","role":"symbol","title":"DLCardBrandIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandIdentifier","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The available card brand identifiers."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/identifier":{"title":"identifier","url":"\/documentation\/dldirectsdk\/dlcardbrand\/identifier","abstract":[{"text":"Identifier of the brand, like .visa or .mastercard","type":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/identifier","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier","kind":"typeIdentifier","text":"DLCardBrandIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","op":"replace","value":"DLCardBrand"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","value":[{"text":"DLCardBrand","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title","op":"replace","value":"DLCardBrandIdentifier"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments","op":"replace","value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}]}]}]}