{"metadata":{"roleHeading":"Case","modules":[{"name":"DLDirectSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalClientError","kind":"identifier"}],"navigatorTitle":[{"text":"DLErrorTypeInternalClientError","kind":"identifier"}],"externalID":"c:@M@DLDirectSDK@E@DLErrorType@DLErrorTypeInternalClientError","title":"DLErrorType.internalClientError","symbolKind":"case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalClientError"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlerrortype\/internalclienterror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlerrortype\/internalclienterror"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/internalClientError"},"abstract":[{"text":"This usually indicates an error in the library code and there isn’t anything you could do about it. Please contact dlocal if this happens.","type":"text"}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/internalClientError":{"type":"topic","role":"symbol","abstract":[{"text":"This usually indicates an error in the library code and there isn’t anything you could do about it. Please contact dlocal if this happens.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalClientError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeInternalClientError"}],"title":"DLErrorType.internalClientError","url":"\/documentation\/dldirectsdk\/dlerrortype\/internalclienterror","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/internalClientError"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType":{"url":"\/documentation\/dldirectsdk\/dlerrortype","role":"symbol","navigatorTitle":[{"text":"DLErrorType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DLErrorType","kind":"identifier"}],"type":"topic","abstract":[{"text":"Categorizes the possible errors that can be returned by our APIs.","type":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","kind":"symbol","title":"DLErrorType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DLErrorTypeInternalClientError","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"DLErrorTypeInternalClientError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DLErrorTypeInternalClientError","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1internalClientError\/title","value":"DLErrorTypeInternalClientError"},{"op":"replace","value":[{"text":"DLErrorTypeInternalClientError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1internalClientError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/title","value":"DLErrorType"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/fragments","op":"replace","value":[{"text":"DLErrorType","kind":"identifier"}]}]}]}