{"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/patternsobjc"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/patternsobjc"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"]]},"abstract":[{"type":"text","text":"Same as "},{"type":"codeVoice","code":"patterns"},{"type":"text","text":" but exposed specifically to Objective-C (as enums with associated values cannot be exposed)."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"patternsObjc"},{"kind":"text","text":": ["},{"text":"DLCardBrandPatternObjc","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrandPatternObjc","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"patternsObjc","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrandPatternObjc","kind":"typeIdentifier","text":"DLCardBrandPatternObjc"},{"kind":"text","text":"]"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrand(py)patternsObjc","navigatorTitle":[{"text":"patternsObjc","kind":"identifier"}],"modules":[{"name":"DLDirectSDK"}],"title":"patternsObjc"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/patternsObjc"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandPatternObjc":{"abstract":[{"type":"text","text":"The card number patterns that match a card brand (built specifically for usage from Objective-C code)."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrandPatternObjc"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc","url":"\/documentation\/dldirectsdk\/dlcardbrandpatternobjc","type":"topic","title":"DLCardBrandPatternObjc","navigatorTitle":[{"text":"DLCardBrandPatternObjc","kind":"identifier"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","title":"DLDirectSDK","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/patternsObjc":{"kind":"symbol","abstract":[{"text":"Same as ","type":"text"},{"code":"patterns","type":"codeVoice"},{"text":" but exposed specifically to Objective-C (as enums with associated values cannot be exposed).","type":"text"}],"type":"topic","title":"patternsObjc","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"patternsObjc"},{"text":": [","kind":"text"},{"text":"DLCardBrandPatternObjc","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrandPatternObjc","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"patternsObjc","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/patternsObjc","url":"\/documentation\/dldirectsdk\/dlcardbrand\/patternsobjc"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrand","abstract":[{"text":"The brand identifing the issuer of a card.","type":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","role":"symbol","title":"DLCardBrand","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrand","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"patternsObjc"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"patternsObjc"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<DLCardBrandPatternObjc *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"patternsObjc","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandPatternObjc\/title","op":"replace","value":"DLCardBrandPatternObjc"},{"value":[{"kind":"identifier","text":"DLCardBrandPatternObjc"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandPatternObjc\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1patternsObjc\/title","value":"patternsObjc"},{"value":[{"text":"patternsObjc","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1patternsObjc\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","value":"DLCardBrand","op":"replace"},{"value":[{"text":"DLCardBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments"}]}]}