{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"]]},"abstract":[{"type":"text","text":"When contacting dlocal, please provide this identifier for us to research what happened."}],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerror\/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlerror\/identifier"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/identifier","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"DLDirectSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DLDirectSDK@objc(cs)DLError(py)identifier","title":"identifier"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/identifier":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/identifier","type":"topic","abstract":[{"type":"text","text":"When contacting dlocal, please provide this identifier for us to research what happened."}],"role":"symbol","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlerror\/identifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"identifier"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"navigatorTitle":[{"text":"DLCardTokenizer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","role":"symbol","abstract":[{"text":"Used to perform various tokenization related operations.","type":"text"}],"type":"topic","title":"DLCardTokenizer","url":"\/documentation\/dldirectsdk\/dlcardtokenizer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardTokenizer","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","url":"\/documentation\/dldirectsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","role":"collection"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","abstract":[{"text":"Encapsulates error that can happen when using the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","type":"topic","url":"\/documentation\/dldirectsdk\/dlerror","title":"DLError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLError","kind":"identifier"}],"navigatorTitle":[{"text":"DLError","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"identifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"identifier","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1identifier\/title"},{"value":[{"text":"identifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1identifier\/fragments","op":"replace"},{"value":"DLCardTokenizer","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","value":[{"kind":"identifier","text":"DLCardTokenizer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","value":"DLError"},{"value":[{"kind":"identifier","text":"DLError"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}