{"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"DLDirectSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"prettyPrintedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","navigatorTitle":[{"text":"prettyPrintedDescription","kind":"identifier"}],"roleHeading":"Instance Property","title":"prettyPrintedDescription","externalID":"c:@M@DLDirectSDK@objc(cs)DLError(py)prettyPrintedDescription"},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerror\/prettyprinteddescription"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlerror\/prettyprinteddescription"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"prettyPrintedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/prettyPrintedDescription","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"url":"\/documentation\/dldirectsdk\/dlerror","type":"topic","navigatorTitle":[{"text":"DLError","kind":"identifier"}],"abstract":[{"type":"text","text":"Encapsulates error that can happen when using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLError","kind":"identifier"}],"title":"DLError","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[],"url":"\/documentation\/dldirectsdk","role":"collection"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardTokenizer"}],"abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}],"title":"DLCardTokenizer","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtokenizer","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","kind":"symbol","navigatorTitle":[{"text":"DLCardTokenizer","kind":"identifier"}],"type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/prettyPrintedDescription":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prettyPrintedDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"title":"prettyPrintedDescription","role":"symbol","url":"\/documentation\/dldirectsdk\/dlerror\/prettyprinteddescription","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/prettyPrintedDescription","navigatorTitle":[{"text":"prettyPrintedDescription","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"prettyPrintedDescription","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"prettyPrintedDescription","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"prettyPrintedDescription","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DLError","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title"},{"value":[{"kind":"identifier","text":"DLError"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","value":"DLCardTokenizer","op":"replace"},{"value":[{"text":"DLCardTokenizer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1prettyPrintedDescription\/title","op":"replace","value":"prettyPrintedDescription"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1prettyPrintedDescription\/fragments","value":[{"text":"prettyPrintedDescription","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}