{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk"]},{"paths":["\/documentation\/dldirectsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"module","title":"DLDirectSDK","role":"collection","externalID":"DLDirectSDK","modules":[{"name":"DLDirectSDK"}],"roleHeading":"Framework"},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardSync","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan"],"title":"Classes"},{"title":"Enumerations","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPattern","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize"]}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2}]}],"hierarchy":{"paths":[[]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Get bin information and installments."}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getBinInformation"},{"kind":"text","text":"("},{"text":"binNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"currencyCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"amount"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","text":"DLBinInfo"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","kind":"typeIdentifier","text":"DLError"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","type":"topic","title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandSecurityCode":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode","abstract":[{"type":"text","text":"The information about the security code for a specific card brand."}],"navigatorTitle":[{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"title":"DLCardBrandSecurityCode","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandsecuritycode","role":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"kind":"symbol","navigatorTitle":[{"text":"DLError","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlerror","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLError","kind":"identifier"}],"title":"DLError","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","type":"topic","abstract":[{"text":"Encapsulates error that can happen when using the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandContainer":{"url":"\/documentation\/dldirectsdk\/dlcardbrandcontainer","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrandContainer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandContainer"}],"abstract":[],"kind":"symbol","title":"DLCardBrandContainer"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize":{"url":"\/documentation\/dldirectsdk\/dlimagesize","type":"topic","title":"DLImageSize","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DLImageSize"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLImageSize"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLDirectSDKVersionString":{"title":"DLDirectSDKVersionString","kind":"symbol","url":"\/documentation\/dldirectsdk\/dldirectsdkversionstring","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLDirectSDKVersionString","fragments":[{"text":"DLDirectSDKVersionString","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Project version string for DLDirectSDK."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","navigatorTitle":[{"text":"DLCardTokenizer","kind":"identifier"}],"type":"topic","title":"DLCardTokenizer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLCardTokenizer","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer","abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLDirectSDKVersionNumber":{"fragments":[{"text":"DLDirectSDKVersionNumber","kind":"identifier"}],"abstract":[{"text":"Project version number for DLDirectSDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLDirectSDKVersionNumber","url":"\/documentation\/dldirectsdk\/dldirectsdkversionnumber","kind":"symbol","type":"topic","title":"DLDirectSDKVersionNumber"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardToken":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtoken","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardToken"}],"title":"DLCardToken","abstract":[{"type":"text","text":"The card number tokenized."},{"type":"text","text":" "},{"type":"text","text":"This is the output of the "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","type":"reference","isActive":true},{"text":" method.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLCardToken","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLBinInfo"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLBinInfo"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","abstract":[{"type":"text","text":"The information obtained from the bin number of the card."},{"type":"text","text":" "},{"type":"text","text":"This is used as output parameter in the "},{"isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","type":"reference"},{"type":"text","text":" method."}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlbininfo","title":"DLBinInfo"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:onSuccess:onError:)":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","navigatorTitle":[{"text":"getBinInformationWithBinNumber:onSuccess:onError:","kind":"identifier"}],"type":"topic","title":"getBinInformation(binNumber:onSuccess:onError:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBinInformation"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","text":"DLBinInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"text":": (","kind":"text"},{"text":"DLError","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:onsuccess:onerror:)","abstract":[{"type":"text","text":"Get bin information"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm":{"abstract":[{"text":"The algorithm used for validating the brand’s card numbers.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","title":"DLCardBrandValidationAlgorithm","navigatorTitle":[{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity":{"role":"symbol","url":"\/documentation\/dldirectsdk\/dlimagedensity","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DLImageDensity","kind":"identifier"}],"title":"DLImageDensity","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","navigatorTitle":[{"text":"DLImageDensity","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardData":{"url":"\/documentation\/dldirectsdk\/dlcarddata","abstract":[{"type":"text","text":"Encapsulates data for the card you want to tokenize."},{"type":"text","text":" "},{"type":"text","text":"This is used as input parameter in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)"},{"type":"text","text":" method."}],"navigatorTitle":[{"kind":"identifier","text":"DLCardData"}],"role":"symbol","title":"DLCardData","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLCardData","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","abstract":[{"text":"The available card brand identifiers.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandIdentifier","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","type":"topic","title":"DLCardBrandIdentifier"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","navigatorTitle":[{"text":"DLErrorType","kind":"identifier"}],"title":"DLErrorType","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLErrorType","kind":"identifier"}],"abstract":[{"type":"text","text":"Categorizes the possible errors that can be returned by our APIs."}],"url":"\/documentation\/dldirectsdk\/dlerrortype"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandPatternObjc":{"abstract":[{"type":"text","text":"The card number patterns that match a card brand (built specifically for usage from Objective-C code)."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc","navigatorTitle":[{"text":"DLCardBrandPatternObjc","kind":"identifier"}],"type":"topic","title":"DLCardBrandPatternObjc","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandPatternObjc","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandpatternobjc"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/tokenizeCard(cardData:onSuccess:onError:)":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/tokenizecard(carddata:onsuccess:onerror:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tokenizeCardWithCardData:onSuccess:onError:"}],"title":"tokenizeCard(cardData:onSuccess:onError:)","abstract":[{"type":"text","text":"Tokenizes a card."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tokenizeCard","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardData"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData","text":"DLCardData","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardToken","text":"DLCardToken","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage":{"url":"\/documentation\/dldirectsdk\/dlbrandimage","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","role":"symbol","navigatorTitle":[{"text":"DLBrandImage","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLBrandImage"}],"kind":"symbol","title":"DLBrandImage"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan","title":"DLInstallmentsPlan","abstract":[{"text":"One of the available installments options.","type":"text"},{"text":" ","type":"text"},{"text":"This is used as output parameter in the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","type":"reference","isActive":true},{"type":"text","text":" method."}],"url":"\/documentation\/dldirectsdk\/dlinstallmentsplan","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLInstallmentsPlan","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLInstallmentsPlan"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardSync":{"abstract":[{"type":"text","text":"Entry point for everything related to our card sync feature"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardSync","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardSync","title":"DLCardSync","navigatorTitle":[{"kind":"identifier","text":"DLCardSync"}],"type":"topic","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardsync"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments":{"navigatorTitle":[{"kind":"identifier","text":"DLInstallments"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlinstallments","abstract":[{"text":"The available installment options.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is used as output parameter in the "},{"isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","type":"reference"},{"type":"text","text":" method."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLInstallments","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments","type":"topic","title":"DLInstallments"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrand","kind":"identifier"}],"title":"DLCardBrand","role":"symbol","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrand","type":"topic","navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}],"abstract":[{"type":"text","text":"The brand identifing the issuer of a card."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","kind":"symbol","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLCardExpert","kind":"identifier"}],"title":"DLCardExpert","role":"symbol","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}],"abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandPattern":{"title":"DLCardBrandPattern","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPattern","kind":"symbol","abstract":[{"type":"text","text":"The card number patterns that match a card brand."}],"role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandpattern","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLCardBrandPattern","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandPattern"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan"],"title":"Classes"},{"title":"Variables","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLDirectSDKVersionNumber","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLDirectSDKVersionString"]},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize"],"title":"Enumerations"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"},{"value":[{"kind":"text","text":"- "},{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode\/title","value":"DLCardBrandSecurityCode"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode\/fragments","value":[{"text":"DLCardBrandSecurityCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","value":"DLError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments","value":[{"kind":"identifier","text":"DLError"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer\/title","op":"replace","value":"DLCardBrandContainer"},{"value":[{"kind":"identifier","text":"DLCardBrandContainer"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/title","value":"DLImageSize"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/fragments","value":[{"text":"DLImageSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","value":"DLCardTokenizer","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","value":[{"kind":"identifier","text":"DLCardTokenizer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken\/title","value":"DLCardToken"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken\/fragments","value":[{"text":"DLCardToken","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/title","op":"replace","value":"DLBinInfo"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLBinInfo"}]},{"value":"getBinInformationWithBinNumber:onSuccess:onError:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getBinInformationWithBinNumber:onSuccess:onError:"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/title","op":"replace","value":"DLCardBrandValidationAlgorithm"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/fragments","op":"replace","value":[{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}]},{"value":"DLImageDensity","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/title"},{"value":[{"text":"DLImageDensity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData\/title","value":"DLCardData"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData\/fragments","value":[{"kind":"identifier","text":"DLCardData"}],"op":"replace"},{"op":"replace","value":"DLCardBrandIdentifier","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments","value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/title","value":"DLErrorType"},{"value":[{"kind":"identifier","text":"DLErrorType"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/fragments"},{"value":"DLCardBrandPatternObjc","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandPatternObjc\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandPatternObjc\/fragments","value":[{"kind":"identifier","text":"DLCardBrandPatternObjc"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/title","value":"tokenizeCardWithCardData:onSuccess:onError:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tokenizeCardWithCardData:onSuccess:onError:"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/title","value":"DLBrandImage","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/fragments","op":"replace","value":[{"text":"DLBrandImage","kind":"identifier"}]},{"value":"DLInstallmentsPlan","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DLInstallmentsPlan"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan\/fragments"},{"op":"replace","value":"DLInstallments","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/title"},{"value":[{"text":"DLInstallments","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","op":"replace","value":"DLCardBrand"},{"value":[{"kind":"identifier","text":"DLCardBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","value":"DLCardExpert"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"text":"DLCardExpert","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}