{"metadata":{"modules":[{"name":"DLDirectSDK"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrand(py)images","roleHeading":"Instance Property","title":"images","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"images","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBrandImage","text":"DLBrandImage"},{"kind":"text","text":"]?"}],"role":"symbol","navigatorTitle":[{"text":"images","kind":"identifier"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/images","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"URL of the brand card with logo."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"images","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBrandImage","text":"DLBrandImage","kind":"typeIdentifier"},{"kind":"text","text":"]? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"]]},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/images"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/images"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"navigatorTitle":[{"kind":"identifier","text":"DLCardBrand"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrand"}],"kind":"symbol","type":"topic","title":"DLCardBrand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","abstract":[{"type":"text","text":"The brand identifing the issuer of a card."}],"url":"\/documentation\/dldirectsdk\/dlcardbrand","role":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage":{"title":"DLBrandImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLBrandImage","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DLBrandImage","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlbrandimage","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/images":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/images","url":"\/documentation\/dldirectsdk\/dlcardbrand\/images","abstract":[{"type":"text","text":"URL of the brand card with logo."}],"type":"topic","title":"images","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"images","kind":"identifier"},{"kind":"text","text":": ["},{"text":"DLBrandImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBrandImage"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"images"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[],"url":"\/documentation\/dldirectsdk","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"images"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"images","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<DLBrandImage *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"images"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","value":"DLCardBrand","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","value":[{"text":"DLCardBrand","kind":"identifier"}]},{"op":"replace","value":"DLBrandImage","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/fragments","value":[{"kind":"identifier","text":"DLBrandImage"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1images\/title","op":"replace","value":"images"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1images\/fragments","value":[{"kind":"identifier","text":"images"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}