{"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/lengths","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/name"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"languages":["swift"]}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"metadata":{"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrandSecurityCode","role":"symbol","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"title":"DLCardBrandSecurityCode","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"roleHeading":"Class"},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandsecuritycode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandsecuritycode"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The information about the security code for a specific card brand."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","title":"Swift.Hashable"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandSecurityCode/name":{"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandsecuritycode\/name","navigatorTitle":[{"text":"name","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/name","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"name"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandSecurityCode/init(from:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/init(from:)","url":"\/documentation\/dldirectsdk\/dlcardbrandsecuritycode\/init(from:)","abstract":[],"role":"symbol","title":"init(from:)","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandSecurityCode/lengths":{"navigatorTitle":[{"text":"lengths","kind":"identifier"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandsecuritycode\/lengths","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"]","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/lengths","kind":"symbol","role":"symbol","title":"lengths"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dlocal.DLDirectSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","title":"Swift.Decodable"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandSecurityCode":{"abstract":[{"type":"text","text":"The information about the security code for a specific card brand."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandSecurityCode"}],"title":"DLCardBrandSecurityCode","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandsecuritycode"},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","title":"Swift.Equatable"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DLCardBrandSecurityCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardBrandSecurityCode"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/lengths","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/name"],"title":"Instance Properties"}],"path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrandSecurityCode"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode~1name\/title","value":"name","op":"replace"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode~1name\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode~1lengths\/title","value":"lengths"},{"value":[{"kind":"identifier","text":"lengths"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode~1lengths\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode\/title","value":"DLCardBrandSecurityCode","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DLCardBrandSecurityCode"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode\/fragments"}]}]}