{"variants":[{"paths":["\/documentation\/dldirectsdk\/dlinstallments"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlinstallments"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLInstallments"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"metadata":{"navigatorTitle":[{"text":"DLInstallments","kind":"identifier"}],"modules":[{"name":"DLDirectSDK"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLInstallments","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLInstallments","kind":"identifier"}],"symbolKind":"class","title":"DLInstallments","role":"symbol"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/amount","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/bin","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/country","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/currency","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/id","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/installments"]}],"abstract":[{"text":"The available installment options.","type":"text"},{"text":" ","type":"text"},{"text":"This is used as output parameter in the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","isActive":true},{"text":" method.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SE","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"type":"conformsTo"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments","interfaceLanguage":"swift"},"references":{"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getBinInformation","kind":"identifier"},{"kind":"text","text":"("},{"text":"binNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"currencyCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"amount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"DLBinInfo","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"text":": (","kind":"text"},{"text":"DLError","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","abstract":[{"type":"text","text":"Get bin information and installments."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","title":"Swift.Decodable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments/amount":{"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/amount","type":"topic","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlinstallments\/amount","abstract":[{"type":"text","text":"The total amount that would be paid in installments."}],"title":"amount","navigatorTitle":[{"text":"amount","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"amount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments/init(from:)":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/init(from:)","role":"symbol","url":"\/documentation\/dldirectsdk\/dlinstallments\/init(from:)","type":"topic","kind":"symbol","title":"init(from:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments/currency":{"kind":"symbol","title":"currency","abstract":[{"text":"The currency of the installments.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"currency","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dldirectsdk\/dlinstallments\/currency","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/currency","type":"topic","role":"symbol","navigatorTitle":[{"text":"currency","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments":{"abstract":[{"type":"text","text":"The available installment options."},{"type":"text","text":" "},{"text":"This is used as output parameter in the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","isActive":true,"type":"reference"},{"text":" method.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLInstallments"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLInstallments"}],"title":"DLInstallments","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlinstallments"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments/installments":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/installments","type":"topic","url":"\/documentation\/dldirectsdk\/dlinstallments\/installments","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"installments","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DLInstallmentsPlan","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLInstallmentsPlan"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"installments","kind":"identifier"}],"role":"symbol","title":"installments","abstract":[{"type":"text","text":"The installment options available."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments/country":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/country","role":"symbol","url":"\/documentation\/dldirectsdk\/dlinstallments\/country","navigatorTitle":[{"text":"country","kind":"identifier"}],"title":"country","kind":"symbol","type":"topic","abstract":[{"text":"The country associated with the installments.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"country"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments/id":{"kind":"symbol","title":"id","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/id","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[{"text":"The identifier of the installments plan.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlinstallments\/id","navigatorTitle":[{"text":"id","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject"},"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH"},"doc://com.dlocal.DLDirectSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SE"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments/bin":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/bin","role":"symbol","url":"\/documentation\/dldirectsdk\/dlinstallments\/bin","navigatorTitle":[{"text":"bin","kind":"identifier"}],"title":"bin","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The bin number of the card for which the installments plan was created."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bin","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DLInstallments","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DLInstallments","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"DLInstallments"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/amount","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/bin","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/country","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/currency","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/id","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/installments"],"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLInstallments"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1amount\/title","value":"amount","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1amount\/fragments","value":[{"kind":"identifier","text":"amount"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1currency\/title","value":"currency"},{"op":"replace","value":[{"kind":"identifier","text":"currency"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1currency\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/title","op":"replace","value":"DLInstallments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/fragments","value":[{"kind":"identifier","text":"DLInstallments"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1installments\/title","value":"installments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1installments\/fragments","op":"replace","value":[{"text":"installments","kind":"identifier"}]},{"value":"country","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1country\/title"},{"value":[{"kind":"identifier","text":"country"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1country\/fragments"},{"value":"id","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1id\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1id\/fragments","op":"replace","value":[{"text":"id","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1bin\/title","value":"bin"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1bin\/fragments","value":[{"text":"bin","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}