{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsuccessfulHttpStatusCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerrortype\/unsuccessfulhttpstatuscode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlerrortype\/unsuccessfulhttpstatuscode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/unsuccessfulHttpStatusCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The network request failed because the HTTP status code returned by the API was unsuccessful."},{"type":"text","text":" "},{"type":"text","text":"Inspect "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/apiErrorRaw"},{"type":"text","text":" for further information on what happened if you are debugging your app."},{"type":"text","text":" "},{"type":"text","text":"Suggested user message is to just show a generic error message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsuccessfulHttpStatusCode"}],"title":"DLErrorType.unsuccessfulHttpStatusCode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@DLDirectSDK@E@DLErrorType@DLErrorTypeUnsuccessfulHttpStatusCode","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeUnsuccessfulHttpStatusCode"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/apiErrorRaw":{"role":"symbol","title":"apiErrorRaw","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiErrorRaw"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The raw error data returned by the API."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" it would indicate that API did not return any error information."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/apiErrorRaw","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apiErrorRaw"}],"url":"\/documentation\/dldirectsdk\/dlerror\/apierrorraw"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/unsuccessfulHttpStatusCode":{"role":"symbol","title":"DLErrorType.unsuccessfulHttpStatusCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsuccessfulHttpStatusCode"}],"abstract":[{"type":"text","text":"The network request failed because the HTTP status code returned by the API was unsuccessful."},{"type":"text","text":" "},{"type":"text","text":"Inspect "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/apiErrorRaw"},{"type":"text","text":" for further information on what happened if you are debugging your app."},{"type":"text","text":" "},{"type":"text","text":"Suggested user message is to just show a generic error message."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/unsuccessfulHttpStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeUnsuccessfulHttpStatusCode"}],"url":"\/documentation\/dldirectsdk\/dlerrortype\/unsuccessfulhttpstatuscode"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType":{"role":"symbol","title":"DLErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLErrorType"}],"abstract":[{"type":"text","text":"Categorizes the possible errors that can be returned by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLErrorType"}],"url":"\/documentation\/dldirectsdk\/dlerrortype"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"role":"symbol","title":"DLCardTokenizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardTokenizer"}],"abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardTokenizer"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DLErrorTypeUnsuccessfulHttpStatusCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLErrorTypeUnsuccessfulHttpStatusCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DLErrorTypeUnsuccessfulHttpStatusCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1apiErrorRaw\/title","value":"apiErrorRaw"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1apiErrorRaw\/fragments","value":[{"kind":"identifier","text":"apiErrorRaw"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1unsuccessfulHttpStatusCode\/title","value":"DLErrorTypeUnsuccessfulHttpStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1unsuccessfulHttpStatusCode\/fragments","value":[{"kind":"identifier","text":"DLErrorTypeUnsuccessfulHttpStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/title","value":"DLErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/fragments","value":[{"kind":"identifier","text":"DLErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","value":"DLCardTokenizer"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","value":[{"kind":"identifier","text":"DLCardTokenizer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}