{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@M@DLDirectSDK@E@DLErrorType@DLErrorTypeApiKeyInvalid","title":"DLErrorType.apiKeyInvalid","navigatorTitle":[{"text":"DLErrorTypeApiKeyInvalid","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiKeyInvalid"}],"modules":[{"name":"DLDirectSDK"}],"symbolKind":"case"},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerrortype\/apikeyinvalid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlerrortype\/apikeyinvalid"]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/apiKeyInvalid","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"API-KEY"},{"text":" provided is invalid. Please check that you are not using the production key for testing or vice versa. Please contact dlocal if you are unable to get this fixed.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"apiKeyInvalid","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/apiKeyInvalid":{"title":"DLErrorType.apiKeyInvalid","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiKeyInvalid"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlerrortype\/apikeyinvalid","kind":"symbol","navigatorTitle":[{"text":"DLErrorTypeApiKeyInvalid","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"API-KEY"},{"type":"text","text":" provided is invalid. Please check that you are not using the production key for testing or vice versa. Please contact dlocal if you are unable to get this fixed."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/apiKeyInvalid"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLErrorType"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","abstract":[{"text":"Categorizes the possible errors that can be returned by our APIs.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DLErrorType"}],"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlerrortype","title":"DLErrorType","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DLErrorTypeApiKeyInvalid"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DLErrorTypeApiKeyInvalid","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DLErrorTypeApiKeyInvalid","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1apiKeyInvalid\/title","value":"DLErrorTypeApiKeyInvalid"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1apiKeyInvalid\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLErrorTypeApiKeyInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/title","value":"DLErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/fragments","value":[{"text":"DLErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}