{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/americanexpress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/americanexpress"]}],"metadata":{"modules":[{"name":"DLDirectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"americanExpress","kind":"identifier"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","title":"DLCardBrandIdentifier.americanExpress","externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierAmericanExpress","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierAmericanExpress"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"americanExpress"}]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/americanExpress","interfaceLanguage":"swift"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/americanExpress":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/americanExpress","title":"DLCardBrandIdentifier.americanExpress","type":"topic","role":"symbol","navigatorTitle":[{"text":"DLCardBrandIdentifierAmericanExpress","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/americanexpress","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"americanExpress","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","abstract":[{"text":"The available card brand identifiers.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrandIdentifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","kind":"symbol","title":"DLCardBrandIdentifier","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","abstract":[],"url":"\/documentation\/dldirectsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"DLCardBrandIdentifierAmericanExpress","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DLCardBrandIdentifierAmericanExpress","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DLCardBrandIdentifierAmericanExpress","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DLCardBrandIdentifierAmericanExpress","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1americanExpress\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1americanExpress\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierAmericanExpress"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title","op":"replace","value":"DLCardBrandIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments","value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}]}]}]}