{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImageDensity"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandimagedensity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandimagedensity"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH","doc:\/\/com.dlocal.DLDirectSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/x1","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/x2","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/x3"]},{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/Equatable-Implementations","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImageDensity"}],"title":"DLCardBrandImageDensity","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@DLDirectSDK@E@DLCardBrandImageDensity","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImageDensity"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"references":{"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageDensity/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandimagedensity\/equatable-implementations"},"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageDensity/x1":{"role":"symbol","title":"DLCardBrandImageDensity.x1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"x1"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/x1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImageDensityX1"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandimagedensity\/x1"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageDensity/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandimagedensity\/rawrepresentable-implementations"},"doc://com.dlocal.DLDirectSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SY"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageDensity/x2":{"role":"symbol","title":"DLCardBrandImageDensity.x2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"x2"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/x2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImageDensityX2"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandimagedensity\/x2"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageDensity":{"role":"symbol","title":"DLCardBrandImageDensity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImageDensity"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImageDensity"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandimagedensity"},"doc://com.dlocal.DLDirectSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageDensity/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandimagedensity\/init(rawvalue:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageDensity/x3":{"role":"symbol","title":"DLCardBrandImageDensity.x3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"x3"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/x3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImageDensityX3"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandimagedensity\/x3"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DLCardBrandImageDensity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImageDensity"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DLCardBrandImageDensity"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/x1","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/x2","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity\/x3"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImageDensity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity~1x1\/title","value":"DLCardBrandImageDensityX1"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity~1x1\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImageDensityX1"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity~1x2\/title","value":"DLCardBrandImageDensityX2"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity~1x2\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImageDensityX2"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity\/title","value":"DLCardBrandImageDensity"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImageDensity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity~1x3\/title","value":"DLCardBrandImageDensityX3"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity~1x3\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImageDensityX3"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}