{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm","text":"DLCardBrandValidationAlgorithm"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardnumbervalidator\/validation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardnumbervalidator\/validation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator\/validation","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm"}],"title":"validation","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardNumberValidator(py)validation","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"validation"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberValidator":{"role":"symbol","title":"DLCardNumberValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardNumberValidator"}],"abstract":[{"type":"text","text":"Defines the card number validation rules."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:validator:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardNumberValidator"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbervalidator"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberValidator/validation":{"role":"symbol","title":"validation","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator\/validation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validation"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbervalidator\/validation"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm":{"role":"symbol","title":"DLCardBrandValidationAlgorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"abstract":[{"type":"text","text":"The algorithm used for validating the brand’s card numbers."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(cardNumber:validator:)":{"role":"symbol","title":"validate(cardNumber:validator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardNumberValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardNumberValidator"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate a card number using the given validator."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:validator:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithCardNumber:validator:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(cardnumber:validator:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"validation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"validation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm","text":"DLCardBrandValidationAlgorithm"},{"kind":"text","text":" "},{"kind":"identifier","text":"validation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator\/title","value":"DLCardNumberValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator\/fragments","value":[{"kind":"identifier","text":"DLCardNumberValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator~1validation\/title","value":"validation"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator~1validation\/fragments","value":[{"kind":"identifier","text":"validation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/title","value":"DLCardBrandValidationAlgorithm"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/fragments","value":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(cardNumber:validator:)\/title","value":"validateWithCardNumber:validator:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(cardNumber:validator:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithCardNumber:validator:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}