{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tokenizeCard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cardData","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData","text":"DLCardData","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardToken","kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken","text":"DLCardToken"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError","kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The card data.","type":"text"}]}],"name":"cardData"}],"kind":"parameters"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenizeCard"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cardData"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DLCardData","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardToken","kind":"typeIdentifier","text":"DLCardToken"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"DLError","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"tokenizeCardWithCardData:onSuccess:onError:","kind":"identifier"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardTokenizer(im)tokenizeCardWithCardData:onSuccess:onError:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DLDirectSDK"}],"title":"tokenizeCard(cardData:onSuccess:onError:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"]]},"abstract":[{"text":"Tokenizes a card.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardtokenizer\/tokenizecard(carddata:onsuccess:onerror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardtokenizer\/tokenizecard(carddata:onsuccess:onerror:)"]}],"sections":[],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/tokenizeCard(cardData:onSuccess:onError:)":{"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/tokenizecard(carddata:onsuccess:onerror:)","abstract":[{"text":"Tokenizes a card.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenizeCard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cardData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DLCardData","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"DLCardToken","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardToken","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"DLError","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tokenizeCardWithCardData:onSuccess:onError:"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","role":"symbol","kind":"symbol","type":"topic","title":"tokenizeCard(cardData:onSuccess:onError:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardToken":{"url":"\/documentation\/dldirectsdk\/dlcardtoken","abstract":[{"type":"text","text":"The card number tokenized."},{"text":" ","type":"text"},{"type":"text","text":"This is the output of the "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","type":"reference","isActive":true},{"text":" method.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardToken"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardToken"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken","role":"symbol","kind":"symbol","title":"DLCardToken","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLError"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLError"}],"title":"DLError","role":"symbol","url":"\/documentation\/dldirectsdk\/dlerror","type":"topic","abstract":[{"type":"text","text":"Encapsulates error that can happen when using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"},{"type":"text","text":"."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","title":"DLDirectSDK","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLCardTokenizer","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardTokenizer"}],"title":"DLCardTokenizer","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtokenizer","type":"topic","abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardData":{"url":"\/documentation\/dldirectsdk\/dlcarddata","abstract":[{"type":"text","text":"Encapsulates data for the card you want to tokenize."},{"type":"text","text":" "},{"text":"This is used as input parameter in the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)"},{"text":" method.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardData"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData","role":"symbol","kind":"symbol","type":"topic","title":"DLCardData"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"tokenizeCardWithCardData:onSuccess:onError:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"tokenizeCardWithCardData:onSuccess:onError:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"tokenizeCardWithCardData:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData","text":"DLCardData"},{"text":" *) ","kind":"text"},{"text":"cardData","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"onSuccess:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@DLDirectSDK@objc(cs)DLCardToken)","text":"void (^)(DLCardToken *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"onSuccess"},{"text":" ","kind":"text"},{"text":"onError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(DLError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@DLDirectSDK@objc(cs)DLError)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"onError"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"tokenizeCardWithCardData:onSuccess:onError:","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tokenizeCardWithCardData:onSuccess:onError:"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken\/title","value":"DLCardToken"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken\/fragments","op":"replace","value":[{"text":"DLCardToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","value":"DLError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments","value":[{"text":"DLError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","value":"DLCardTokenizer"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","value":[{"kind":"identifier","text":"DLCardTokenizer"}]},{"value":"DLCardData","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData\/fragments","value":[{"text":"DLCardData","kind":"identifier"}]}]}]}