{"metadata":{"roleHeading":"Class","modules":[{"name":"DLDirectSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLBrandImage"}],"navigatorTitle":[{"kind":"identifier","text":"DLBrandImage"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLBrandImage","title":"DLBrandImage","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/background","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/density","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/size","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/url"]}],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlbrandimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlbrandimage"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLBrandImage","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage/background":{"url":"\/documentation\/dldirectsdk\/dlbrandimage\/background","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/background","title":"background","kind":"symbol","navigatorTitle":[{"text":"background","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage/url":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/url","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"url"}],"title":"url","url":"\/documentation\/dldirectsdk\/dlbrandimage\/url"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject"},"doc://com.dlocal.DLDirectSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage/size":{"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlbrandimage\/size","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/size","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"DLImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageSize"}],"title":"size","navigatorTitle":[{"text":"size","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage/density":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/density","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"density"},{"text":": ","kind":"text"},{"text":"DLImageDensity","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"density"}],"title":"density","url":"\/documentation\/dldirectsdk\/dlbrandimage\/density"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage/init(from:)":{"url":"\/documentation\/dldirectsdk\/dlbrandimage\/init(from:)","role":"symbol","title":"init(from:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/init(from:)","abstract":[]},"doc://com.dlocal.DLDirectSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se"},"doc://com.dlocal.DLDirectSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage":{"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlbrandimage","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLBrandImage"}],"title":"DLBrandImage","navigatorTitle":[{"text":"DLBrandImage","kind":"identifier"}],"role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DLBrandImage","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"DLBrandImage"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DLBrandImage","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/background","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/density","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/size","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/url"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DLBrandImage","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"value":"background","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1background\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1background\/fragments","value":[{"text":"background","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1url\/title","value":"url"},{"value":[{"kind":"identifier","text":"url"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1url\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1size\/title","op":"replace","value":"size"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1size\/fragments","op":"replace","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1density\/title","value":"density"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1density\/fragments","op":"replace","value":[{"text":"density","kind":"identifier"}]},{"value":"DLBrandImage","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DLBrandImage"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}