{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"abstract":[{"type":"text","text":"Get the brand from a given identifier."}],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/brand(withidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/brand(withidentifier:)"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/brand(withIdentifier:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","extendedModule":"DLDirectSDK","role":"symbol","modules":[{"name":"DLDirectSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"brand"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrandIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"text":"?","kind":"text"}],"title":"brand(withIdentifier:)","navigatorTitle":[{"kind":"identifier","text":"brandWithIdentifier:"}],"symbolKind":"method","externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)brandWithIdentifier:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"brand","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifier"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","text":"DLCardBrandIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the brand."}]}],"name":"identifier"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand or "},{"code":"nil","type":"codeVoice"},{"text":" if there is no brand with this identifier.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","url":"\/documentation\/dldirectsdk\/dlcardexpert","abstract":[{"text":"Used  to perform various operations around cards, like format a card number or validate an expiration date.","type":"text"}],"type":"topic","title":"DLCardExpert","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardExpert","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/brand(withIdentifier:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"brand"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DLCardBrandIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier"},{"text":") -> ","kind":"text"},{"text":"DLCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/brand(withIdentifier:)","abstract":[{"type":"text","text":"Get the brand from a given identifier."}],"title":"brand(withIdentifier:)","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert\/brand(withidentifier:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"brandWithIdentifier:"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandIdentifier","kind":"identifier"}],"abstract":[{"type":"text","text":"The available card brand identifiers."}],"title":"DLCardBrandIdentifier","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","kind":"symbol","navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[],"url":"\/documentation\/dldirectsdk","role":"collection"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"navigatorTitle":[{"kind":"identifier","text":"DLCardBrand"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrand"}],"kind":"symbol","type":"topic","title":"DLCardBrand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","abstract":[{"type":"text","text":"The brand identifing the issuer of a card."}],"url":"\/documentation\/dldirectsdk\/dlcardbrand","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"brandWithIdentifier:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"brandWithIdentifier:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"brandWithIdentifier:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier","text":"DLCardBrandIdentifier"},{"kind":"text","text":") "},{"text":"identifier","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"DLCardExpert","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title"},{"value":[{"kind":"identifier","text":"DLCardExpert"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1brand(withIdentifier:)\/title","value":"brandWithIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1brand(withIdentifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"brandWithIdentifier:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title","value":"DLCardBrandIdentifier","op":"replace"},{"value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments"},{"value":"DLCardBrand","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","value":[{"text":"DLCardBrand","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}