{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardNumberValidator","text":"DLCardNumberValidator"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"cardNumber","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card number to validate."}]}]},{"name":"validator","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The validator specifying the rules of validation."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"True if teh card number is valid, false otherwise."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this version of the validator if you want to validate the card according to your own defined rules."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator"},{"type":"text","text":" for more info."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/validate(cardnumber:validator:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/validate(cardnumber:validator:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:validator:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Validate a card number using the given validator."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardNumberValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardNumberValidator"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"validate(cardNumber:validator:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)validateWithCardNumber:validator:","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithCardNumber:validator:"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"role":"symbol","title":"DLCardExpert","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardExpert"}],"abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberValidator":{"role":"symbol","title":"DLCardNumberValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardNumberValidator"}],"abstract":[{"type":"text","text":"Defines the card number validation rules."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:validator:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardNumberValidator"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbervalidator"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(cardNumber:validator:)":{"role":"symbol","title":"validate(cardNumber:validator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardNumberValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardNumberValidator"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate a card number using the given validator."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:validator:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithCardNumber:validator:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(cardnumber:validator:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"validateWithCardNumber:validator:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithCardNumber:validator:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithCardNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cardNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"validator:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardNumberValidator","text":"DLCardNumberValidator"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"validator"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","value":"DLCardExpert"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"kind":"identifier","text":"DLCardExpert"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator\/title","value":"DLCardNumberValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator\/fragments","value":[{"kind":"identifier","text":"DLCardNumberValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(cardNumber:validator:)\/title","value":"validateWithCardNumber:validator:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(cardNumber:validator:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithCardNumber:validator:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}