{"variants":[{"paths":["\/documentation\/dldirectsdk\/dlimagesize\/small"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlimagesize\/small"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/small"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"small","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"DLImageSizeSmall","kind":"identifier"}],"role":"symbol","modules":[{"name":"DLDirectSDK"}],"symbolKind":"case","title":"DLImageSize.small","externalID":"c:@M@DLDirectSDK@E@DLImageSize@DLImageSizeSmall","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"small"}]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DLImageSize","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlimagesize","title":"DLImageSize","navigatorTitle":[{"kind":"identifier","text":"DLImageSize"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize","type":"topic","abstract":[],"role":"symbol","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize/small":{"type":"topic","url":"\/documentation\/dldirectsdk\/dlimagesize\/small","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"small"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/small","kind":"symbol","title":"DLImageSize.small","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLImageSizeSmall"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","url":"\/documentation\/dldirectsdk","role":"collection","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DLImageSizeSmall"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DLImageSizeSmall","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"DLImageSizeSmall","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/title","value":"DLImageSize"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLImageSize"}]},{"value":"DLImageSizeSmall","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize~1small\/title"},{"value":[{"text":"DLImageSizeSmall","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize~1small\/fragments"}]}]}