{"abstract":[{"type":"text","text":"The card number patterns that match a card brand (built specifically for usage from Objective-C code)."}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc\/prefix","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc\/rangeEnd","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc\/rangeStart"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc\/isEqual(_:)"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc"},"metadata":{"modules":[{"name":"DLDirectSDK"}],"roleHeading":"Class","title":"DLCardBrandPatternObjc","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLCardBrandPatternObjc","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandPatternObjc","kind":"identifier"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrandPatternObjc","symbolKind":"class","role":"symbol"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrandPatternObjc"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandpatternobjc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandpatternobjc"]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandPatternObjc/rangeStart":{"role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandpatternobjc\/rangestart","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc\/rangeStart","title":"rangeStart","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"rangeStart","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"?","kind":"text"}],"abstract":[],"type":"topic","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandPatternObjc/rangeEnd":{"role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandpatternobjc\/rangeend","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc\/rangeEnd","title":"rangeEnd","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"rangeEnd","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","title":"Swift.Equatable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandPatternObjc/prefix":{"kind":"symbol","abstract":[],"role":"symbol","title":"prefix","url":"\/documentation\/dldirectsdk\/dlcardbrandpatternobjc\/prefix","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefix","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc\/prefix"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandPatternObjc":{"title":"DLCardBrandPatternObjc","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLCardBrandPatternObjc","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandPatternObjc","kind":"identifier"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandpatternobjc","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc","kind":"symbol","abstract":[{"text":"The card number patterns that match a card brand (built specifically for usage from Objective-C code).","type":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandPatternObjc/isEqual(_:)":{"title":"isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandpatternobjc\/isequal(_:)","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc\/isEqual(_:)","kind":"symbol","abstract":[]},"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DLCardBrandPatternObjc","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DLCardBrandPatternObjc","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DLCardBrandPatternObjc","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandPatternObjc\/isEqual(_:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrandPatternObjc"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandPatternObjc\/title","op":"replace","value":"DLCardBrandPatternObjc"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandPatternObjc\/fragments","op":"replace","value":[{"text":"DLCardBrandPatternObjc","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandPatternObjc~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandPatternObjc~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]}]}]}