{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x1"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"x1","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlimagedensity\/x1"]},{"paths":["\/documentation\/dldirectsdk\/dlimagedensity\/x1"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DLDirectSDK"}],"externalID":"c:@M@DLDirectSDK@E@DLImageDensity@DLImageDensityX1","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"x1","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLImageDensityX1"}],"title":"DLImageDensity.x1","symbolKind":"case","role":"symbol","roleHeading":"Case"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","url":"\/documentation\/dldirectsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","role":"collection"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","type":"topic","url":"\/documentation\/dldirectsdk\/dlimagedensity","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DLImageDensity","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DLImageDensity","kind":"identifier"}],"title":"DLImageDensity","role":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity/x1":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x1","type":"topic","url":"\/documentation\/dldirectsdk\/dlimagedensity\/x1","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"x1","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLImageDensityX1"}],"title":"DLImageDensity.x1","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DLImageDensityX1","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"DLImageDensityX1","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DLImageDensityX1","kind":"identifier"}]}]}},{"value":"DLImageDensity","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/title"},{"op":"replace","value":[{"text":"DLImageDensity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x1\/title","value":"DLImageDensityX1"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x1\/fragments","value":[{"kind":"identifier","text":"DLImageDensityX1"}]}]}]}