{"metadata":{"modules":[{"name":"DLDirectSDK"}],"roleHeading":"Case","title":"DLImageDensity.x3","role":"symbol","symbolKind":"case","externalID":"c:@M@DLDirectSDK@E@DLImageDensity@DLImageDensityX3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"x3","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLImageDensityX3"}]},"sections":[],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x3","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlimagedensity\/x3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlimagedensity\/x3"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"x3","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity"]]},"kind":"symbol","references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","type":"topic","url":"\/documentation\/dldirectsdk\/dlimagedensity","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DLImageDensity","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DLImageDensity","kind":"identifier"}],"title":"DLImageDensity","role":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity/x3":{"kind":"symbol","abstract":[],"title":"DLImageDensity.x3","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x3","role":"symbol","type":"topic","navigatorTitle":[{"text":"DLImageDensityX3","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"x3"}],"url":"\/documentation\/dldirectsdk\/dlimagedensity\/x3"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","url":"\/documentation\/dldirectsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"DLImageDensityX3","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"DLImageDensityX3","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"DLImageDensityX3","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"DLImageDensity","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/title"},{"value":[{"kind":"identifier","text":"DLImageDensity"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/fragments"},{"value":"DLImageDensityX3","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x3\/title","op":"replace"},{"op":"replace","value":[{"text":"DLImageDensityX3","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x3\/fragments"}]}]}