{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unexpectedEmptyResponse"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerrortype\/unexpectedemptyresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlerrortype\/unexpectedemptyresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/unexpectedEmptyResponse","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The network request failed because the response from the API was unexpectively empty."},{"type":"text","text":" "},{"type":"text","text":"This should never happen but if it does it means that our API is temporarily unavailable."},{"type":"text","text":" "},{"type":"text","text":"Try the request again if you are debugging the app."},{"type":"text","text":" "},{"type":"text","text":"Suggested user message is to just show a generic error message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unexpectedEmptyResponse"}],"title":"DLErrorType.unexpectedEmptyResponse","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@DLDirectSDK@E@DLErrorType@DLErrorTypeUnexpectedEmptyResponse","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeUnexpectedEmptyResponse"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"role":"symbol","title":"DLCardTokenizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardTokenizer"}],"abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardTokenizer"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/unexpectedEmptyResponse":{"role":"symbol","title":"DLErrorType.unexpectedEmptyResponse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unexpectedEmptyResponse"}],"abstract":[{"type":"text","text":"The network request failed because the response from the API was unexpectively empty."},{"type":"text","text":" "},{"type":"text","text":"This should never happen but if it does it means that our API is temporarily unavailable."},{"type":"text","text":" "},{"type":"text","text":"Try the request again if you are debugging the app."},{"type":"text","text":" "},{"type":"text","text":"Suggested user message is to just show a generic error message."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/unexpectedEmptyResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeUnexpectedEmptyResponse"}],"url":"\/documentation\/dldirectsdk\/dlerrortype\/unexpectedemptyresponse"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType":{"role":"symbol","title":"DLErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLErrorType"}],"abstract":[{"type":"text","text":"Categorizes the possible errors that can be returned by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLErrorType"}],"url":"\/documentation\/dldirectsdk\/dlerrortype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DLErrorTypeUnexpectedEmptyResponse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLErrorTypeUnexpectedEmptyResponse"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DLErrorTypeUnexpectedEmptyResponse"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","value":"DLCardTokenizer"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","value":[{"kind":"identifier","text":"DLCardTokenizer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1unexpectedEmptyResponse\/title","value":"DLErrorTypeUnexpectedEmptyResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1unexpectedEmptyResponse\/fragments","value":[{"kind":"identifier","text":"DLErrorTypeUnexpectedEmptyResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/title","value":"DLErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/fragments","value":[{"kind":"identifier","text":"DLErrorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}