{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectBrand"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The detected card brands from this number. If the card number is incomplete, we might return more than one brand."}]}]},{"kind":"parameters","parameters":[{"name":"cardNumber","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card number (either complete or incomplete)."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/detectbrand(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/detectbrand(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(from:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Detect the brand from the given card number."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"detectBrandFrom:"}],"role":"symbol","title":"detectBrand(from:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectBrand"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":"]"}],"symbolKind":"method","externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)detectBrandFrom:","extendedModule":"DLDirectSDK","modules":[{"name":"DLDirectSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"role":"symbol","title":"DLCardExpert","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardExpert"}],"abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/detectBrand(from:)":{"role":"symbol","title":"detectBrand(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectBrand"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Detect the brand from the given card number."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectBrandFrom:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/detectbrand(from:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"role":"symbol","title":"DLCardBrand","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrand"}],"abstract":[{"type":"text","text":"The brand identifing the issuer of a card."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrand"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"detectBrandFrom:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectBrandFrom:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<DLCardBrand *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"detectBrandFrom:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"cardNumber"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","value":"DLCardExpert"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"kind":"identifier","text":"DLCardExpert"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1detectBrand(from:)\/title","value":"detectBrandFrom:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1detectBrand(from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectBrandFrom:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","value":"DLCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","value":[{"kind":"identifier","text":"DLCardBrand"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}