{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"formatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeFormatter","text":"DLSecurityCodeFormatter"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The formatted security code."}]}]},{"kind":"parameters","parameters":[{"name":"securityCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The security code to format."}]}]},{"name":"formatter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The formatter with your rules."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(securitycode:formatter:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(securitycode:formatter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:formatter:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Format the security code using your own rules."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"formatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLSecurityCodeFormatter","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeFormatter"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"format(securityCode:formatter:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)formatWithSecurityCode:formatter:","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"formatWithSecurityCode:formatter:"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(securityCode:formatter:)":{"role":"symbol","title":"format(securityCode:formatter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"securityCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"formatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLSecurityCodeFormatter","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeFormatter"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Format the security code using your own rules."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:formatter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formatWithSecurityCode:formatter:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(securitycode:formatter:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLSecurityCodeFormatter":{"role":"symbol","title":"DLSecurityCodeFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLSecurityCodeFormatter"}],"abstract":[{"type":"text","text":"Used to format the security code."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(securityCode:formatter:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLSecurityCodeFormatter"}],"url":"\/documentation\/dldirectsdk\/dlsecuritycodeformatter"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"role":"symbol","title":"DLCardExpert","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardExpert"}],"abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"formatWithSecurityCode:formatter:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithSecurityCode:formatter:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"formatWithSecurityCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"securityCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"formatter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLSecurityCodeFormatter","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLSecurityCodeFormatter","text":"DLSecurityCodeFormatter"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"formatter"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:formatter:)\/title","value":"formatWithSecurityCode:formatter:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(securityCode:formatter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithSecurityCode:formatter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter\/title","value":"DLSecurityCodeFormatter"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLSecurityCodeFormatter\/fragments","value":[{"kind":"identifier","text":"DLSecurityCodeFormatter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","value":"DLCardExpert"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"kind":"identifier","text":"DLCardExpert"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}