{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"x2"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlimagedensity\/x2"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlimagedensity\/x2"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"x2","kind":"identifier"}],"navigatorTitle":[{"text":"DLImageDensityX2","kind":"identifier"}],"modules":[{"name":"DLDirectSDK"}],"role":"symbol","title":"DLImageDensity.x2","externalID":"c:@M@DLDirectSDK@E@DLImageDensity@DLImageDensityX2"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity"]]},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x2","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","title":"DLDirectSDK","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","url":"\/documentation\/dldirectsdk\/dlimagedensity","title":"DLImageDensity","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLImageDensity"}],"type":"topic","navigatorTitle":[{"text":"DLImageDensity","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity/x2":{"abstract":[],"url":"\/documentation\/dldirectsdk\/dlimagedensity\/x2","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"x2","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x2","title":"DLImageDensity.x2","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLImageDensityX2"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DLImageDensityX2"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DLImageDensityX2"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DLImageDensityX2"}],"platforms":["iOS"]}]}},{"op":"replace","value":"DLImageDensity","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/title"},{"value":[{"kind":"identifier","text":"DLImageDensity"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/fragments","op":"replace"},{"value":"DLImageDensityX2","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x2\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x2\/fragments","value":[{"kind":"identifier","text":"DLImageDensityX2"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}