{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/currency","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlinstallments\/currency"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlinstallments\/currency"]}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLInstallments(py)currency","title":"currency","modules":[{"name":"DLDirectSDK"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"currency"}]},"abstract":[{"type":"text","text":"The currency of the installments."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments"]]},"kind":"symbol","references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments/currency":{"navigatorTitle":[{"kind":"identifier","text":"currency"}],"url":"\/documentation\/dldirectsdk\/dlinstallments\/currency","title":"currency","type":"topic","abstract":[{"text":"The currency of the installments.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments\/currency"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getBinInformation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"binNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"currencyCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"amount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"DLBinInfo","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","type":"topic","abstract":[{"type":"text","text":"Get bin information and installments."}],"title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)","navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLInstallments"}],"abstract":[{"type":"text","text":"The available installment options."},{"type":"text","text":" "},{"type":"text","text":"This is used as output parameter in the "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","isActive":true,"type":"reference"},{"type":"text","text":" method."}],"navigatorTitle":[{"kind":"identifier","text":"DLInstallments"}],"type":"topic","role":"symbol","kind":"symbol","title":"DLInstallments","url":"\/documentation\/dldirectsdk\/dlinstallments","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"currency","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"currency"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"currency","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1currency\/title","op":"replace","value":"currency"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments~1currency\/fragments","value":[{"kind":"identifier","text":"currency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"}]},{"value":"DLInstallments","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/fragments","value":[{"text":"DLInstallments","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}