{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"country"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"abstract":[{"text":"The country where card was issued, e.g. “US” for “United States”","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/country"},"metadata":{"modules":[{"name":"DLDirectSDK"}],"roleHeading":"Instance Property","title":"country","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"country"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"country","kind":"identifier"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLBinInfo(py)country","symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo"]]},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlbininfo\/country"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlbininfo\/country"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/country":{"navigatorTitle":[{"kind":"identifier","text":"country"}],"abstract":[{"text":"The country where card was issued, e.g. “US” for “United States”","type":"text"}],"kind":"symbol","title":"country","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/country","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"country"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dldirectsdk\/dlbininfo\/country","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:onSuccess:onError:)":{"navigatorTitle":[{"text":"getBinInformationWithBinNumber:onSuccess:onError:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Get bin information","type":"text"}],"kind":"symbol","role":"symbol","title":"getBinInformation(binNumber:onSuccess:onError:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:onsuccess:onerror:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getBinInformation"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"DLBinInfo","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo":{"navigatorTitle":[{"kind":"identifier","text":"DLBinInfo"}],"type":"topic","abstract":[{"type":"text","text":"The information obtained from the bin number of the card."},{"text":" ","type":"text"},{"type":"text","text":"This is used as output parameter in the "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","isActive":true,"type":"reference"},{"type":"text","text":" method."}],"kind":"symbol","role":"symbol","title":"DLBinInfo","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","url":"\/documentation\/dldirectsdk\/dlbininfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLBinInfo","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"country","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"country","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"country","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1country\/title","op":"replace","value":"country"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1country\/fragments","op":"replace","value":[{"text":"country","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:onSuccess:onError:"},{"value":[{"kind":"text","text":"- "},{"text":"getBinInformationWithBinNumber:onSuccess:onError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/fragments","op":"replace"},{"value":"DLBinInfo","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/fragments","value":[{"text":"DLBinInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}