{"metadata":{"modules":[{"name":"DLDirectSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expirationMonth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"expirationMonth","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardData(py)expirationMonth","navigatorTitle":[{"kind":"identifier","text":"expirationMonth"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Expiration month, e.g. 5.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"expirationMonth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcarddata\/expirationmonth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcarddata\/expirationmonth"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData\/expirationMonth","interfaceLanguage":"swift"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardData/expirationMonth":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData\/expirationMonth","abstract":[{"text":"Expiration month, e.g. 5.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"expirationMonth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/dldirectsdk\/dlcarddata\/expirationmonth","navigatorTitle":[{"text":"expirationMonth","kind":"identifier"}],"kind":"symbol","title":"expirationMonth"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardData":{"type":"topic","title":"DLCardData","url":"\/documentation\/dldirectsdk\/dlcarddata","abstract":[{"type":"text","text":"Encapsulates data for the card you want to tokenize."},{"text":" ","type":"text"},{"type":"text","text":"This is used as input parameter in the "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","type":"reference","isActive":true},{"text":" method.","type":"text"}],"navigatorTitle":[{"text":"DLCardData","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLCardData","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData","role":"symbol","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","abstract":[],"url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/tokenizeCard(cardData:onSuccess:onError:)":{"type":"topic","title":"tokenizeCard(cardData:onSuccess:onError:)","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/tokenizecard(carddata:onsuccess:onerror:)","abstract":[{"type":"text","text":"Tokenizes a card."}],"navigatorTitle":[{"text":"tokenizeCardWithCardData:onSuccess:onError:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenizeCard","kind":"identifier"},{"kind":"text","text":"("},{"text":"cardData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DLCardData","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardToken","text":"DLCardToken","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"expirationMonth","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"expirationMonth","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"expirationMonth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData~1expirationMonth\/title","value":"expirationMonth","op":"replace"},{"op":"replace","value":[{"text":"expirationMonth","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData~1expirationMonth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData\/title","value":"DLCardData"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData\/fragments","value":[{"text":"DLCardData","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/title","value":"tokenizeCardWithCardData:onSuccess:onError:"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tokenizeCardWithCardData:onSuccess:onError:","kind":"identifier"}],"op":"replace"}]}]}