{"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerrortype\/servererror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlerrortype\/servererror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/serverError"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Our server returned an unsuccessful response. This could be an issue with your input or our API is unavailable. Please contact dlocal if this happens continously."}],"metadata":{"title":"DLErrorType.serverError","modules":[{"name":"DLDirectSDK"}],"externalID":"c:@M@DLDirectSDK@E@DLErrorType@DLErrorTypeServerError","symbolKind":"case","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"}],"navigatorTitle":[{"text":"DLErrorTypeServerError","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType"]]},"sections":[],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","navigatorTitle":[{"text":"DLErrorType","kind":"identifier"}],"title":"DLErrorType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLErrorType","kind":"identifier"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlerrortype","kind":"symbol","abstract":[{"text":"Categorizes the possible errors that can be returned by our APIs.","type":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType/serverError":{"role":"symbol","title":"DLErrorType.serverError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLErrorTypeServerError"}],"abstract":[{"type":"text","text":"Our server returned an unsuccessful response. This could be an issue with your input or our API is unavailable. Please contact dlocal if this happens continously."}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlerrortype\/servererror","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType\/serverError"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","url":"\/documentation\/dldirectsdk","role":"collection","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DLErrorTypeServerError","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DLErrorTypeServerError","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DLErrorTypeServerError","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/title","op":"replace","value":"DLErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/fragments","value":[{"kind":"identifier","text":"DLErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1serverError\/title","value":"DLErrorTypeServerError"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType~1serverError\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLErrorTypeServerError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}