{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"text":"encoder","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP","text":"Encoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","modules":[{"name":"DLDirectSDK"}],"role":"symbol","title":"encode(to:)","roleHeading":"Instance Method","externalID":"s:11DLDirectSDK7DLErrorC6encode2toys7Encoder_p_tKF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"Encodable.encode(to:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/encode(to:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerror\/encode(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/encode(to:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlerror\/encode(to:)","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Encoder","kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/encode(to:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardTokenizer","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardTokenizer"}],"title":"DLCardTokenizer","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtokenizer"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"abstract":[{"type":"text","text":"Encapsulates error that can happen when using the "},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLError","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLError"}],"title":"DLError","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlerror"}},"variantOverrides":[{"patch":[{"value":"DLCardTokenizer","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","value":[{"kind":"identifier","text":"DLCardTokenizer"}]},{"value":"DLError","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments","value":[{"text":"DLError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}