{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DLErrorType","preciseIdentifier":"c:@M@DLDirectSDK@E@DLErrorType","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","title":"type","externalID":"c:@M@DLDirectSDK@objc(cs)DLError(py)type","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DLDirectSDK@E@DLErrorType","kind":"typeIdentifier","text":"DLErrorType"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"modules":[{"name":"DLDirectSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerror\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlerror\/type"]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/type","interfaceLanguage":"swift"},"abstract":[{"text":"Allows you categorize the error that caused the operation to fail.","type":"text"},{"type":"text","text":" "},{"text":"Use this for example to understand whether it was a service unavailability error or a client device networking issue.","type":"text"}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLErrorType":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType","navigatorTitle":[{"text":"DLErrorType","kind":"identifier"}],"title":"DLErrorType","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLErrorType","kind":"identifier"}],"abstract":[{"type":"text","text":"Categorizes the possible errors that can be returned by our APIs."}],"url":"\/documentation\/dldirectsdk\/dlerrortype"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","navigatorTitle":[{"text":"DLCardTokenizer","kind":"identifier"}],"type":"topic","title":"DLCardTokenizer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLCardTokenizer","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer","abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","kind":"symbol","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"kind":"symbol","navigatorTitle":[{"text":"DLError","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlerror","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLError","kind":"identifier"}],"title":"DLError","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","type":"topic","abstract":[{"text":"Encapsulates error that can happen when using the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/type":{"kind":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlerror\/type","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DLErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLErrorType"}],"title":"type","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/type","type":"topic","abstract":[{"text":"Allows you categorize the error that caused the operation to fail.","type":"text"},{"type":"text","text":" "},{"text":"Use this for example to understand whether it was a service unavailability error or a client device networking issue.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"type"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DLErrorType","preciseIdentifier":"c:@M@DLDirectSDK@E@DLErrorType","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLErrorType"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/title","op":"replace","value":"DLErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLErrorType\/fragments","value":[{"kind":"identifier","text":"DLErrorType"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","op":"replace","value":"DLCardTokenizer"},{"op":"replace","value":[{"kind":"identifier","text":"DLCardTokenizer"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments"},{"value":"DLError","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","op":"replace"},{"op":"replace","value":[{"text":"DLError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments"},{"value":"type","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1type\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"type"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1type\/fragments"}]}]}