{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/description","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/error","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/httpStatusCode","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/identifier","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/prettyPrintedDescription","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/type"]},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/encode(to:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/Error-Implementations"],"generated":true,"title":"Default Implementations"}],"abstract":[{"text":"Encapsulates error that can happen when using the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","isActive":true,"type":"reference"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLError","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLError"}],"modules":[{"name":"DLDirectSDK"}],"title":"DLError","externalID":"c:@M@DLDirectSDK@objc(cs)DLError"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlerror"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SE","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/s5ErrorP","doc:\/\/com.dlocal.DLDirectSDK\/SH","doc:\/\/com.dlocal.DLDirectSDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLError"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/identifier":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/identifier","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"title":"identifier","role":"symbol","url":"\/documentation\/dldirectsdk\/dlerror\/identifier","type":"topic","abstract":[{"type":"text","text":"When contacting dlocal, please provide this identifier for us to research what happened."}]},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/encode(to:)":{"type":"topic","url":"\/documentation\/dldirectsdk\/dlerror\/encode(to:)","kind":"symbol","title":"encode(to:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/encode(to:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","title":"DLDirectSDK","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/Error-Implementations":{"abstract":[],"url":"\/documentation\/dldirectsdk\/dlerror\/error-implementations","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/Error-Implementations","title":"Error Implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/prettyPrintedDescription":{"title":"prettyPrintedDescription","type":"topic","abstract":[],"navigatorTitle":[{"text":"prettyPrintedDescription","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlerror\/prettyprinteddescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prettyPrintedDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/prettyPrintedDescription","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.dlocal.DLDirectSDK/s5ErrorP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s5ErrorP","type":"unresolvable","title":"Swift.Error"},"doc://com.dlocal.DLDirectSDK/SE":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.dlocal.DLDirectSDK/SH":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/type":{"title":"type","type":"topic","abstract":[{"text":"Allows you categorize the error that caused the operation to fail.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Use this for example to understand whether it was a service unavailability error or a client device networking issue."}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlerror\/type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"DLErrorType","preciseIdentifier":"c:@M@DLDirectSDK@E@DLErrorType","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/type","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLCardTokenizer","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardTokenizer"}],"title":"DLCardTokenizer","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtokenizer","type":"topic","abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/httpStatusCode":{"url":"\/documentation\/dldirectsdk\/dlerror\/httpstatuscode","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/httpStatusCode","type":"topic","abstract":[{"type":"text","text":"The HTTP status code returned by the API."}],"role":"symbol","kind":"symbol","title":"httpStatusCode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"httpStatusCode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/description":{"title":"description","type":"topic","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlerror\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/description","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/error":{"title":"error","type":"topic","abstract":[{"type":"text","text":"Contains the underlying error as returned by the networking layer, useful for debugging."}],"navigatorTitle":[{"text":"error","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlerror\/error","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/error","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/init(from:)":{"title":"init(from:)","type":"topic","abstract":[],"url":"\/documentation\/dldirectsdk\/dlerror\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/init(from:)","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.dlocal.DLDirectSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s8SendableP","title":"Swift.Sendable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLError"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLError"}],"title":"DLError","role":"symbol","url":"\/documentation\/dldirectsdk\/dlerror","type":"topic","abstract":[{"type":"text","text":"Encapsulates error that can happen when using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"},{"type":"text","text":"."}]},"doc://com.dlocal.DLDirectSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","title":"Swift.Decodable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"DLError","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DLError","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DLError"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/description","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/error","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/identifier","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/prettyPrintedDescription","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/type"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DLError","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1identifier\/title","op":"replace","value":"identifier"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1identifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"identifier"}]},{"value":"prettyPrintedDescription","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1prettyPrintedDescription\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1prettyPrintedDescription\/fragments","value":[{"kind":"identifier","text":"prettyPrintedDescription"}],"op":"replace"},{"value":"type","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1type\/title","op":"replace"},{"op":"replace","value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1type\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","value":"DLCardTokenizer"},{"value":[{"kind":"identifier","text":"DLCardTokenizer"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1error\/title","value":"error","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1error\/fragments","value":[{"text":"error","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","value":"DLError"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments","value":[{"text":"DLError","kind":"identifier"}],"op":"replace"}]}]}