{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lengths"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode"]]},"metadata":{"symbolKind":"property","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"text":"lengths","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lengths","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrandSecurityCode(py)lengths","roleHeading":"Instance Property","role":"symbol","title":"lengths"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandsecuritycode\/lengths"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandsecuritycode\/lengths"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/lengths"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandSecurityCode/lengths":{"navigatorTitle":[{"text":"lengths","kind":"identifier"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandsecuritycode\/lengths","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"]","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode\/lengths","kind":"symbol","role":"symbol","title":"lengths"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandSecurityCode":{"abstract":[{"type":"text","text":"The information about the security code for a specific card brand."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandSecurityCode"}],"title":"DLCardBrandSecurityCode","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandsecuritycode"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","url":"\/documentation\/dldirectsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"lengths"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"lengths","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"lengths","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode~1lengths\/title","op":"replace","value":"lengths"},{"value":[{"kind":"identifier","text":"lengths"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode~1lengths\/fragments"},{"value":"DLCardBrandSecurityCode","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode\/fragments","op":"replace","value":[{"text":"DLCardBrandSecurityCode","kind":"identifier"}]}]}]}