{"sections":[],"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm@DLCardBrandValidationAlgorithmNaranja","modules":[{"name":"DLDirectSDK"}],"title":"DLCardBrandValidationAlgorithm.naranja","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithmNaranja"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"naranja"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"naranja","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/naranja"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/naranja"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/naranja","interfaceLanguage":"swift"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm/naranja":{"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithmNaranja"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"naranja"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/naranja","title":"DLCardBrandValidationAlgorithm.naranja","abstract":[],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/naranja","role":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","title":"DLCardBrandValidationAlgorithm","abstract":[{"type":"text","text":"The algorithm used for validating the brand’s card numbers."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","url":"\/documentation\/dldirectsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DLCardBrandValidationAlgorithmNaranja"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DLCardBrandValidationAlgorithmNaranja","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DLCardBrandValidationAlgorithmNaranja","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1naranja\/title","value":"DLCardBrandValidationAlgorithmNaranja","op":"replace"},{"op":"replace","value":[{"text":"DLCardBrandValidationAlgorithmNaranja","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1naranja\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/title","value":"DLCardBrandValidationAlgorithm"},{"value":[{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/fragments","op":"replace"}]}]}