{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm"]]},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/luhn","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm@DLCardBrandValidationAlgorithmLuhn","title":"DLCardBrandValidationAlgorithm.luhn","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithmLuhn"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"luhn","kind":"identifier"}],"modules":[{"name":"DLDirectSDK"}],"symbolKind":"case"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"luhn","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/luhn"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/luhn"]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm":{"navigatorTitle":[{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","type":"topic","abstract":[{"type":"text","text":"The algorithm used for validating the brand’s card numbers."}],"role":"symbol","title":"DLCardBrandValidationAlgorithm"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm/luhn":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/luhn","navigatorTitle":[{"text":"DLCardBrandValidationAlgorithmLuhn","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/luhn","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"luhn"}],"abstract":[],"title":"DLCardBrandValidationAlgorithm.luhn"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DLCardBrandValidationAlgorithmLuhn"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DLCardBrandValidationAlgorithmLuhn","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"DLCardBrandValidationAlgorithmLuhn","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/title","op":"replace","value":"DLCardBrandValidationAlgorithm"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/fragments","value":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1luhn\/title","value":"DLCardBrandValidationAlgorithmLuhn"},{"op":"replace","value":[{"text":"DLCardBrandValidationAlgorithmLuhn","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1luhn\/fragments"}]}]}