{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/other","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"DLDirectSDK"}],"role":"symbol","externalID":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm@DLCardBrandValidationAlgorithmOther","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"DLCardBrandValidationAlgorithmOther","kind":"identifier"}],"title":"DLCardBrandValidationAlgorithm.other"},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/other"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/other"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm/other":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm\/other","navigatorTitle":[{"text":"DLCardBrandValidationAlgorithmOther","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm\/other","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"abstract":[],"title":"DLCardBrandValidationAlgorithm.other"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm":{"navigatorTitle":[{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","type":"topic","abstract":[{"type":"text","text":"The algorithm used for validating the brand’s card numbers."}],"role":"symbol","title":"DLCardBrandValidationAlgorithm"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DLCardBrandValidationAlgorithmOther","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DLCardBrandValidationAlgorithmOther","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithmOther"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DLCardBrandValidationAlgorithmOther","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1other\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm~1other\/fragments","value":[{"text":"DLCardBrandValidationAlgorithmOther","kind":"identifier"}],"op":"replace"},{"value":"DLCardBrandValidationAlgorithm","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/fragments","value":[{"text":"DLCardBrandValidationAlgorithm","kind":"identifier"}]}]}]}