{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandcontainer\/ios"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandcontainer\/ios"]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"ios","roleHeading":"Instance Property","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrandContainer(py)ios","modules":[{"name":"DLDirectSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ios","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DLBrandImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBrandImage"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"ios"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ios","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","text":"DLBrandImage","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBrandImage","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer\/ios"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandContainer/ios":{"url":"\/documentation\/dldirectsdk\/dlcardbrandcontainer\/ios","title":"ios","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer\/ios","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ios","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBrandImage","text":"DLBrandImage"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"ios","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandContainer":{"url":"\/documentation\/dldirectsdk\/dlcardbrandcontainer","title":"DLCardBrandContainer","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandContainer"}],"navigatorTitle":[{"text":"DLCardBrandContainer","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage":{"title":"DLBrandImage","navigatorTitle":[{"text":"DLBrandImage","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","url":"\/documentation\/dldirectsdk\/dlbrandimage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLBrandImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ios","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ios"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<DLBrandImage *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ios"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ios","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer~1ios\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer~1ios\/fragments","value":[{"text":"ios","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer\/title","value":"DLCardBrandContainer"},{"op":"replace","value":[{"text":"DLCardBrandContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/title","value":"DLBrandImage","op":"replace"},{"op":"replace","value":[{"text":"DLBrandImage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/fragments"}]}]}