{"sections":[],"abstract":[{"text":"Detect the brand from the given bin number.","type":"text"}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(binNumber:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"detectBrandWithBinNumber:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectBrand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier","text":"DLCardBrand"},{"text":"]","kind":"text"}],"externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)detectBrandWithBinNumber:","title":"detectBrand(binNumber:)","modules":[{"name":"DLDirectSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detectBrand","kind":"identifier"},{"kind":"text","text":"("},{"text":"binNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> [","kind":"text"},{"kind":"typeIdentifier","text":"DLCardBrand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":"]"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The bin number (first six digits of the card).","type":"text"}],"type":"paragraph"}],"name":"binNumber"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The detected card brands from this number. If the card number is incomplete, we might return more than one brand."}]}]}],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/detectbrand(binnumber:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/detectbrand(binnumber:)"]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/detectBrand(binNumber:)":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/detectBrand(binNumber:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"detectBrand","kind":"identifier"},{"kind":"text","text":"("},{"text":"binNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Detect the brand from the given bin number."}],"role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert\/detectbrand(binnumber:)","title":"detectBrand(binNumber:)","navigatorTitle":[{"text":"detectBrandWithBinNumber:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"kind":"symbol","type":"topic","abstract":[{"text":"The brand identifing the issuer of a card.","type":"text"}],"title":"DLCardBrand","url":"\/documentation\/dldirectsdk\/dlcardbrand","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrand","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"title":"DLCardExpert","url":"\/documentation\/dldirectsdk\/dlcardexpert","abstract":[{"text":"Used  to perform various operations around cards, like format a card number or validate an expiration date.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardExpert"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","url":"\/documentation\/dldirectsdk","title":"DLDirectSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"detectBrandWithBinNumber:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectBrandWithBinNumber:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSArray<DLCardBrand *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"detectBrandWithBinNumber:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"binNumber","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"detectBrandWithBinNumber:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1detectBrand(binNumber:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1detectBrand(binNumber:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"detectBrandWithBinNumber:","kind":"identifier"}]},{"value":"DLCardBrand","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","value":[{"text":"DLCardBrand","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","op":"replace","value":"DLCardExpert"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"kind":"identifier","text":"DLCardExpert"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}