{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"]]},"metadata":{"modules":[{"name":"DLDirectSDK"}],"title":"Error Implementations","role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlerror\/error-implementations"]}],"kind":"article","identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/Error-Implementations","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/localizedDescription"],"title":"Instance Properties"}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"abstract":[{"type":"text","text":"Encapsulates error that can happen when using the "},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","isActive":true},{"text":".","type":"text"}],"title":"DLError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLError","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","navigatorTitle":[{"kind":"identifier","text":"DLError"}],"url":"\/documentation\/dldirectsdk\/dlerror","role":"symbol","kind":"symbol","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}],"title":"DLCardTokenizer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLCardTokenizer","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","navigatorTitle":[{"text":"DLCardTokenizer","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer","role":"symbol","kind":"symbol","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/localizedDescription":{"role":"symbol","title":"localizedDescription","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/localizedDescription","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlerror\/localizeddescription"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","op":"replace","value":"DLError"},{"op":"replace","value":[{"text":"DLError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments"},{"value":"DLCardTokenizer","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","value":[{"kind":"identifier","text":"DLCardTokenizer"}]}]}]}