{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"density"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandImageDensity","text":"DLCardBrandImageDensity"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandimage\/density"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandimage\/density"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImage\/density","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"density"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrandImageDensity","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandImageDensity"}],"title":"density","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrandImage(py)density","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"density"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImage"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageDensity":{"role":"symbol","title":"DLCardBrandImageDensity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImageDensity"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImageDensity"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandimagedensity"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImage/density":{"role":"symbol","title":"density","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"density"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrandImageDensity","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandImageDensity"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImage\/density","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"density"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandimage\/density"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImage":{"role":"symbol","title":"DLCardBrandImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImage"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImage"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"density"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"density"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageDensity","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandImageDensity","text":"DLCardBrandImageDensity"},{"kind":"text","text":" "},{"kind":"identifier","text":"density"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity\/title","value":"DLCardBrandImageDensity"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageDensity\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImageDensity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImage~1density\/title","value":"density"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImage~1density\/fragments","value":[{"kind":"identifier","text":"density"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImage\/title","value":"DLCardBrandImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImage\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}