{"metadata":{"roleHeading":"Instance Method","title":"format(holderName:)","symbolKind":"method","modules":[{"name":"DLDirectSDK"}],"role":"symbol","navigatorTitle":[{"text":"formatWithHolderName:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"holderName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)formatWithHolderName:"},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(holderName:)","interfaceLanguage":"swift"},"abstract":[{"text":"Formats the holder name to match the formatting shown in the card.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(holdername:)"]},{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(holdername:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"text":"(","kind":"text"},{"text":"holderName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"holderName","content":[{"type":"paragraph","inlineContent":[{"text":"The holder name","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The formatted holder name"}]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","title":"DLDirectSDK","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(holderName:)":{"navigatorTitle":[{"kind":"identifier","text":"formatWithHolderName:"}],"title":"format(holderName:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(holderName:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"text":"holderName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(holdername:)","abstract":[{"text":"Formats the holder name to match the formatting shown in the card.","type":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"url":"\/documentation\/dldirectsdk\/dlcardexpert","kind":"symbol","type":"topic","title":"DLCardExpert","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardExpert","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"navigatorTitle":[{"text":"DLCardExpert","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"formatWithHolderName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"formatWithHolderName:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"formatWithHolderName:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"holderName","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(holderName:)\/title","op":"replace","value":"formatWithHolderName:"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(holderName:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"formatWithHolderName:","kind":"identifier"}],"op":"replace"},{"value":"DLCardExpert","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"text":"DLCardExpert","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}