{"metadata":{"title":"format(cardNumber:brand:)","modules":[{"name":"DLDirectSDK"}],"externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)formatWithCardNumber:brand:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cardNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"formatWithCardNumber:brand:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Fromat a card number to match what’s shown on the card."},{"text":" ","type":"text"},{"type":"text","text":"The difference between this and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)"},{"text":" is that we will not attempt to detect the brand from the number, instead we will use what you pass as parameter.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cardNumber"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"cardNumber","content":[{"inlineContent":[{"type":"text","text":"The card number to format."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand of the card."}]}],"name":"brand"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The formatted card number."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumber:brand:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumber:brand:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"abstract":[{"text":"Used  to perform various operations around cards, like format a card number or validate an expiration date.","type":"text"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardexpert","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardExpert","kind":"identifier"}],"title":"DLCardExpert","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumber:brand:)":{"abstract":[{"text":"Fromat a card number to match what’s shown on the card.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The difference between this and "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","type":"reference","isActive":true},{"text":" is that we will not attempt to detect the brand from the number, instead we will use what you pass as parameter.","type":"text"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumber:brand:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cardNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"format(cardNumber:brand:)","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","navigatorTitle":[{"text":"formatWithCardNumber:brand:","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","kind":"symbol","abstract":[{"type":"text","text":"The brand identifing the issuer of a card."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrand","kind":"identifier"}],"role":"symbol","title":"DLCardBrand","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrand","navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","url":"\/documentation\/dldirectsdk","role":"collection","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"formatWithCardNumber:brand:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"formatWithCardNumber:brand:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"formatWithCardNumber:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cardNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"brand:"},{"kind":"text","text":"("},{"text":"DLCardBrand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","value":"DLCardExpert","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"text":"DLCardExpert","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:brand:)\/title","value":"formatWithCardNumber:brand:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"formatWithCardNumber:brand:"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:brand:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","value":"DLCardBrand"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","value":[{"text":"DLCardBrand","kind":"identifier"}],"op":"replace"}]}]}