{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"testMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"modules":[{"name":"DLDirectSDK"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithCountryCode:testMode:options:","kind":"identifier"}],"title":"init(countryCode:testMode:options:)","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardExpert(im)initWithCountryCode:testMode:options:","symbolKind":"init","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/init(countryCode:testMode:options:)"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Initializes the card expert."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/init(countrycode:testmode:options:)"]},{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/init(countrycode:testmode:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"testMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"] = [:])","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The two letter country code for which you want to load card data from. Each country have its own set of supported cards.","type":"text"}],"type":"paragraph"}],"name":"countryCode"},{"content":[{"inlineContent":[{"text":"Whether you are operating on a sanbox environment or production.","type":"text"}],"type":"paragraph"}],"name":"testMode"},{"name":"options","content":[{"inlineContent":[{"type":"text","text":"Allows to override some behavior of the card expert, you can leave this empty unless instructed otherwise."}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/init(countryCode:testMode:options:)":{"url":"\/documentation\/dldirectsdk\/dlcardexpert\/init(countrycode:testmode:options:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/init(countryCode:testMode:options:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"testMode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"Initializes the card expert."}],"navigatorTitle":[{"text":"initWithCountryCode:testMode:options:","kind":"identifier"}],"title":"init(countryCode:testMode:options:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","url":"\/documentation\/dldirectsdk","role":"collection","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"abstract":[{"text":"Used  to perform various operations around cards, like format a card number or validate an expiration date.","type":"text"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardexpert","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardExpert","kind":"identifier"}],"title":"DLCardExpert","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithCountryCode:testMode:options:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCountryCode:testMode:options:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithCountryCode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"countryCode","kind":"internalParam"},{"kind":"text","text":" "},{"text":"testMode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"testMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1init(countryCode:testMode:options:)\/title","value":"initWithCountryCode:testMode:options:"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1init(countryCode:testMode:options:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCountryCode:testMode:options:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","value":"DLCardExpert"},{"value":[{"text":"DLCardExpert","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}