{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImageSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandimagesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandimagesize"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH","doc:\/\/com.dlocal.DLDirectSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize\/small"]},{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize\/Equatable-Implementations","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImageSize"}],"title":"DLCardBrandImageSize","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@DLDirectSDK@E@DLCardBrandImageSize","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImageSize"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageSize/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandimagesize\/rawrepresentable-implementations"},"doc://com.dlocal.DLDirectSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SY"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageSize/small":{"role":"symbol","title":"DLCardBrandImageSize.small","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"small"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize\/small","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImageSizeSmall"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandimagesize\/small"},"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageSize":{"role":"symbol","title":"DLCardBrandImageSize","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImageSize"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandImageSize"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandimagesize"},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ"},"doc://com.dlocal.DLDirectSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageSize/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandimagesize\/equatable-implementations"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandImageSize/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandimagesize\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DLCardBrandImageSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImageSize"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DLCardBrandImageSize"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandImageSize\/small"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageSize~1small\/title","value":"DLCardBrandImageSizeSmall"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageSize~1small\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImageSizeSmall"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageSize\/title","value":"DLCardBrandImageSize"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandImageSize\/fragments","value":[{"kind":"identifier","text":"DLCardBrandImageSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}