{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiErrorRaw"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerror\/apierrorraw"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlerror\/apierrorraw"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/apiErrorRaw","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The raw error data returned by the API."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" it would indicate that API did not return any error information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiErrorRaw"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"apiErrorRaw","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DLDirectSDK@objc(cs)DLError(py)apiErrorRaw","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"apiErrorRaw"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/apiErrorRaw":{"role":"symbol","title":"apiErrorRaw","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiErrorRaw"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The raw error data returned by the API."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" it would indicate that API did not return any error information."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/apiErrorRaw","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apiErrorRaw"}],"url":"\/documentation\/dldirectsdk\/dlerror\/apierrorraw"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"role":"symbol","title":"DLError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLError"}],"abstract":[{"type":"text","text":"Encapsulates error that can happen when using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLError"}],"url":"\/documentation\/dldirectsdk\/dlerror"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"role":"symbol","title":"DLCardTokenizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardTokenizer"}],"abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardTokenizer"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"apiErrorRaw"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"apiErrorRaw"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"apiErrorRaw"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1apiErrorRaw\/title","value":"apiErrorRaw"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError~1apiErrorRaw\/fragments","value":[{"kind":"identifier","text":"apiErrorRaw"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","value":"DLError"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments","value":[{"kind":"identifier","text":"DLError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","value":"DLCardTokenizer"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","value":[{"kind":"identifier","text":"DLCardTokenizer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}