{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"gaps"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"lengths","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card number lengths supported, formatted value will be limited to the maximum length."}]}]},{"name":"gaps","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The indexes where to insert spaces."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardnumberformatter\/init(lengths:gaps:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardnumberformatter\/init(lengths:gaps:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberFormatter\/init(lengths:gaps:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a formatter instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"gaps"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"title":"init(lengths:gaps:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardNumberFormatter(im)initWithLengths:gaps:","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLengths:gaps:"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberFormatter"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumber:formatter:)":{"role":"symbol","title":"format(cardNumber:formatter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"formatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardNumberFormatter","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardNumberFormatter"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Format the card number using your own rules."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:formatter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formatWithCardNumber:formatter:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumber:formatter:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberFormatter/init(lengths:gaps:)":{"role":"symbol","title":"init(lengths:gaps:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"gaps"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Creates a formatter instance."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberFormatter\/init(lengths:gaps:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLengths:gaps:"}],"url":"\/documentation\/dldirectsdk\/dlcardnumberformatter\/init(lengths:gaps:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberFormatter":{"role":"symbol","title":"DLCardNumberFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardNumberFormatter"}],"abstract":[{"type":"text","text":"Used to format a card number."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:formatter:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardNumberFormatter"}],"url":"\/documentation\/dldirectsdk\/dlcardnumberformatter"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLengths:gaps:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLengths:gaps:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLengths:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"lengths"},{"kind":"text","text":" "},{"kind":"identifier","text":"gaps:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"gaps"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:formatter:)\/title","value":"formatWithCardNumber:formatter:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:formatter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithCardNumber:formatter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberFormatter~1init(lengths:gaps:)\/title","value":"initWithLengths:gaps:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberFormatter~1init(lengths:gaps:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLengths:gaps:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberFormatter\/title","value":"DLCardNumberFormatter"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberFormatter\/fragments","value":[{"kind":"identifier","text":"DLCardNumberFormatter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}