{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken"]]},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken\/init(from:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Decodable.init(from:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"symbolKind":"init","title":"init(from:)","externalID":"s:11DLDirectSDK11DLCardTokenC4fromACs7Decoder_p_tKcfc","modules":[{"name":"DLDirectSDK"}],"roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardtoken\/init(from:)"]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardToken/init(from:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken\/init(from:)","abstract":[],"kind":"symbol","title":"init(from:)","url":"\/documentation\/dldirectsdk\/dlcardtoken\/init(from:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardToken":{"title":"DLCardToken","url":"\/documentation\/dldirectsdk\/dlcardtoken","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardToken"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardToken","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardToken"}],"abstract":[{"type":"text","text":"The card number tokenized."},{"text":" ","type":"text"},{"text":"This is the output of the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","isActive":true,"type":"reference"},{"type":"text","text":" method."}],"type":"topic","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","url":"\/documentation\/dldirectsdk","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/tokenizeCard(cardData:onSuccess:onError:)":{"title":"tokenizeCard(cardData:onSuccess:onError:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tokenizeCard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cardData","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData","text":"DLCardData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardToken","text":"DLCardToken"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": ("},{"text":"DLError","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/tokenizecard(carddata:onsuccess:onerror:)","kind":"symbol","abstract":[{"type":"text","text":"Tokenizes a card."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"tokenizeCardWithCardData:onSuccess:onError:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken\/title","value":"DLCardToken","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardToken\/fragments","value":[{"text":"DLCardToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/title","op":"replace","value":"tokenizeCardWithCardData:onSuccess:onError:"},{"value":[{"text":"- ","kind":"text"},{"text":"tokenizeCardWithCardData:onSuccess:onError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/fragments","op":"replace"}]}]}