{"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cencosud","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cencosud"]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cencosud"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cencosud","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DLDirectSDK"}],"title":"DLCardBrandIdentifier.cencosud","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cencosud","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierCencosud","role":"symbol","navigatorTitle":[{"text":"DLCardBrandIdentifierCencosud","kind":"identifier"}]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/cencosud":{"title":"DLCardBrandIdentifier.cencosud","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierCencosud"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cencosud","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cencosud"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cencosud"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"title":"DLCardBrandIdentifier","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","abstract":[{"type":"text","text":"The available card brand identifiers."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandIdentifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","title":"DLDirectSDK","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DLCardBrandIdentifierCencosud","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierCencosud"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DLCardBrandIdentifierCencosud"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cencosud\/title","value":"DLCardBrandIdentifierCencosud"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cencosud\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierCencosud"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title","value":"DLCardBrandIdentifier","op":"replace"},{"value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}