{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"sections":[],"metadata":{"symbolKind":"case","modules":[{"name":"DLDirectSDK"}],"roleHeading":"Case","externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierTarjetaShopping","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tarjetaShopping"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierTarjetaShopping"}],"title":"DLCardBrandIdentifier.tarjetaShopping"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tarjetaShopping"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/tarjetashopping"]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/tarjetashopping"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/tarjetaShopping","interfaceLanguage":"swift"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"title":"DLCardBrandIdentifier","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","abstract":[{"type":"text","text":"The available card brand identifiers."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandIdentifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","title":"DLDirectSDK","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/tarjetaShopping":{"title":"DLCardBrandIdentifier.tarjetaShopping","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/tarjetashopping","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/tarjetaShopping","navigatorTitle":[{"text":"DLCardBrandIdentifierTarjetaShopping","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"tarjetaShopping","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"DLCardBrandIdentifierTarjetaShopping","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"DLCardBrandIdentifierTarjetaShopping","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DLCardBrandIdentifierTarjetaShopping"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DLCardBrandIdentifier","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments","op":"replace","value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1tarjetaShopping\/title","value":"DLCardBrandIdentifierTarjetaShopping"},{"value":[{"kind":"identifier","text":"DLCardBrandIdentifierTarjetaShopping"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1tarjetaShopping\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}