{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardNumberMaskFormatter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardnumbermaskformatter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardnumbermaskformatter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Used to format a card number using the last digits."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:formatter:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardNumberMaskFormatter"}],"title":"DLCardNumberMaskFormatter","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardNumberMaskFormatter","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardNumberMaskFormatter"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/init(brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/init(length:gaps:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/gaps","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/length"]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberMaskFormatter/init(brand:)":{"role":"symbol","title":"init(brand:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/init(brand:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBrand:"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbermaskformatter\/init(brand:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumber:formatter:)":{"role":"symbol","title":"format(cardNumber:formatter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"formatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardNumberFormatter","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardNumberFormatter"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Format the card number using your own rules."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:formatter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formatWithCardNumber:formatter:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumber:formatter:)"},"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH"},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberMaskFormatter/gaps":{"role":"symbol","title":"gaps","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"gaps"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/gaps","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gaps"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbermaskformatter\/gaps"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberMaskFormatter":{"role":"symbol","title":"DLCardNumberMaskFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardNumberMaskFormatter"}],"abstract":[{"type":"text","text":"Used to format a card number using the last digits."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:formatter:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardNumberMaskFormatter"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbermaskformatter"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberMaskFormatter/length":{"role":"symbol","title":"length","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/length","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"length"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbermaskformatter\/length"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberMaskFormatter/init(length:gaps:)":{"role":"symbol","title":"init(length:gaps:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gaps"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Creates a formatter instance."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/init(length:gaps:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLength:gaps:"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbermaskformatter\/init(length:gaps:)"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DLCardNumberMaskFormatter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardNumberMaskFormatter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DLCardNumberMaskFormatter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/gaps","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/length"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/init(brand:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberMaskFormatter\/init(length:gaps:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardNumberMaskFormatter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter~1init(brand:)\/title","value":"initWithBrand:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter~1init(brand:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBrand:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:formatter:)\/title","value":"formatWithCardNumber:formatter:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:formatter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithCardNumber:formatter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter~1gaps\/title","value":"gaps"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter~1gaps\/fragments","value":[{"kind":"identifier","text":"gaps"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter\/title","value":"DLCardNumberMaskFormatter"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter\/fragments","value":[{"kind":"identifier","text":"DLCardNumberMaskFormatter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter~1length\/title","value":"length"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter~1length\/fragments","value":[{"kind":"identifier","text":"length"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter~1init(length:gaps:)\/title","value":"initWithLength:gaps:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberMaskFormatter~1init(length:gaps:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLength:gaps:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}