{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installments"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo"]]},"metadata":{"modules":[{"name":"DLDirectSDK"}],"roleHeading":"Instance Property","title":"installments","role":"symbol","symbolKind":"property","externalID":"c:@M@DLDirectSDK@objc(cs)DLBinInfo(py)installments","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"installments"},{"text":": ","kind":"text"},{"text":"DLInstallments","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLInstallments"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"installments","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"installments","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DLInstallments","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLInstallments","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"If you use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)"},{"type":"text","text":", this value will be "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" as you are just requesting bin information."},{"type":"text","text":" "},{"type":"text","text":"If you use "},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","isActive":true},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"this value will contain the installments information OR will be ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if something went wrong when attempting to create installments. Look into the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installmentsError"},{"text":" ","type":"text"},{"type":"text","text":"to get more information about what went wrong."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/dldirectsdk\/dlbininfo\/installments"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlbininfo\/installments"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallments":{"url":"\/documentation\/dldirectsdk\/dlinstallments","abstract":[{"type":"text","text":"The available installment options."},{"text":" ","type":"text"},{"text":"This is used as output parameter in the ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","isActive":true,"type":"reference"},{"type":"text","text":" method."}],"navigatorTitle":[{"kind":"identifier","text":"DLInstallments"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments","title":"DLInstallments","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLInstallments"}],"role":"symbol","type":"topic"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/installments":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installments","navigatorTitle":[{"text":"installments","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"installments","kind":"identifier"},{"kind":"text","text":": "},{"text":"DLInstallments","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLInstallments"},{"kind":"text","text":"?"}],"title":"installments","type":"topic","abstract":[{"text":"If you use ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","isActive":true},{"text":", this value will be ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" as you are just requesting bin information.","type":"text"},{"type":"text","text":" "},{"text":"If you use ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","isActive":true},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"this value will contain the installments information OR will be "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if something went wrong when attempting to create installments. Look into the "},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installmentsError","isActive":true},{"text":" ","type":"text"},{"type":"text","text":"to get more information about what went wrong."}],"url":"\/documentation\/dldirectsdk\/dlbininfo\/installments","role":"symbol","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo":{"title":"DLBinInfo","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","role":"symbol","navigatorTitle":[{"text":"DLBinInfo","kind":"identifier"}],"type":"topic","abstract":[{"text":"The information obtained from the bin number of the card.","type":"text"},{"type":"text","text":" "},{"text":"This is used as output parameter in the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","isActive":true},{"type":"text","text":" method."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLBinInfo","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlbininfo"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","url":"\/documentation\/dldirectsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","role":"collection"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/installmentsError":{"title":"installmentsError","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installmentsError","role":"symbol","navigatorTitle":[{"text":"installmentsError","kind":"identifier"}],"type":"topic","abstract":[{"text":"If you use ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","isActive":true},{"text":", this value will be ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" as you are just requesting bin information."},{"text":" ","type":"text"},{"type":"text","text":"If you use "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"and something goes wrong creating installments, this value will contain information about what went wrong.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"installmentsError","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","kind":"typeIdentifier","text":"DLError"},{"text":"?","kind":"text"}],"url":"\/documentation\/dldirectsdk\/dlbininfo\/installmentserror"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"role":"symbol","kind":"symbol","title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getBinInformation","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"binNumber"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currencyCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"amount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"DLBinInfo","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"DLError","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)","type":"topic","abstract":[{"text":"Get bin information and installments.","type":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:onSuccess:onError:)":{"navigatorTitle":[{"text":"getBinInformationWithBinNumber:onSuccess:onError:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","role":"symbol","abstract":[{"type":"text","text":"Get bin information"}],"type":"topic","title":"getBinInformation(binNumber:onSuccess:onError:)","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:onsuccess:onerror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getBinInformation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"binNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","text":"DLBinInfo","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","kind":"typeIdentifier","text":"DLError"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"installments","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"installments","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DLInstallments","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLInstallments","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallments"},{"kind":"text","text":" * "},{"text":"installments","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DLInstallments","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallments\/fragments","op":"replace","value":[{"text":"DLInstallments","kind":"identifier"}]},{"value":"installments","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1installments\/title","op":"replace"},{"value":[{"text":"installments","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1installments\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/title","value":"DLBinInfo"},{"value":[{"kind":"identifier","text":"DLBinInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/fragments"},{"value":"installmentsError","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1installmentsError\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1installmentsError\/fragments","value":[{"text":"installmentsError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:onSuccess:onError:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBinInformationWithBinNumber:onSuccess:onError:"}]}]}]}