{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mastercardDebito"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"metadata":{"title":"DLCardBrandIdentifier.mastercardDebito","modules":[{"name":"DLDirectSDK"}],"externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierMastercardDebito","symbolKind":"case","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mastercardDebito"}],"navigatorTitle":[{"text":"DLCardBrandIdentifierMastercardDebito","kind":"identifier"}]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mastercardDebito"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/mastercarddebito"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/mastercarddebito"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","role":"symbol","title":"DLCardBrandIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandIdentifier","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The available card brand identifiers."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/mastercardDebito":{"title":"DLCardBrandIdentifier.mastercardDebito","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mastercardDebito","role":"symbol","abstract":[],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/mastercarddebito","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mastercardDebito"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierMastercardDebito"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","url":"\/documentation\/dldirectsdk","role":"collection","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DLCardBrandIdentifierMastercardDebito"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierMastercardDebito"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DLCardBrandIdentifierMastercardDebito"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DLCardBrandIdentifier","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title"},{"value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mastercardDebito\/title","value":"DLCardBrandIdentifierMastercardDebito"},{"value":[{"kind":"identifier","text":"DLCardBrandIdentifierMastercardDebito"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mastercardDebito\/fragments","op":"replace"}]}]}