{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/mercadopago"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/mercadopago"]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mercadopago","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"metadata":{"title":"DLCardBrandIdentifier.mercadopago","modules":[{"name":"DLDirectSDK"}],"externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierMercadopago","symbolKind":"case","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mercadopago","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandIdentifierMercadopago","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mercadopago"}]}]}],"kind":"symbol","sections":[],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","role":"symbol","title":"DLCardBrandIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandIdentifier","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The available card brand identifiers."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"kind":"symbol","url":"\/documentation\/dldirectsdk","role":"collection","title":"DLDirectSDK","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","abstract":[]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/mercadopago":{"title":"DLCardBrandIdentifier.mercadopago","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mercadopago","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mercadopago"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierMercadopago"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/mercadopago","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DLCardBrandIdentifierMercadopago","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DLCardBrandIdentifierMercadopago"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DLCardBrandIdentifierMercadopago","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DLCardBrandIdentifier","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DLCardBrandIdentifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mercadopago\/title","value":"DLCardBrandIdentifierMercadopago","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mercadopago\/fragments","value":[{"text":"DLCardBrandIdentifierMercadopago","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}