{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"decoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dltoken\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLToken\/init(from:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Decodable.init(from:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(from:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DLDirectSDK7DLTokenC4fromACs7Decoder_p_tKcfc","modules":[{"name":"DLDirectSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLToken"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLToken/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLToken\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk\/dltoken\/init(from:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/tokenizeCard(cardData:onSuccess:onError:)":{"role":"symbol","title":"tokenizeCard(cardData:onSuccess:onError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenizeCard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardData","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"DLToken","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLToken"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"DLError","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tokenizes a card."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tokenizeCardWithCardData:onSuccess:onError:"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/tokenizecard(carddata:onsuccess:onerror:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLToken":{"role":"symbol","title":"DLToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLToken"}],"abstract":[{"type":"text","text":"The card number tokenized."},{"type":"text","text":" "},{"type":"text","text":"This is the output of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLToken"}],"url":"\/documentation\/dldirectsdk\/dltoken"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/title","value":"tokenizeCardWithCardData:onSuccess:onError:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenizeCardWithCardData:onSuccess:onError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLToken\/title","value":"DLToken"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLToken\/fragments","value":[{"kind":"identifier","text":"DLToken"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}