{"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlerror\/httpstatuscode"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/httpStatusCode","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DLDirectSDK"}],"role":"symbol","title":"httpStatusCode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"httpStatusCode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":"?","kind":"text"}],"externalID":"s:11DLDirectSDK7DLErrorC14httpStatusCodeSiSgvp"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"]]},"abstract":[{"type":"text","text":"The HTTP status code returned by the API."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"httpStatusCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"title":"DLError","abstract":[{"type":"text","text":"Encapsulates error that can happen when using the "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/dldirectsdk\/dlerror","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLError"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLError"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError/httpStatusCode":{"abstract":[{"type":"text","text":"The HTTP status code returned by the API."}],"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlerror\/httpstatuscode","title":"httpStatusCode","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"httpStatusCode"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError\/httpStatusCode"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"title":"DLCardTokenizer","abstract":[{"type":"text","text":"Used to perform various tokenization related operations."}],"role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtokenizer","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardTokenizer"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardTokenizer"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","value":"DLError"},{"value":[{"kind":"identifier","text":"DLError"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","value":"DLCardTokenizer"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLCardTokenizer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}