{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrandContainer","title":"DLCardBrandContainer","symbolKind":"class","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"text":"DLCardBrandContainer","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DLCardBrandContainer","kind":"identifier"}],"roleHeading":"Class","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandcontainer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandcontainer"]}],"sections":[],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer\/ios"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandContainer"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.dlocal.DLDirectSDK/SQ":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandContainer/init(from:)":{"url":"\/documentation\/dldirectsdk\/dlcardbrandcontainer\/init(from:)","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","title":"init(from:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer\/init(from:)"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","abstract":[],"url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandContainer/ios":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ios","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DLBrandImage","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBrandImage","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ios"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer\/ios","url":"\/documentation\/dldirectsdk\/dlcardbrandcontainer\/ios","role":"symbol","kind":"symbol","title":"ios","abstract":[]},"doc://com.dlocal.DLDirectSDK/SH":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandContainer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrandContainer","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DLCardBrandContainer","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer","url":"\/documentation\/dldirectsdk\/dlcardbrandcontainer","role":"symbol","kind":"symbol","title":"DLCardBrandContainer","abstract":[]},"doc://com.dlocal.DLDirectSDK/Se":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","type":"unresolvable","title":"Swift.Decodable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DLCardBrandContainer"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"DLCardBrandContainer"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DLCardBrandContainer"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandContainer\/ios"],"title":"Instance Properties"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DLCardBrandContainer","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"ios","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer~1ios\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer~1ios\/fragments","op":"replace","value":[{"kind":"identifier","text":"ios"}]},{"op":"replace","value":"DLCardBrandContainer","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer\/title"},{"value":[{"text":"DLCardBrandContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandContainer\/fragments"}]}]}