{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getBinInformation","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"binNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"DLBinInfo","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","text":"DLError","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"binNumber","content":[{"type":"paragraph","inlineContent":[{"text":"The first six digits of the card.","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DLDirectSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getBinInformation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"binNumber"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","kind":"typeIdentifier","text":"DLBinInfo"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","kind":"typeIdentifier","text":"DLError"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"getBinInformationWithBinNumber:onSuccess:onError:","kind":"identifier"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardTokenizer(im)getBinInformationWithBinNumber:onSuccess:onError:","symbolKind":"method","role":"symbol","title":"getBinInformation(binNumber:onSuccess:onError:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Get bin information","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:onsuccess:onerror:)"]},{"paths":["\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:onsuccess:onerror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo":{"url":"\/documentation\/dldirectsdk\/dlbininfo","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLBinInfo"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","title":"DLBinInfo","navigatorTitle":[{"text":"DLBinInfo","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The information obtained from the bin number of the card."},{"type":"text","text":" "},{"type":"text","text":"This is used as output parameter in the "},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","isActive":true},{"type":"text","text":" method."}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer":{"url":"\/documentation\/dldirectsdk\/dlcardtokenizer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardTokenizer","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer","title":"DLCardTokenizer","navigatorTitle":[{"text":"DLCardTokenizer","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Used to perform various tokenization related operations.","type":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLError":{"abstract":[{"text":"Encapsulates error that can happen when using the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLError","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLError","title":"DLError","navigatorTitle":[{"text":"DLError","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlerror"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:onSuccess:onError:)":{"abstract":[{"text":"Get bin information","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBinInformation"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","text":"DLBinInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"DLError","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","title":"getBinInformation(binNumber:onSuccess:onError:)","navigatorTitle":[{"kind":"identifier","text":"getBinInformationWithBinNumber:onSuccess:onError:"}],"type":"topic","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:onsuccess:onerror:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"getBinInformationWithBinNumber:onSuccess:onError:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"getBinInformationWithBinNumber:onSuccess:onError:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"getBinInformationWithBinNumber:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"binNumber"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onSuccess:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$@M@DLDirectSDK@objc(cs)DLBinInfo)","kind":"typeIdentifier","text":"void (^)(DLBinInfo *)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"onSuccess"},{"kind":"text","text":" "},{"text":"onError:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(DLError *)","preciseIdentifier":"c:BFv(#*$@M@DLDirectSDK@objc(cs)DLError)"},{"kind":"text","text":") "},{"text":"onError","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DLBinInfo","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/fragments","value":[{"text":"DLBinInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/title","value":"DLCardTokenizer"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer\/fragments","value":[{"kind":"identifier","text":"DLCardTokenizer"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/title","op":"replace","value":"DLError"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLError\/fragments","value":[{"text":"DLError","kind":"identifier"}],"op":"replace"},{"value":"getBinInformationWithBinNumber:onSuccess:onError:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getBinInformationWithBinNumber:onSuccess:onError:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}