{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan"]]},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installmentAmount","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"installmentAmount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"symbolKind":"property","title":"installmentAmount","roleHeading":"Instance Property","externalID":"c:@M@DLDirectSDK@objc(cs)DLInstallmentsPlan(py)installmentAmount","role":"symbol","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"text":"installmentAmount","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlinstallmentsplan\/installmentamount"]},{"paths":["\/documentation\/dldirectsdk\/dlinstallmentsplan\/installmentamount"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The amount paid on each installment, e.g. 200.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"installmentAmount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getBinInformation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"binNumber"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currencyCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"amount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"onSuccess","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","text":"DLBinInfo","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Get bin information and installments.","type":"text"}],"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan":{"type":"topic","title":"DLInstallmentsPlan","url":"\/documentation\/dldirectsdk\/dlinstallmentsplan","role":"symbol","abstract":[{"text":"One of the available installments options.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This is used as output parameter in the "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","type":"reference","isActive":true},{"text":" method.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DLInstallmentsPlan"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLInstallmentsPlan","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan/installmentAmount":{"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlinstallmentsplan\/installmentamount","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"installmentAmount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"The amount paid on each installment, e.g. 200.","type":"text"}],"title":"installmentAmount","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installmentAmount","role":"symbol","navigatorTitle":[{"text":"installmentAmount","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"installmentAmount","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"installmentAmount"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"installmentAmount"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan\/title","value":"DLInstallmentsPlan"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan\/fragments","value":[{"text":"DLInstallmentsPlan","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1installmentAmount\/title","value":"installmentAmount"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1installmentAmount\/fragments","value":[{"text":"installmentAmount","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}