{"sections":[],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/securityCode","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Security code information.","type":"text"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"securityCode"},{"text":": ","kind":"text"},{"text":"DLCardBrandSecurityCode","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrandSecurityCode","kind":"typeIdentifier"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLCardBrand(py)securityCode","navigatorTitle":[{"text":"securityCode","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"securityCode","modules":[{"name":"DLDirectSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/securitycode"]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrand\/securitycode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"securityCode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode","kind":"typeIdentifier","text":"DLCardBrandSecurityCode","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrandSecurityCode"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandSecurityCode":{"abstract":[{"type":"text","text":"The information about the security code for a specific card brand."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode","role":"symbol","title":"DLCardBrandSecurityCode","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandSecurityCode","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandsecuritycode"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand/securityCode":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"securityCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DLCardBrandSecurityCode","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrandSecurityCode","kind":"typeIdentifier"}],"abstract":[{"text":"Security code information.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand\/securityCode","title":"securityCode","navigatorTitle":[{"kind":"identifier","text":"securityCode"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrand\/securitycode"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","abstract":[],"url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"role":"symbol","abstract":[{"text":"The brand identifing the issuer of a card.","type":"text"}],"title":"DLCardBrand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrand"}],"navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrand"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"securityCode"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"securityCode"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandSecurityCode","kind":"typeIdentifier","text":"DLCardBrandSecurityCode","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrandSecurityCode"},{"text":" * ","kind":"text"},{"text":"securityCode","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode\/title","op":"replace","value":"DLCardBrandSecurityCode"},{"op":"replace","value":[{"kind":"identifier","text":"DLCardBrandSecurityCode"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandSecurityCode\/fragments"},{"value":"securityCode","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1securityCode\/title"},{"value":[{"text":"securityCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand~1securityCode\/fragments","op":"replace"},{"value":"DLCardBrand","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title","op":"replace"},{"value":[{"text":"DLCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}