{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cmr"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cmr"]},{"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cmr"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"metadata":{"modules":[{"name":"DLDirectSDK"}],"title":"DLCardBrandIdentifier.cmr","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierCmr","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cmr","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandIdentifierCmr","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cmr","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/cmr":{"kind":"symbol","title":"DLCardBrandIdentifier.cmr","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cmr","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cmr","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cmr"}],"role":"symbol","navigatorTitle":[{"text":"DLCardBrandIdentifierCmr","kind":"identifier"}],"type":"topic","abstract":[]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandIdentifier","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","type":"topic","abstract":[{"text":"The available card brand identifiers.","type":"text"}],"title":"DLCardBrandIdentifier","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DLCardBrandIdentifierCmr"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"DLCardBrandIdentifierCmr","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DLCardBrandIdentifierCmr"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cmr\/title","value":"DLCardBrandIdentifierCmr","op":"replace"},{"op":"replace","value":[{"text":"DLCardBrandIdentifierCmr","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cmr\/fragments"},{"value":"DLCardBrandIdentifier","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments","value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}