{"metadata":{"modules":[{"name":"DLDirectSDK"}],"title":"DLCardBrandIdentifier.maestro","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"maestro","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierMaestro"}],"symbolKind":"case","externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierMaestro"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"maestro","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/maestro"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/maestro"]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/maestro"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLCardBrandIdentifier","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","type":"topic","abstract":[{"text":"The available card brand identifiers.","type":"text"}],"title":"DLCardBrandIdentifier","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/maestro":{"kind":"symbol","title":"DLCardBrandIdentifier.maestro","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/maestro","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/maestro","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maestro"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierMaestro"}],"type":"topic","abstract":[]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"title":"DLDirectSDK","role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"DLCardBrandIdentifierMaestro","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierMaestro"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DLCardBrandIdentifierMaestro","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title","value":"DLCardBrandIdentifier"},{"op":"replace","value":[{"kind":"identifier","text":"DLCardBrandIdentifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments"},{"value":"DLCardBrandIdentifierMaestro","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1maestro\/title"},{"value":[{"text":"DLCardBrandIdentifierMaestro","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1maestro\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}