{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/verve"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verve","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierVerve","title":"DLCardBrandIdentifier.verve","navigatorTitle":[{"text":"DLCardBrandIdentifierVerve","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verve","kind":"identifier"}],"modules":[{"name":"DLDirectSDK"}],"symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/verve"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/verve"]}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","title":"DLCardBrandIdentifier","abstract":[{"type":"text","text":"The available card brand identifiers."}],"navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"url":"\/documentation\/dldirectsdk","abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/verve":{"kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/verve","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierVerve"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/verve","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verve"}],"abstract":[],"title":"DLCardBrandIdentifier.verve"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DLCardBrandIdentifierVerve"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DLCardBrandIdentifierVerve","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DLCardBrandIdentifierVerve","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DLCardBrandIdentifier","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments","value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1verve\/title","op":"replace","value":"DLCardBrandIdentifierVerve"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1verve\/fragments","op":"replace","value":[{"text":"DLCardBrandIdentifierVerve","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}