{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"validation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm","text":"DLCardBrandValidationAlgorithm"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"lengths","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The lengths expected for this card number or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if length should not be validated."}]}]},{"name":"validation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The algorithm to validate this card number."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardnumbervalidator\/init(lengths:validation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcardnumbervalidator\/init(lengths:validation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator\/init(lengths:validation:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates an instance of the validator."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"validation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm"},{"kind":"text","text":")"}],"title":"init(lengths:validation:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardNumberValidator(im)initWithLengths:validation:","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLengths:validation:"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(cardNumber:validator:)":{"role":"symbol","title":"validate(cardNumber:validator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardNumberValidator","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardNumberValidator"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate a card number using the given validator."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:validator:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithCardNumber:validator:"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(cardnumber:validator:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberValidator/init(lengths:validation:)":{"role":"symbol","title":"init(lengths:validation:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"validation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates an instance of the validator."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator\/init(lengths:validation:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLengths:validation:"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbervalidator\/init(lengths:validation:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardNumberValidator":{"role":"symbol","title":"DLCardNumberValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardNumberValidator"}],"abstract":[{"type":"text","text":"Defines the card number validation rules."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(cardNumber:validator:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardNumberValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardNumberValidator"}],"url":"\/documentation\/dldirectsdk\/dlcardnumbervalidator"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandValidationAlgorithm":{"role":"symbol","title":"DLCardBrandValidationAlgorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"abstract":[{"type":"text","text":"The algorithm used for validating the brand’s card numbers."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandvalidationalgorithm"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLengths:validation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLengths:validation:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLengths:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"lengths"},{"kind":"text","text":" "},{"kind":"identifier","text":"validation:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandValidationAlgorithm","preciseIdentifier":"c:@M@DLDirectSDK@E@DLCardBrandValidationAlgorithm","text":"DLCardBrandValidationAlgorithm"},{"kind":"text","text":")"},{"kind":"internalParam","text":"validation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(cardNumber:validator:)\/title","value":"validateWithCardNumber:validator:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(cardNumber:validator:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithCardNumber:validator:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator~1init(lengths:validation:)\/title","value":"initWithLengths:validation:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator~1init(lengths:validation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLengths:validation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator\/title","value":"DLCardNumberValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardNumberValidator\/fragments","value":[{"kind":"identifier","text":"DLCardNumberValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/title","value":"DLCardBrandValidationAlgorithm"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandValidationAlgorithm\/fragments","value":[{"kind":"identifier","text":"DLCardBrandValidationAlgorithm"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}