{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"metadata":{"symbolKind":"method","title":"format(cardNumberEndingWith:brand:)","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumberEndingWith"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"brand","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier","text":"DLCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"formatWithCardNumberEndingWith:brand:"}],"extendedModule":"DLDirectSDK","externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)formatWithCardNumberEndingWith:brand:"},"abstract":[{"type":"text","text":"Format the card number using the last digits."},{"text":" ","type":"text"},{"text":"The difference between this and ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:)","isActive":true,"type":"reference"},{"text":" is that you specify what brand to use.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This is preferred as it will make the formatted string match what’s displayed on the brand."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":"("},{"text":"cardNumberEndingWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"lastNumbers","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"brand","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The last numbers of the card."}]}],"name":"lastNumbers"},{"name":"brand","content":[{"inlineContent":[{"type":"text","text":"The brand of the card."}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"The formatted card number.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:brand:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumberendingwith:brand:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumberendingwith:brand:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumberEndingWith:)":{"type":"topic","title":"format(cardNumberEndingWith:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"kind":"text","text":"("},{"text":"cardNumberEndingWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"Format the card number using the last digits."},{"text":" ","type":"text"},{"type":"text","text":"If you know the brand of the card then you can use "},{"isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","type":"reference"},{"text":" which will provide a formatted version that matches what’s on the card.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumberendingwith:)","navigatorTitle":[{"text":"formatWithCardNumberEndingWith:","kind":"identifier"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","kind":"symbol","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumber:brand:)":{"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","title":"format(cardNumber:brand:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"format","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"brand","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","text":"DLCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"Fromat a card number to match what’s shown on the card.","type":"text"},{"text":" ","type":"text"},{"text":"The difference between this and ","type":"text"},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumber:brand:)","type":"reference","isActive":true},{"text":" is that we will not attempt to detect the brand from the number, instead we will use what you pass as parameter.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumber:brand:)","navigatorTitle":[{"text":"formatWithCardNumber:brand:","kind":"identifier"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrand":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardBrand","kind":"identifier"}],"title":"DLCardBrand","role":"symbol","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrand","type":"topic","navigatorTitle":[{"text":"DLCardBrand","kind":"identifier"}],"abstract":[{"type":"text","text":"The brand identifing the issuer of a card."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/format(cardNumberEndingWith:brand:)":{"type":"topic","title":"format(cardNumberEndingWith:brand:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:brand:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cardNumberEndingWith","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brand"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier","text":"DLCardBrand"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"Format the card number using the last digits.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The difference between this and "},{"isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/format(cardNumberEndingWith:)","type":"reference"},{"text":" is that you specify what brand to use.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is preferred as it will make the formatted string match what’s displayed on the brand."}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/format(cardnumberendingwith:brand:)","navigatorTitle":[{"text":"formatWithCardNumberEndingWith:brand:","kind":"identifier"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLCardExpert","kind":"identifier"}],"title":"DLCardExpert","role":"symbol","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}],"abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"formatWithCardNumberEndingWith:brand:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"formatWithCardNumberEndingWith:brand:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"formatWithCardNumberEndingWith:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"lastNumbers","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"brand:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrand","text":"DLCardBrand","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardBrand","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"brand","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumberEndingWith:)\/title","value":"formatWithCardNumberEndingWith:"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumberEndingWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithCardNumberEndingWith:"}],"op":"replace"},{"op":"replace","value":"formatWithCardNumber:brand:","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:brand:)\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumber:brand:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithCardNumber:brand:"}],"op":"replace"},{"value":"DLCardBrand","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrand\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLCardBrand"}]},{"value":"formatWithCardNumberEndingWith:brand:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumberEndingWith:brand:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1format(cardNumberEndingWith:brand:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formatWithCardNumberEndingWith:brand:"}]},{"value":"DLCardExpert","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"text":"DLCardExpert","kind":"identifier"}],"op":"replace"}]}]}