{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"text":"expirationDate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]},{"parameters":[{"name":"expirationDate","content":[{"inlineContent":[{"type":"text","text":"The expiration date to validate, e.g. “05\/24”."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"True if the expiration date is valid, false otherwise."}],"type":"paragraph"}]}],"metadata":{"symbolKind":"method","modules":[{"name":"DLDirectSDK"}],"role":"symbol","navigatorTitle":[{"text":"validateWithExpirationDate:","kind":"identifier"}],"title":"validate(expirationDate:)","roleHeading":"Instance Method","externalID":"c:@CM@DLDirectSDK@objc(cs)DLCardExpert(im)validateWithExpirationDate:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"expirationDate"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Validate the expiration date.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Validation includes proper formatting of the expiration date and also that card is not expired."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(expirationDate:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/validate(expirationdate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardexpert\/validate(expirationdate:)"]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","role":"collection","title":"DLDirectSDK","kind":"symbol","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert":{"abstract":[{"type":"text","text":"Used  to perform various operations around cards, like format a card number or validate an expiration date."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DLCardExpert","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardExpert"}],"title":"DLCardExpert","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardexpert"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardExpert/validate(expirationDate:)":{"title":"validate(expirationDate:)","abstract":[{"type":"text","text":"Validate the expiration date."},{"type":"text","text":" "},{"type":"text","text":"Validation includes proper formatting of the expiration date and also that card is not expired."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"expirationDate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/dldirectsdk\/dlcardexpert\/validate(expirationdate:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"validateWithExpirationDate:","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardExpert\/validate(expirationDate:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"validateWithExpirationDate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"validateWithExpirationDate:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"validateWithExpirationDate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expirationDate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/title","value":"DLCardExpert"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert\/fragments","value":[{"kind":"identifier","text":"DLCardExpert"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(expirationDate:)\/title","op":"replace","value":"validateWithExpirationDate:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardExpert~1validate(expirationDate:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"validateWithExpirationDate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}