{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DLDirectSDK@objc(cs)DLBrandImage(py)density","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"density"},{"text":": ","kind":"text"},{"text":"DLImageDensity","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity"}],"role":"symbol","modules":[{"name":"DLDirectSDK"}],"title":"density","symbolKind":"property","navigatorTitle":[{"text":"density","kind":"identifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlbrandimage\/density"]},{"paths":["\/documentation\/dldirectsdk\/dlbrandimage\/density"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"density"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity","kind":"typeIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","text":"DLImageDensity"}]}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/density","interfaceLanguage":"swift"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","type":"topic","url":"\/documentation\/dldirectsdk","title":"DLDirectSDK"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLBrandImage"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage","title":"DLBrandImage","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLBrandImage"}],"url":"\/documentation\/dldirectsdk\/dlbrandimage","role":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity":{"kind":"symbol","type":"topic","abstract":[],"title":"DLImageDensity","url":"\/documentation\/dldirectsdk\/dlimagedensity","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLImageDensity"}],"navigatorTitle":[{"text":"DLImageDensity","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBrandImage/density":{"url":"\/documentation\/dldirectsdk\/dlbrandimage\/density","role":"symbol","title":"density","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"density","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity","kind":"typeIdentifier","text":"DLImageDensity"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"density"}],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBrandImage\/density"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"density"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"density","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@E@DLImageDensity","text":"DLImageDensity","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"density","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/title","value":"DLBrandImage"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage\/fragments","value":[{"text":"DLBrandImage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/title","value":"DLImageDensity"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/fragments","value":[{"text":"DLImageDensity","kind":"identifier"}]},{"op":"replace","value":"density","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1density\/title"},{"value":[{"kind":"identifier","text":"density"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBrandImage~1density\/fragments"}]}]}