{"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DLImageSize"}],"externalID":"c:@M@DLDirectSDK@E@DLImageSize","roleHeading":"Enumeration","modules":[{"name":"DLDirectSDK"}],"role":"symbol","title":"DLImageSize","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLImageSize","kind":"identifier"}],"symbolKind":"enum"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH","doc:\/\/com.dlocal.DLDirectSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlimagesize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlimagesize"]}],"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/small"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/Equatable-Implementations","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/RawRepresentable-Implementations"],"generated":true}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLImageSize"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk","title":"DLDirectSDK","abstract":[],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","title":"Swift.Equatable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize/small":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"small","kind":"identifier"}],"title":"DLImageSize.small","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/small","kind":"symbol","role":"symbol","url":"\/documentation\/dldirectsdk\/dlimagesize\/small","navigatorTitle":[{"text":"DLImageSizeSmall","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DLImageSize","kind":"identifier"}],"title":"DLImageSize","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dldirectsdk\/dlimagesize","navigatorTitle":[{"text":"DLImageSize","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/dldirectsdk\/dlimagesize\/rawrepresentable-implementations"},"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","title":"Swift.Hashable"},"doc://com.dlocal.DLDirectSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.dlocal.DLDirectSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","title":"Swift.Decodable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/init(rawValue:)","kind":"symbol","role":"symbol","url":"\/documentation\/dldirectsdk\/dlimagesize\/init(rawvalue:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageSize/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/Equatable-Implementations","type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/dldirectsdk\/dlimagesize\/equatable-implementations"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"DLImageSize","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DLImageSize","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DLImageSize"}]},{"value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageSize\/small"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLImageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DLImageSizeSmall","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize~1small\/title"},{"value":[{"text":"DLImageSizeSmall","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize~1small\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/title","value":"DLImageSize","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageSize\/fragments","value":[{"text":"DLImageSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}