{"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DLImageDensity","kind":"identifier"}],"title":"DLImageDensity","externalID":"c:@M@DLDirectSDK@E@DLImageDensity","roleHeading":"Enumeration","symbolKind":"enum","modules":[{"name":"DLDirectSDK"}],"role":"symbol","navigatorTitle":[{"text":"DLImageDensity","kind":"identifier"}]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x1","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x2","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x3"]},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/Equatable-Implementations","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlimagedensity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlimagedensity"]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH","doc:\/\/com.dlocal.DLDirectSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DLImageDensity","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity/x2":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"DLImageDensityX2","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/dldirectsdk\/dlimagedensity\/x2","title":"DLImageDensity.x2","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x2","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"x2","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk","title":"DLDirectSDK","abstract":[],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","title":"Swift.Equatable"},"doc://com.dlocal.DLDirectSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","title":"Swift.Hashable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity/RawRepresentable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/RawRepresentable-Implementations","url":"\/documentation\/dldirectsdk\/dlimagedensity\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity":{"url":"\/documentation\/dldirectsdk\/dlimagedensity","role":"symbol","type":"topic","abstract":[],"title":"DLImageDensity","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DLImageDensity","kind":"identifier"}],"navigatorTitle":[{"text":"DLImageDensity","kind":"identifier"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity/x1":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"DLImageDensityX1","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/dldirectsdk\/dlimagedensity\/x1","title":"DLImageDensity.x1","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x1","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"x1","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity/x3":{"url":"\/documentation\/dldirectsdk\/dlimagedensity\/x3","role":"symbol","type":"topic","abstract":[],"title":"DLImageDensity.x3","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"x3"}],"navigatorTitle":[{"kind":"identifier","text":"DLImageDensityX3"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.dlocal.DLDirectSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","title":"Swift.Decodable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/init(rawValue:)","kind":"symbol","role":"symbol","url":"\/documentation\/dldirectsdk\/dlimagedensity\/init(rawvalue:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLImageDensity/Equatable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/Equatable-Implementations","url":"\/documentation\/dldirectsdk\/dlimagedensity\/equatable-implementations","title":"Equatable Implementations"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DLImageDensity"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DLImageDensity"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DLImageDensity","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x1","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x2","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLImageDensity\/x3"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLImageDensity","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x2\/title","value":"DLImageDensityX2"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x2\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLImageDensityX2"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/title","value":"DLImageDensity","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity\/fragments","op":"replace","value":[{"text":"DLImageDensity","kind":"identifier"}]},{"value":"DLImageDensityX1","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x1\/title"},{"value":[{"text":"DLImageDensityX1","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x1\/fragments","op":"replace"},{"value":"DLImageDensityX3","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x3\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLImageDensity~1x3\/fragments","value":[{"text":"DLImageDensityX3","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}