{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"holderName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcarddata\/holdername"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dldirectsdk\/dlcarddata\/holdername"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData\/holderName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Holder name as it appears on the card, e.g. “JOHN SMITH”."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"holderName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"holderName","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DLDirectSDK@objc(cs)DLCardData(py)holderName","modules":[{"name":"DLDirectSDK"}],"navigatorTitle":[{"kind":"identifier","text":"holderName"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData"]]},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/tokenizeCard(cardData:onSuccess:onError:)":{"role":"symbol","title":"tokenizeCard(cardData:onSuccess:onError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenizeCard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DLCardData","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLCardData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"DLToken","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLToken"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"DLError","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tokenizes a card."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tokenizeCardWithCardData:onSuccess:onError:"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/tokenizecard(carddata:onsuccess:onerror:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","title":"DLDirectSDK","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","kind":"symbol","type":"topic","url":"\/documentation\/dldirectsdk"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardData":{"role":"symbol","title":"DLCardData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardData"}],"abstract":[{"type":"text","text":"Encapsulates data for the card you want to tokenize."},{"type":"text","text":" "},{"type":"text","text":"This is used as input parameter in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/tokenizeCard(cardData:onSuccess:onError:)"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DLCardData"}],"url":"\/documentation\/dldirectsdk\/dlcarddata"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardData/holderName":{"role":"symbol","title":"holderName","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"holderName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Holder name as it appears on the card, e.g. “JOHN SMITH”."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardData\/holderName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"holderName"}],"url":"\/documentation\/dldirectsdk\/dlcarddata\/holdername"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"holderName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"holderName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"holderName"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/title","value":"tokenizeCardWithCardData:onSuccess:onError:"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1tokenizeCard(cardData:onSuccess:onError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenizeCardWithCardData:onSuccess:onError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData\/title","value":"DLCardData"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData\/fragments","value":[{"kind":"identifier","text":"DLCardData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData~1holderName\/title","value":"holderName"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardData~1holderName\/fragments","value":[{"kind":"identifier","text":"holderName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}