{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"roleHeading":"Initializer","modules":[{"name":"DLDirectSDK"}],"symbolKind":"init","externalID":"s:11DLDirectSDK9DLBinInfoC4fromACs7Decoder_p_tKcfc","title":"init(from:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Decodable.init(from:)","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/init(from:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlbininfo\/init(from:)"]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo":{"abstract":[{"type":"text","text":"The information obtained from the bin number of the card."},{"type":"text","text":" "},{"type":"text","text":"This is used as output parameter in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)"},{"type":"text","text":" method."}],"type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","title":"DLBinInfo","kind":"symbol","role":"symbol","url":"\/documentation\/dldirectsdk\/dlbininfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLBinInfo","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLBinInfo"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","url":"\/documentation\/dldirectsdk","title":"DLDirectSDK","abstract":[],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/init(from:)":{"url":"\/documentation\/dldirectsdk\/dlbininfo\/init(from:)","role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/init(from:)","abstract":[],"title":"init(from:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:onSuccess:onError:)":{"abstract":[{"type":"text","text":"Get bin information"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","title":"getBinInformation(binNumber:onSuccess:onError:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:onsuccess:onerror:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getBinInformation","kind":"identifier"},{"kind":"text","text":"("},{"text":"binNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": ("},{"text":"DLBinInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"getBinInformationWithBinNumber:onSuccess:onError:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/title","value":"DLBinInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/fragments","value":[{"kind":"identifier","text":"DLBinInfo"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/title","op":"replace","value":"getBinInformationWithBinNumber:onSuccess:onError:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getBinInformationWithBinNumber:onSuccess:onError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/fragments"}]}]}