{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/hipercard"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"hipercard","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"DLCardBrandIdentifierHipercard","kind":"identifier"}],"modules":[{"name":"DLDirectSDK"}],"title":"DLCardBrandIdentifier.hipercard","externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierHipercard"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/hipercard"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/hipercard"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"hipercard","kind":"identifier"}]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/hipercard":{"navigatorTitle":[{"text":"DLCardBrandIdentifierHipercard","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/hipercard","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/hipercard","title":"DLCardBrandIdentifier.hipercard","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hipercard","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DLCardBrandIdentifier","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"abstract":[{"type":"text","text":"The available card brand identifiers."}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","title":"DLCardBrandIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","role":"symbol","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","title":"DLDirectSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DLCardBrandIdentifierHipercard","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLCardBrandIdentifierHipercard"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DLCardBrandIdentifierHipercard"}]}]}},{"value":"DLCardBrandIdentifierHipercard","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1hipercard\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1hipercard\/fragments","value":[{"text":"DLCardBrandIdentifierHipercard","kind":"identifier"}]},{"value":"DLCardBrandIdentifier","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifier"}],"op":"replace"}]}]}