{"sections":[],"variants":[{"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/unionpay"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier\/unionpay"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unionpay"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier@DLCardBrandIdentifierUnionpay","roleHeading":"Case","modules":[{"name":"DLDirectSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unionpay"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierUnionpay"}],"title":"DLCardBrandIdentifier.unionpay","role":"symbol"},"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/unionpay","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DLCardBrandIdentifier","kind":"identifier"}],"navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"abstract":[{"type":"text","text":"The available card brand identifiers."}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","title":"DLCardBrandIdentifier","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","role":"symbol","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/unionpay":{"navigatorTitle":[{"text":"DLCardBrandIdentifierUnionpay","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/unionpay","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/unionpay","title":"DLCardBrandIdentifier.unionpay","type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unionpay","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","title":"DLDirectSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"DLCardBrandIdentifierUnionpay","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierUnionpay"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DLCardBrandIdentifierUnionpay"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DLCardBrandIdentifier","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments","op":"replace","value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}]},{"value":"DLCardBrandIdentifierUnionpay","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1unionpay\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1unionpay\/fragments","op":"replace","value":[{"text":"DLCardBrandIdentifierUnionpay","kind":"identifier"}]}]}]}