{"abstract":[{"type":"text","text":"The number of installments, e.g. 6."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installments","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dldirectsdk\/dlinstallmentsplan\/installments"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlinstallmentsplan\/installments"]}],"metadata":{"navigatorTitle":[{"text":"installments","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"installments","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"installments","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"DLDirectSDK"}],"externalID":"c:@M@DLDirectSDK@objc(cs)DLInstallmentsPlan(py)installments"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"installments","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","title":"DLDirectSDK","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan/installments":{"url":"\/documentation\/dldirectsdk\/dlinstallmentsplan\/installments","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan\/installments","title":"installments","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"installments"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"installments"}],"abstract":[{"text":"The number of installments, e.g. 6.","type":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getBinInformation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"binNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currencyCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"amount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","text":"DLBinInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"DLError","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get bin information and installments."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"}],"url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLInstallmentsPlan":{"navigatorTitle":[{"text":"DLInstallmentsPlan","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlinstallmentsplan","title":"DLInstallmentsPlan","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLInstallmentsPlan"}],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLInstallmentsPlan","abstract":[{"type":"text","text":"One of the available installments options."},{"type":"text","text":" "},{"type":"text","text":"This is used as output parameter in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)"},{"text":" method.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"installments"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"installments","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"installments"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1installments\/title","value":"installments"},{"value":[{"kind":"identifier","text":"installments"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan~1installments\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title","value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:"}]},{"value":"DLInstallmentsPlan","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLInstallmentsPlan\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLInstallmentsPlan"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}