{"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The information obtained from the bin number of the card."},{"text":" ","type":"text"},{"type":"text","text":"This is used as output parameter in the "},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","isActive":true},{"text":" method.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/init(from:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/bin","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/brand","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/country","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installments","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installmentsError","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/type"],"title":"Instance Properties"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DLBinInfo","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlbininfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlbininfo"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","doc:\/\/com.dlocal.DLDirectSDK\/Se","doc:\/\/com.dlocal.DLDirectSDK\/SE","doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"metadata":{"roleHeading":"Class","title":"DLBinInfo","externalID":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","navigatorTitle":[{"text":"DLBinInfo","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLBinInfo"}],"modules":[{"name":"DLDirectSDK"}],"symbolKind":"class"},"references":{"doc://com.dlocal.DLDirectSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SE","title":"Swift.Encodable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/type":{"type":"topic","role":"symbol","title":"type","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/type","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"abstract":[{"text":"The type of card type, e.g. “credit”.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlbininfo\/type"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/installments":{"type":"topic","role":"symbol","title":"installments","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installments","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"installments"},{"text":": ","kind":"text"},{"text":"DLInstallments","kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLInstallments"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"installments","kind":"identifier"}],"abstract":[{"text":"If you use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)"},{"type":"text","text":", this value will be "},{"type":"codeVoice","code":"nil"},{"text":" as you are just requesting bin information.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)"},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"this value will contain the installments information OR will be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if something went wrong when attempting to create installments. Look into the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installmentsError"},{"text":" ","type":"text"},{"text":"to get more information about what went wrong.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlbininfo\/installments"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:onSuccess:onError:)":{"navigatorTitle":[{"kind":"identifier","text":"getBinInformationWithBinNumber:onSuccess:onError:"}],"role":"symbol","abstract":[{"type":"text","text":"Get bin information"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getBinInformation"},{"text":"(","kind":"text"},{"text":"binNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","text":"DLBinInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onError"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:onsuccess:onerror:)","kind":"symbol","title":"getBinInformation(binNumber:onSuccess:onError:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","title":"DLDirectSDK","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s28CustomDebugStringConvertibleP"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/brand":{"title":"brand","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/brand","type":"topic","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlbininfo\/brand","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"text":"brand","kind":"identifier"}],"abstract":[{"type":"text","text":"The identifier of the card brand, e.g. “VI” for a “VISA” card."}]},"doc://com.dlocal.DLDirectSDK/Se":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/SH":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo":{"navigatorTitle":[{"text":"DLBinInfo","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The information obtained from the bin number of the card.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is used as output parameter in the "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","isActive":true,"type":"reference"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLBinInfo"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlbininfo","kind":"symbol","title":"DLBinInfo"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/installmentsError":{"type":"topic","role":"symbol","title":"installmentsError","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installmentsError","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"installmentsError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","kind":"typeIdentifier","text":"DLError"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"installmentsError","kind":"identifier"}],"abstract":[{"text":"If you use ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:onSuccess:onError:)","isActive":true},{"type":"text","text":", this value will be "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" as you are just requesting bin information."},{"text":" ","type":"text"},{"type":"text","text":"If you use "},{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"and something goes wrong creating installments, this value will contain information about what went wrong.","type":"text"}],"url":"\/documentation\/dldirectsdk\/dlbininfo\/installmentserror"},"doc://com.dlocal.DLDirectSDK/SQ":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/init(from:)":{"type":"topic","role":"symbol","title":"init(from:)","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","abstract":[],"url":"\/documentation\/dldirectsdk\/dlbininfo\/init(from:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/country":{"type":"topic","role":"symbol","title":"country","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/country","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"country","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"country","kind":"identifier"}],"abstract":[{"type":"text","text":"The country where card was issued, e.g. “US” for “United States”"}],"url":"\/documentation\/dldirectsdk\/dlbininfo\/country"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLBinInfo/bin":{"navigatorTitle":[{"text":"bin","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The bin number of the card (first 6 digits), e.g. “424242”"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/bin","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bin"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/dldirectsdk\/dlbininfo\/bin","kind":"symbol","title":"bin"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardTokenizer/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)":{"navigatorTitle":[{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"type":"topic","title":"getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","url":"\/documentation\/dldirectsdk\/dlcardtokenizer\/getbininformation(binnumber:currencycode:amount:onsuccess:onerror:)","abstract":[{"type":"text","text":"Get bin information and installments."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getBinInformation"},{"kind":"text","text":"("},{"text":"binNumber","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currencyCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"amount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onSuccess","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"DLBinInfo","preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLBinInfo","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"onError","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@DLDirectSDK@objc(cs)DLError","text":"DLError","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardTokenizer\/getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)","role":"symbol","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.dlocal.DLDirectSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DLBinInfo","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"DLBinInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DLBinInfo","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/bin","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/brand","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/country","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installments","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/installmentsError","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLBinInfo\/type"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLBinInfo"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"value":"type","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1type\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1installments\/title","value":"installments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1installments\/fragments","value":[{"kind":"identifier","text":"installments"}]},{"op":"replace","value":"getBinInformationWithBinNumber:onSuccess:onError:","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:onSuccess:onError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getBinInformationWithBinNumber:onSuccess:onError:"}]},{"value":"brand","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1brand\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1brand\/fragments","op":"replace","value":[{"kind":"identifier","text":"brand"}]},{"value":"DLBinInfo","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo\/fragments","op":"replace","value":[{"text":"DLBinInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1installmentsError\/title","value":"installmentsError"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1installmentsError\/fragments","op":"replace","value":[{"text":"installmentsError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1country\/title","value":"country","op":"replace"},{"value":[{"text":"country","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1country\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1bin\/title","value":"bin","op":"replace"},{"op":"replace","value":[{"text":"bin","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLBinInfo~1bin\/fragments"},{"value":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"getBinInformationWithBinNumber:currencyCode:amount:onSuccess:onError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardTokenizer~1getBinInformation(binNumber:currencyCode:amount:onSuccess:onError:)\/fragments","op":"replace"}]}]}