{"abstract":[{"text":"The available card brand identifiers.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/SQ","doc:\/\/com.dlocal.DLDirectSDK\/SH","doc:\/\/com.dlocal.DLDirectSDK\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dldirectsdk\/dlcardbrandidentifier"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandIdentifier"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"DLDirectSDK"}],"role":"symbol","symbolKind":"enum","title":"DLCardBrandIdentifier","externalID":"c:@M@DLDirectSDK@E@DLCardBrandIdentifier","navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DLCardBrandIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK"]]},"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/americanExpress","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/argencard","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cabal","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cencosud","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cmr","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cordobesa","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/debcabal","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/dinersClub","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/discover","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/elo","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/hipercard","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/jcb","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/lider","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/maestro","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/magna","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mastercard","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mastercardDebito","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/meeza","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mercadopago","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/naranja","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/nativa","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/oca","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/presto","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/tarjetaShopping","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/unionpay","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/verve","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/visa","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/visaDebito"]},{"title":"Initializers","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/init(rawIdentifier:)","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/rawIdentifier"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/Equatable-Implementations","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/RawRepresentable-Implementations"],"generated":true}],"sections":[],"identifier":{"url":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","interfaceLanguage":"swift"},"references":{"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier":{"title":"DLCardBrandIdentifier","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier","abstract":[{"type":"text","text":"The available card brand identifiers."}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier","navigatorTitle":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DLCardBrandIdentifier"}]},"doc://com.dlocal.DLDirectSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SH"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/magna":{"title":"DLCardBrandIdentifier.magna","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierMagna"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/magna","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"magna","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/magna"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/lider":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/lider","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"lider","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/lider","type":"topic","title":"DLCardBrandIdentifier.lider","role":"symbol","navigatorTitle":[{"text":"DLCardBrandIdentifierLider","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/cordobesa":{"abstract":[],"title":"DLCardBrandIdentifier.cordobesa","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cordobesa"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cordobesa","role":"symbol","navigatorTitle":[{"text":"DLCardBrandIdentifierCordobesa","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cordobesa"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/rawIdentifier":{"title":"rawIdentifier","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/rawidentifier","abstract":[{"text":"The identifier as String.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/rawIdentifier"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/cabal":{"title":"DLCardBrandIdentifier.cabal","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierCabal"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cabal","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cabal"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cabal"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/verve":{"title":"DLCardBrandIdentifier.verve","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierVerve"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/verve","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verve"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/verve"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/presto":{"title":"DLCardBrandIdentifier.presto","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierPresto"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/presto","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presto"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/presto"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/jcb":{"title":"DLCardBrandIdentifier.jcb","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierJcb"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/jcb","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jcb"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/jcb"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/unionpay":{"title":"DLCardBrandIdentifier.unionpay","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierUnionpay"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/unionpay","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unionpay"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/unionpay"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/elo":{"title":"DLCardBrandIdentifier.elo","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierElo"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/elo","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"elo"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/elo"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/init(rawValue:)":{"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/init(rawvalue:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/init(rawValue:)","title":"init(rawValue:)","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/visaDebito":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"visaDebito"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/visaDebito","navigatorTitle":[{"text":"DLCardBrandIdentifierVisaDebito","kind":"identifier"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/visadebito","title":"DLCardBrandIdentifier.visaDebito","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/oca":{"title":"DLCardBrandIdentifier.oca","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierOca"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/oca","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"oca"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/oca"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/naranja":{"title":"DLCardBrandIdentifier.naranja","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierNaranja"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/naranja","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"naranja"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/naranja"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/discover":{"title":"DLCardBrandIdentifier.discover","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierDiscover"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/discover","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"discover"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/discover"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/cencosud":{"title":"DLCardBrandIdentifier.cencosud","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierCencosud"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cencosud","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cencosud"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cencosud"},"doc://com.dlocal.DLDirectSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SQ"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","type":"topic","kind":"article","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/Equatable-Implementations"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/debcabal":{"title":"DLCardBrandIdentifier.debcabal","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierDebcabal"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/debcabal","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debcabal"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/debcabal"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/mercadopago":{"title":"DLCardBrandIdentifier.mercadopago","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierMercadopago"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/mercadopago","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mercadopago"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mercadopago"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/maestro":{"title":"DLCardBrandIdentifier.maestro","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/maestro","navigatorTitle":[{"text":"DLCardBrandIdentifierMaestro","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maestro"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/maestro","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/nativa":{"title":"DLCardBrandIdentifier.nativa","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierNativa"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/nativa","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativa"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/nativa"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK":{"type":"topic","title":"DLDirectSDK","url":"\/documentation\/dldirectsdk","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK","role":"collection","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/mastercardDebito":{"title":"DLCardBrandIdentifier.mastercardDebito","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierMastercardDebito"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/mastercarddebito","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mastercardDebito"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mastercardDebito"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/cmr":{"title":"DLCardBrandIdentifier.cmr","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierCmr"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/cmr","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cmr"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cmr"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/mastercard":{"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mastercard","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/mastercard","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mastercard","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierMastercard"}],"abstract":[],"title":"DLCardBrandIdentifier.mastercard","kind":"symbol"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/argencard":{"title":"DLCardBrandIdentifier.argencard","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierArgencard"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/argencard","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"argencard"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/argencard"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/init(rawIdentifier:)":{"title":"init(rawIdentifier:)","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/init(rawidentifier:)","abstract":[{"type":"text","text":"Obtain the identifier from the raw String."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/init(rawIdentifier:)"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/meeza":{"title":"DLCardBrandIdentifier.meeza","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierMeeza"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/meeza","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"meeza"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/meeza"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/visa":{"title":"DLCardBrandIdentifier.visa","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierVisa"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/visa","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"visa","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/visa"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/hipercard":{"title":"DLCardBrandIdentifier.hipercard","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierHipercard"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/hipercard","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hipercard"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/hipercard"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/tarjetaShopping":{"title":"DLCardBrandIdentifier.tarjetaShopping","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/tarjetashopping","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/tarjetaShopping","navigatorTitle":[{"text":"DLCardBrandIdentifierTarjetaShopping","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"tarjetaShopping","kind":"identifier"}]},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","kind":"article","url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/RawRepresentable-Implementations"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/dinersClub":{"title":"DLCardBrandIdentifier.dinersClub","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierDinersClub"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/dinersclub","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dinersClub","kind":"identifier"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/dinersClub"},"doc://com.dlocal.DLDirectSDK/documentation/DLDirectSDK/DLCardBrandIdentifier/americanExpress":{"title":"DLCardBrandIdentifier.americanExpress","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DLCardBrandIdentifierAmericanExpress"}],"url":"\/documentation\/dldirectsdk\/dlcardbrandidentifier\/americanexpress","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"americanExpress"}],"identifier":"doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/americanExpress"},"doc://com.dlocal.DLDirectSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.dlocal.DLDirectSDK\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DLCardBrandIdentifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DLCardBrandIdentifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/americanExpress","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/argencard","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cabal","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cencosud","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cmr","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/cordobesa","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/debcabal","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/dinersClub","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/discover","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/elo","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/hipercard","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/jcb","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/lider","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/maestro","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/magna","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mastercard","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mastercardDebito","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/meeza","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/mercadopago","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/naranja","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/nativa","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/oca","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/presto","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/tarjetaShopping","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/unionpay","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/verve","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/visa","doc:\/\/com.dlocal.DLDirectSDK\/documentation\/DLDirectSDK\/DLCardBrandIdentifier\/visaDebito"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DLCardBrandIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/title","value":"DLCardBrandIdentifier"},{"value":[{"text":"DLCardBrandIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier\/fragments"},{"value":"DLCardBrandIdentifierMagna","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1magna\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1magna\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLCardBrandIdentifierMagna"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1lider\/title","value":"DLCardBrandIdentifierLider","op":"replace"},{"value":[{"text":"DLCardBrandIdentifierLider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1lider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cordobesa\/title","value":"DLCardBrandIdentifierCordobesa"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cordobesa\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierCordobesa"}],"op":"replace"},{"value":"DLCardBrandIdentifierCabal","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cabal\/title","op":"replace"},{"value":[{"text":"DLCardBrandIdentifierCabal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cabal\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1verve\/title","value":"DLCardBrandIdentifierVerve","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1verve\/fragments","op":"replace","value":[{"text":"DLCardBrandIdentifierVerve","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1presto\/title","value":"DLCardBrandIdentifierPresto","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1presto\/fragments","value":[{"text":"DLCardBrandIdentifierPresto","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1jcb\/title","op":"replace","value":"DLCardBrandIdentifierJcb"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1jcb\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierJcb"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1unionpay\/title","op":"replace","value":"DLCardBrandIdentifierUnionpay"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1unionpay\/fragments","op":"replace","value":[{"text":"DLCardBrandIdentifierUnionpay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1elo\/title","value":"DLCardBrandIdentifierElo"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1elo\/fragments","value":[{"text":"DLCardBrandIdentifierElo","kind":"identifier"}]},{"op":"replace","value":"DLCardBrandIdentifierVisaDebito","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1visaDebito\/title"},{"op":"replace","value":[{"text":"DLCardBrandIdentifierVisaDebito","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1visaDebito\/fragments"},{"value":"DLCardBrandIdentifierOca","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1oca\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1oca\/fragments","op":"replace","value":[{"text":"DLCardBrandIdentifierOca","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1naranja\/title","value":"DLCardBrandIdentifierNaranja"},{"value":[{"text":"DLCardBrandIdentifierNaranja","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1naranja\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1discover\/title","op":"replace","value":"DLCardBrandIdentifierDiscover"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1discover\/fragments","value":[{"text":"DLCardBrandIdentifierDiscover","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cencosud\/title","value":"DLCardBrandIdentifierCencosud"},{"op":"replace","value":[{"text":"DLCardBrandIdentifierCencosud","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cencosud\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1debcabal\/title","value":"DLCardBrandIdentifierDebcabal"},{"value":[{"text":"DLCardBrandIdentifierDebcabal","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1debcabal\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mercadopago\/title","value":"DLCardBrandIdentifierMercadopago","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DLCardBrandIdentifierMercadopago"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mercadopago\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1maestro\/title","value":"DLCardBrandIdentifierMaestro","op":"replace"},{"value":[{"text":"DLCardBrandIdentifierMaestro","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1maestro\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1nativa\/title","op":"replace","value":"DLCardBrandIdentifierNativa"},{"value":[{"text":"DLCardBrandIdentifierNativa","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1nativa\/fragments"},{"value":"DLCardBrandIdentifierMastercardDebito","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mastercardDebito\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mastercardDebito\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierMastercardDebito"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cmr\/title","op":"replace","value":"DLCardBrandIdentifierCmr"},{"value":[{"text":"DLCardBrandIdentifierCmr","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1cmr\/fragments","op":"replace"},{"value":"DLCardBrandIdentifierMastercard","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mastercard\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DLCardBrandIdentifierMastercard"}],"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1mastercard\/fragments"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1argencard\/title","op":"replace","value":"DLCardBrandIdentifierArgencard"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1argencard\/fragments","value":[{"text":"DLCardBrandIdentifierArgencard","kind":"identifier"}]},{"value":"DLCardBrandIdentifierMeeza","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1meeza\/title"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1meeza\/fragments","value":[{"text":"DLCardBrandIdentifierMeeza","kind":"identifier"}],"op":"replace"},{"value":"DLCardBrandIdentifierVisa","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1visa\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1visa\/fragments","value":[{"text":"DLCardBrandIdentifierVisa","kind":"identifier"}],"op":"replace"},{"value":"DLCardBrandIdentifierHipercard","op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1hipercard\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1hipercard\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierHipercard"}]},{"value":"DLCardBrandIdentifierTarjetaShopping","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1tarjetaShopping\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1tarjetaShopping\/fragments","value":[{"kind":"identifier","text":"DLCardBrandIdentifierTarjetaShopping"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1dinersClub\/title","value":"DLCardBrandIdentifierDinersClub","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1dinersClub\/fragments","op":"replace","value":[{"kind":"identifier","text":"DLCardBrandIdentifierDinersClub"}]},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1americanExpress\/title","value":"DLCardBrandIdentifierAmericanExpress","op":"replace"},{"path":"\/references\/doc:~1~1com.dlocal.DLDirectSDK~1documentation~1DLDirectSDK~1DLCardBrandIdentifier~1americanExpress\/fragments","value":[{"text":"DLCardBrandIdentifierAmericanExpress","kind":"identifier"}],"op":"replace"}]}]}